### ISSUE TITLE
Find tool for reviewing ontology structure and contents

### ISSUE THREAD

**Issue by alliyya** [cwrc/ontology#100]
Find the oxygen equivalent for LOD.
Feel free to add any possible applications as comments and we can evaluate them.

**Comment by alliyya** [comment]
Continually evaluating: Protege online http://webprotege.stanford.edu
August 27th: 
- Export to rdf/xml modifies ontology too much with unnecessary properties along with many comments, 4993 triples in original owl file and 5453 triples in exported.
- Incorrectly displays class hierarchy

**Comment by alliyya** [comment]
Cool Visualization of ontology, doesn't show the instance but does show some of the more general relations with the associated data 
http://visualdataweb.de/webvowl/#file=cwrc.owl

**Comment by SusanBrown** [comment]
Cool! Link didn't work was able to load https://raw.githubusercontent.com/cwrc/ontology/master/cwrc.owl

Would love to look over this at our meeting if time permits. 

Why is it showing some instances like white/white (deprecated) [ugh]/ Spirtualism/Unitarianism/Tractarian movement?

![image](https://user-images.githubusercontent.com/545952/29752306-8e226420-8b29-11e7-9981-aa063ca8ca52.png)

**Comment by rwarren2** [comment]
It's showing the instances because while they are deprecated, the nodes are still in the file.

**Comment by SusanBrown** [comment]
So perhaps the nodes that are showing up inappropriately (e.g. white) need to have their labels changed to indicate deprecation?



On Aug 28, 2017, at 10:59 PM, rwarren2 <notifications@github.com<mailto:notifications@github.com>> wrote:


It's showing the instances because while they are deprecated, the nodes are still in the file.

**Comment by alliyya** [comment]
@SusanBrown 
For some reason a few of the instances are being classifieds as a actual owl classes rather than instances, not too sure quite yet. I suspect it may have to do with how their system handles subclassing.

I do like that it does actually denote that the term is deprecated, most graphing things I played with used to lump everything together ignoring the deprecation completely. 

Would be nice if there were some in-depth more filtering options, it's still a work in progress. Ex. Not showing deprecated terms at all, showing instances.

I do think it's important to note that the tool isn't completely mature and not a complete reliable source for viewing all the connections within the ontology. I just thought it was a neat visual tool to keep an eye on should it mature into a more practical tool.

Sorry for the late response, I thought I hit comment ages ago.

Also regarding the deprecated terms, it is showing that they are deprecated in the brackets already using its vs:term_status and greyed out.

**Comment by alliyya** [comment]
Will be using [Top Braid Composer](https://www.topquadrant.com/tools/modeling-topbraid-composer-standard-edition/) for editing and viewing structure.
