### ISSUE TITLE
Ethnicity instances

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#108]
@rwarren2 and @colinraybrian I believe we still need the Ethnicity instances: both reg and free-form in separate lists.

**Comment by rwarren2** [comment]
Free form Ethnicity instances:

African-Americans
a Jewish
Amer-Indians
Anglo-Norman
Arab
Ashkenazim, or German Jewish
Bengali
black African descent
blood
Celtic
Chinese
Creole
English
European
gipsy
Greek
gypsies
gypsy
Highland
Highland (that is Celtic)
Igbo
Irish
Jamaican-born
Jewish
Jewry
Jews
one-quarter Jewish
Parsi
Punjabi
Sephardic Jewish
She asserted in a 
Slavic
Thracians
Wends or Sorbs
West Indian
white

**Comment by rwarren2** [comment]
Regularized values: 
African
African-American
Ashkenazim
Bengali
black
Celtic
England
European
foreign
gypsy
Irish
Jew
Jewish
Judaism
Roma
Thracian
Wendish
White
