### ISSUE TITLE
huvizTest4.ttl has a syntactically incorrect comment AFAICT

### ISSUE THREAD

**Issue by smurp** [cwrc/ontology#11]
The line

    !--Rob, should denomination be included under RaceEthnicityContext or be Denomination Context? (line 71)--!                          

is breaking a HuViz TTL parser.  I think it should be preceded with a hash character `#`

**Comment by smurp** [comment]
Could I have write permissions on this repo?  I've got fixes for this and #10

**Comment by rwarren2** [comment]
Done.
