### ISSUE TITLE
Clean up cwrc-template in regards to the new genre ontology

### ISSUE THREAD

**Issue by alliyya** [cwrc/ontology#110]
Update documentation concerning the split into a separate ontology and clean-up/organize current mentions of the genre ontology.

Do we still want the genre-taxonomy

**Comment by SusanBrown** [comment]
No we don't want the genre taxonomy image but we do want to keep the global cross-reference with links to the other ontology. Preamble needs to make it clear that this is a separate ontology.

**Comment by SusanBrown** [comment]
Abi to do: Spiel about how we split off the ontology, with link to the new one. Something in linkages to other ontologies
Alliya to do: put in new cross-reference with new links

**Comment by lemaka** [comment]
done!

**Comment by rwarren2** [comment]
Genre template is done, only a basic skeleton exists in french at this point. Will be done in #140, closing this ticket for DH2017 milestone.
