### ISSUE TITLE
Add Micaela Jimenez to list of ontology authors

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#118]

**Comment by alliyya** [comment]
Both ontologies or just the genre one?

**Comment by SusanBrown** [comment]
Just the genre one. 

Which raises a good point that we might as well be precise. Those involved in the genre one are you, rob, micaela, jade, and me.

@lemaka and @colinraybrian I just want to double check that you have not worked on the genre portion of the ontology. Google doesn't think so but you never know.
