### ISSUE TITLE
Revise Authors per Ontology 

### ISSUE THREAD

**Issue by alliyya** [cwrc/ontology#119]
#118

**Comment by alliyya** [comment]
CWRC Ontology Collaborators:
John Simpson
Abigel Lemak
Jade Penancier
Kim Martin
Colin Faulkner
Robert Warren
Alliyya Mo
Susan Brown

Genre Ontology:
John Simpson
Abigel Lemak
Jade Penancier
Kim Martin
Robert Warren
Alliyya Mo
Susan Brown
Micaela Jimenez

Please advise me I'm missing/misplacing anyone @SusanBrown

**Comment by SusanBrown** [comment]
thx @alliyya  I guess I wasn't clear my last on this :(

I think it should be (alphabetizing while we are at it):

CWRC Ontology Collaborators:
Susan Brown
Colin Faulkner
Abigel Lemak
Kim Martin
Alliyya Mo
Jade Penancier
John Simpson
Robert Warren
and members of the Orlando Project

Genre Ontology:
Susan Brown
Micaela Jimenez
Alliyya Mo
Jade Penancier
Robert Warren

**Comment by alliyya** [comment]
Sorry I just wanted it clear for everyone incase there was any objections or suggestions. The document generator takes care of the ordering. Will clean this up later today

**Comment by alliyya** [comment]
Also is there any email or website you'd like your name to link to @SusanBrown @antimony27 ?
