### ISSUE TITLE
Write up narrative credits

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#120]
Write up narrative credits describing each person's role in the ontology creation process qualitatively.

We can coordinate this through a google doc after DH2017.

**Comment by SusanBrown** [comment]
https://docs.google.com/document/d/1TfJfXzbR6P_RO3SzehQUuAlCsiYaUbHcA27AIUjb4mE/edit#heading=h.u9xbzp7mjvz4

**Comment by JasmineDW** [comment]
Update information on https://sparql.cwrc.ca/testing/our-team-EN.html

**Comment by JasmineDW** [comment]
Closing this issue in favor of https://github.com/cwrc/ontology/issues/453
