### ISSUE TITLE
Extraction test for RaceColour and Ethnicity

### ISSUE THREAD

**Issue by colinraybrian** [cwrc/ontology#121]
`<ETHNICITY SELF-DEFINED=SELFYES REG=African-American > <RACECOLOUR SELF-DEFINED=SELFYES REG=black > African </RACECOLOUR> - <NATIONALITY > American </NATIONALITY> </ETHNICITY> `
This should generate only two triples, can we see how many CF triples we would actually extract from this? Susan and I are wondering what the result of this test would be because the raceColour tag is nested in the ethnicity tag, and both have reg values.

**Comment by alliyya** [comment]
@SusanBrown Was this a real sample from Orlando?
Regardless would you not want 3 triples from this?

- cwrc:hasEthnicity cwrc:africanAmericanEthnicity
- cwrc:hasRaceColour cwrc:blackRaceColour
- cwrc:hasNationalIdentity "ISO 3166-2:US"^^xsd:string

**Comment by SusanBrown** [comment]
Yes you are right

**Comment by alliyya** [comment]
Created a sample person with cf tag including that tag entry
```xml 
                    <CULTURALFORMATION>
                        <DIV2>
                            <SHORTPROSE>
                                <P>She was 
                                    <ETHNICITY SELF-DEFINED="SELFYES" REG="African-American" > <RACECOLOUR SELF-DEFINED="SELFYES" REG="black" > African </RACECOLOUR> - <NATIONALITY > American </NATIONALITY> </ETHNICITY>
                                    .</P>
                            </SHORTPROSE>
                        </DIV2>
                    </CULTURALFORMATION>
```
The resulting triples from my extraction is
```ttl
cwrc:samplePerson a cwrc:NaturalPerson ;
    cwrc:hasEthnicitySelfReported cwrc:african-AmericanEthnicity ;
    cwrc:hasNationality "US"^^xsd:string ;
    cwrc:hasRaceColourSelfReported cwrc:blackRaceColour ;
    foaf:name "Sample data person" .
```
So test passed :)
