### ISSUE TITLE
Social Contexts: one or many?

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#123]
So we found an inconsistency in the data through an inconsistency in how things were showing up in HuViz.

Note the addition of Gentry to the URI in the second set:

`<http://www.cwrc.ca/cwrcdata/KINGSocialClass>
    a cwrc:SocialClassContext ;
    rdfs:label "Social Class Context for Sophia King"@en ;
    oa:hasBody cwrc:indigent ;
    oa:hasTarget <http://www.cwrc.ca/cwrcdata/SophiaKing> ;
    prov:derivedFrom cwrc:King12345 .

<http://www.cwrc.ca/cwrcdata/KINGSocialClassGentry>
    a cwrc:SocialClassContext ;
    rdfs:label "Social Class Context for Sophia King"@en ;
    oa:hasBody cwrc:gentry ;
    oa:hasTarget <http://www.cwrc.ca/cwrcdata/SophiaKing> ;
    prov:derivedFrom cwrc:King12345 .

<http://www.cwrc.ca/cwrcdata/KINGSocialClass>
    a cwrc:SocialClassContext ;
    rdfs:label "Social Class Context for Sophia King"@en ;
    oa:hasBody cwrc:professional ;
    oa:hasTarget <http://www.cwrc.ca/cwrcdata/SophiaKing> ;
    prov:derivedFrom cwrc:King12345 .`

I believe that these are broken out as separate nodes because @rwarren2 probably meant for us to distinguish each of them, e.g. KINGSocialClassProfessional and KINGSocialClassIndigent. Then they would show up as 3 distinct nodes, each pointing to their separate terms.

**Comment by rwarren2** [comment]
Exactly, the URIS need to be unique. But not the labels.

**Comment by SusanBrown** [comment]
Thanks for the confirmation.

However, we think that conceptually and in terms of how it shows up in HuViz it is actually more accurate and preferable to consider these as a single Social Class Context. To my mind this is not a problem: they are all typed the same, there would then be one label for one node (we certainly see the problem you were pointing to, @smurp!), they have multiple bodies and targets but that is fine according to OA, and they share the same provenance. 

So we would like to propose that all contexts related to the same cultural form (e.g. SocialClass) and deriving from the same snippet, should be combined into a single node. Is there any reason why they should be broken out?

**Comment by rwarren2** [comment]
No, in that specific case it comes out as the same thing.

**Comment by susanirenebrown** [comment]
So are you agreeing that this can be a single node in this case?

**Comment by rwarren2** [comment]
The creation of a context is the Orlando tag that creates it. If the contexts are aligning with each other in the Orlando source, then by definition they get the same provenance node and then they get the same context node.

We can probably do some fancy footwork to reduce the number of redundant context, but I would put this up as a nice to have.

**Comment by SusanBrown** [comment]
OK, right. I don't actually think we will need to reduce the number of contexts further. In the case of this data for instance, there is only one context tag, the highest-level one which I believe we agreed to call CulturalFormationContext. 

Here is the snippet:

`<CULTURALFORMATION >
<DIV2 ID=b--kingso--0--DIV2--3 >
<SHORTPROSE >
<P ID=b--kingso--0--P--2 > <NAME STANDARD=King, Sophia > SK </NAME> 's <GEOGHERITAGE > <ETHNICITY REG=Jewish > Sephardic Jewish </ETHNICITY> <PLACE > <GEOG REG=Portugal > Portuguese </GEOG> </PLACE> </GEOGHERITAGE> birth, her early years in <DENOMINATION REG=Judaism > Judaism </DENOMINATION> , and her father's <CLASS SOCIALRANK=INDIGENT > boyhood as a street urchin </CLASS> and his high-profile but scandalous career (associating with <POLITICALAFFILIATION REG=radical > political radicals </POLITICALAFFILIATION> while <CLASS SOCIALRANK=PROFESSIONAL > lending money </CLASS> to <CLASS SOCIALRANK=GENTRY > socialites </CLASS> and eventually marrying into the English nobility), made her an outsider in <NATIONALITY SELF-DEFINED=SELFYES REG=English > English </NATIONALITY> society. </P>
</SHORTPROSE>
</DIV2>
</CULTURALFORMATION> `

So in this case the data does not have the tag (ClassIssue) that would generate a SocialClassContext: it only has CulturalFormation. So the sample data doesn't actually reflect the markup. 

We may or may not decide to change it now, but I just want to confirm that we are on the same page.

**Comment by rwarren2** [comment]
Yes.
