### ISSUE TITLE
Cross-referencing within the ontology

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#126]
In the html version of the ontology, will a statement such as the following include a hyperlink to the definition of gender on the bolded term (which I realize won't be bolded--just done here for clarity):

A personal property, this indicates a person's self-defined gender. For more information on this property, see **gender**.

**Comment by rwarren2** [comment]
Not right now, but we can look at getting it done.

**Comment by SusanBrown** [comment]
excellent.


On Jul 30, 2017, at 11:57 AM, rwarren2 <notifications@github.com<mailto:notifications@github.com>> wrote:


Not right now, but we can look at getting it done.

**Comment by rwarren2** [comment]
In the meantime, please see notes in the Wiki https://github.com/cwrc/ontology/wiki/Creating-citations-within-the-CWRC-Genre-ontologies.
