### ISSUE TITLE
Genre terms ready for ingestion

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#129]
https://docs.google.com/spreadsheets/d/1jGLndleZu_tE07CkZrXNf93vnU7B8jYy7QzFswWvWFM/edit#gid=0

**Comment by SusanBrown** [comment]
I have a feeling that the "original text" column with the source text in it might prove useful to +jade.pncr@gmail.com for translation, so we should retain it until the translation is done, though you could move it elsewhere to get it out of your way when you extract the other info.

**Comment by alliyya** [comment]
For Getty and online sources, I'd like the specific getty page for the derived from. 
As the getty cwrc entry is a general entry about getty. Thanks.

Also is the Broader/narrower transitives to be part of the import?
