### ISSUE TITLE
rel:father, rel:mother, etc but no prefix definition for rel: in huvizTest4.ttl

### ISSUE THREAD

**Issue by smurp** [cwrc/ontology#13]
My guess is that what is intended is: http://id.loc.gov/vocabulary/relators/

May I suggest that we use the prefix `marcrel` for this purpose, per the guidance of http://prefix.cc ?

See: http://prefix.cc/marcrel

Happy to effect this change, just give me the GO code!

**Comment by smurp** [comment]
I notice that http://id.loc.gov/vocabulary/relators/ currently has different prefixes in different files -- as a followup to its apparently being what is likely intended by the prefix `rel:` in huvizTest4.ttl

| File | Prefix |
| ---- | ------ |
| cwrc.ttl | ns1: |
| data.ttl | loc: |
| huvizTest.ttl | loc: |
| huvizTest4.ttl | ns1: |

**Comment by rwarren2** [comment]
Prefixes change according to whatever converter it went through. Since they are local to the file being read, they aren't authoritative. 

You're welcome to change it, @prefix ns1: <http://id.loc.gov/vocabulary/relators/>  is the right one.

**Comment by smurp** [comment]
huvizTest4.ttl now parses correctly at http://alpha.huviz.dev.nooron.com/

see:  3f5c455 12fbba8 db07cb4 50e360b 64532fb c758f2d ba645f0

**Comment by smurp** [comment]
Drat!  It **parses** at http://alpha.huviz.dev.nooron.com/ but I have only seen it both **parse** and **display** when I run it try it in my development environment!  I think this is now in the realm of HuViz.  See https://github.com/smurp/huviz/issues/82

**Comment by susanirenebrown** [comment]
Oh dear. Perhaps we should just let it go and figure we’ll work with what we’ve got? At any rate, Rob, stop banging your head against it.
Thanks, both of you.

**Comment by susanirenebrown** [comment]
Ok. I've confirmed that Shawn's fixes to the data are working properly. But I can't get huviz to parse it in firefox / chrome. -rhw

**Comment by smurp** [comment]
Success!  Try loading the latest version of huvizTest4.ttl into http://alpha.huviz.dev.nooron.com/orlonto.html

**Comment by smurp** [comment]
4cdaa7184c8cc9c0ca5d1af8f188b689ed0734d5 fixes `data.ttl` so it works properly in http://alpha.huviz.dev.nooron.com/orlonto.html
