### ISSUE TITLE
Import of political affiliation instances can go ahead

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#130]
https://docs.google.com/spreadsheets/d/1_6q0WZIF7xeCdUIwQs3JXEml8Wo_4a8KTNrT_Kodwls/edit#gid=0

**Comment by alliyya** [comment]
Waiting for dbpedia to be back up to run scrape

**Comment by alliyya** [comment]
@SusanBrown 
@colinraybrian 
- There are no french definitions, is this wanted (for the {cwrc definitions} column)? 
- Want to clarify, that I'm meant to grab the french label and french definition in the {Definition (EN) - Wikipedia} column
- In the column for cwrc definitions, what is meant by see also:
    - > Advocacy or activism opposing the caste system in India. See $https://en.wikipedia.org/wiki/Caste_system_in_India; $https://en.wikipedia.org/wiki/Caste_politics; $https://en.wikipedia.org/wiki/Dalit 

    - Are you meaning to link to this wikipedia page in the definition as a citation?
    - Are we indebted to this source?
    - Should we be subclassing this source?

**Comment by susanirenebrown** [comment]
answered in person :)

**Comment by alliyya** [comment]
Conclusion: 

Linking directly to wikipedia page in definition 
and derived from dbpedia equivalent
