### ISSUE TITLE
Religion: Judaism French definition

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#135]
Begins with reference to Encyc Britannica--is that really how the French definition for Judaism begins @jadepncr ?

**Comment by jadepncr** [comment]
Indeed, that is not what is reflected on the Wiki page. What should we do ?

**Comment by alliyya** [comment]
Grab first 2 paragraphs of french https://fr.wikipedia.org/wiki/Juda%C3%AFsme
