### ISSUE TITLE
Dissenting Christianity

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#137]
French label needs to be translated into a noun

**Comment by jadepncr** [comment]
There is no official French equivalent as a noun form for this term. But I think that "non-conformisme" ou "dissidence anglaise" based on the related wiki articles

**Comment by susanirenebrown** [comment]
Yes it is very close to nonconformism, which has a more specific meaning—I think we have a term for that as well, though, so the latter might be better.

**Comment by jadepncr** [comment]
Right, so I edit as "dissidence anglaise"

**Comment by susanirenebrown** [comment]
If that works to your ear, let’s go with it.

**Comment by alliyya** [comment]
Completed in 7248abb6be1e8d8bfbb5902fc19115b063f8a23c
