### ISSUE TITLE
Dissenting Christianity definition fix

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#138]
Definition should begin, 

A branch of Christianity founded through dissent from the Anglican Church, commonly known after 1660 as Nonconformism. Dissenters are "members of a religious body... [etc] as in 1911 encyc brittanica. 

Then insert the definition from https://en.wikipedia.org/wiki/Nonconformist but also cite Definition: https://en.wikipedia.org/wiki/English_Dissenters (DO NOT use the one listed for Dissenters as it is not nearly as good).

**Comment by colinraybrian** [comment]
It will look like this then:
A branch of Christianity founded through dissent from the Anglican Church, commonly known after 1660 as Nonconformism.&quot;In English church history, a nonconformist was a Protestant who did not &quot;conform&quot; to the governance and usages of the established Church of England. Broad use of the term was precipitated after the Restoration of the British monarchy in 1660, when the Act of Uniformity 1662 re-established the opponents of reform within the Church of England. By the late 19th-century the term specifically included the Reformed Christians (Presbyterians, Congregationalists and other Calvinist sects), plus the Baptists and Methodists. The English Dissenters such as the Puritans who violated the Act of Uniformity 1559 — typically by practising radical, sometimes separatist, dissent — were retrospectively labelled as nonconformists.

By law and social custom, nonconformists were restricted from many spheres of public life—not least, from access to public office, civil service careers, or degrees at university—and were referred to as suffering from civil disabilities. In England and Wales in the late 19th century the new terms &quot;free churchman&quot; and &quot;Free Church&quot; started to replace &quot;dissenter&quot; or &quot;Nonconformist.&quot;&quot;. Also see ttps://en.wikipedia.org/wiki/English_Dissenters

**Comment by alliyya** [comment]
@SusanBrown 
Current definition for #dissentingChristianity

`&quot;One who dissents or disagrees in matters of opinion, belief, &amp;c. The term 'dissenter' is, however, practically restricted to the special sense of a member of a religious body in England which has, for one reason or another, separated from the Established Church. Strictly, the term includes the English Roman Catholics, who in the original draft of the Relief Act of 1791 were styled “Protesting Catholic Dissenters.” It is in practice, however, restricted to the “Protestant Dissenters” referred to in sec. ii. of the Toleration Act of 1688.&quot;<![CDATA[<a href="#_britannica_1911">(Encyclopedia Britannica, 1911)</a>]]>`

is this to be completely disregarded and replaced with Collin's definition. Or should this be an additional definition?

**Comment by alliyya** [comment]
Use English Dissenters, and reference nonconformist.  Disregard Britannica
