### ISSUE TITLE
Occultism definition needs source

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#139]

**Comment by SusanBrown** [comment]
Also please scrutinize all the religions listed as having it as an skos:broader term. I am not at all sure most of them are justified.

**Comment by colinraybrian** [comment]
Reflected in https://docs.google.com/spreadsheets/d/1l0fHHhUv_212CMmCkC6NVJCc0L_I6gPt6Ppu57ni7N8/edit#gid=0
I'm not sure why occultism is a broader term for so many religions. Maybe @lemaka knows?

**Comment by rwarren2** [comment]
Removing broader
