### ISSUE TITLE
Sexual Identity

### ISSUE THREAD

**Issue by rwarren2** [cwrc/ontology#14]
I've liked to http://homosaurus.org for sexual identity with owl:sameas as they only have properties.

I've linked to sexualIdentity, heterosexualIdentity and lesbianIdentity. There is no homosexual identity to link to.

Q: homosexual and lesbian have gender implication. How do we link / record this?

**Comment by SusanBrown** [comment]
Great.

Lesbian identity has gender implications but homosexual doesn’t.

So anyone who hasSexualIdentity lesbianIdentity also hasGender woman, by inference

Gay male identity doesn’t appear in the list, which seemed like an omission given their other terms. Inferring from the related terms here http://homosaurus.org/terms/gayIdentity it looks like they are defining gay identity as exclusively male which is not right, imo.

So I would suggest we have homosexuality, with lesbianIdentity and gayMaleIdentity as subclasses, and then we can link gayMaleIdentity to hasGenderMale

NB they have genderIdentity, transgenderIdentity so we should like to those too.


On Jan 27, 2017, at 10:22 AM, rwarren2 <notifications@github.com<mailto:notifications@github.com>> wrote:


I've liked to http://homosaurus.org<http://homosaurus.org/> for sexual identity with owl:sameas as they only have properties.

I've linked to sexualIdentity, heterosexualIdentity and lesbianIdentity. There is no homosexual identity to link to.

Q: homosexual and lesbian have gender implication. How do we link / record this?

**Comment by alliyya** [comment]
Is this resolvable or should it be pinned for memory?
