### ISSUE TITLE
Language instances don't need defining

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#143]
We are using a set of standard codes for language so we don't need to define them.

**Comment by lemaka** [comment]
can @rwarren2 please point to which standard codes for language we are drawing on?

**Comment by rwarren2** [comment]
http://id.loc.gov/vocabulary/iso639-1/iso639-1_Language

See the definition for Language in the ontology http://sparql.cwrc.ca/testing/cwrc.html#Language
