### ISSUE TITLE
Terms missing from Ontology

### ISSUE THREAD

**Issue by antimony27** [cwrc/ontology#144]
After working with datafile, I couldn't find the following in the dataset - could someone either add them, or advise me if should be something different?

evangelical
NationalityIssueContext
Proto-zionist (Susan said this could be Zionist, but I can't find that either)
NationalHeritageSelfReported
EnglishNationality

Also - should Agnosticism be Agnostic?

Cheers!

**Comment by colinraybrian** [comment]
There's a bit of cross-over with instances, so I'm assuming you mean the political affiliation of zionism. Zionist isn't a term, Zionism is though, and it's in the PA spreadsheet.
Proto-zionist is now a variant term for Zionism. 
Is evangelical supposed to be a religious term? 
Agnosticism should be left that way, in the noun version like the other religions.
Not sure about the other 3

**Comment by colinraybrian** [comment]
NationalityIssueContext should just be NationalityContext, according to Susan

**Comment by rwarren2** [comment]
@antimony27  Let's go through it together tomorrow.

**Comment by alliyya** [comment]
@antimony27 Was evangelical or an equivalent term found?

**Comment by antimony27** [comment]
@alliyya I can't see one. "evangelical" is mentioned 8 times in the ontology, but is not defined. @SusanBrown @lemaka Do we need to include this?

**Comment by lemaka** [comment]
we need an evangelicalChristian instance and definition to add to the ontology

**Comment by alliyya** [comment]
NationalityIssueContext We have NationalityContext, @SusanBrown Is this necessary
~Proto-zionist (Susan said this could be Zionist, but I can't find that either)~  is found now #zionism - Zionism
NationalHeritageSelfReported 
We have #hasGeographicHeritageSelfReported
#hasNationalitySelfReported

~EnglishNationality~ is now found #EnglishNationalIdentity -English

**Comment by SusanBrown** [comment]
Keep @nationalityContext; deprecate/leave out NationalityIssue Context

I couldn't follow what was still needed. From what I can tell these are still needed:
NationalHeritageSelfReported
hasGeographicHeritageSelfReported

**Comment by lemaka** [comment]
sorry, so which of these do we still need @alliyya ?

**Comment by alliyya** [comment]
@SusanBrown                        hasNationalHeritageSelfReported and hasNationalHeritage are not currently in the ontology, these properties should be created correct?
