### ISSUE TITLE
First round ontology review

### ISSUE THREAD

**Issue by rwarren2** [cwrc/ontology#146]

**Comment by alliyya** [comment]
<cwrc:SocialClass rdf:about="#lowerMiddleClass">
    <rdfs:label xml:lang="en">lower-middle class</rdfs:label>
    <rdfs:label xml:lang="fr">classe-moyenne inférieure</rdfs:label>
    <skos:inScheme rdf:resource="#SocialClass"/>
    <rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#Concept"/>
    <skos:definition xml:lang="en">Employees, clerical workers, teachers, governesses. Note, however, that some teachers go into Professional **(Mr. Chips)** and women starting schools and then managing them also go into Professional.</skos:definition>
    <skos:definition xml:lang="fr"/>
    <rdfs:isDefinedBy rdf:resource="http://sparql.cwrc.ca/ontologies/cwrc-ONTOLOGY_DATE"/>
    <void:inDataset rdf:resource="#datasetdefinition"/>
  </cwrc:SocialClass>

Who is Mr. Chips and is this intended

**Comment by susanirenebrown** [comment]
Yes. See https://en.wikipedia.org/wiki/Goodbye,_Mr._Chips_(1939_film) <https://en.wikipedia.org/wiki/Goodbye,_Mr._Chips_(1939_film)>

Revise to “(Mr. Chips from the 1939 film of that name)”

**Comment by alliyya** [comment]
Notes:
#84 contraryTo property has been created
Using skos:broaderTransitive instead of skos:broader except in reference to text labels.
Church of England vs Anglicanism #134

**Comment by rwarren2** [comment]
Closing as this is done.
