### ISSUE TITLE
Genre Ontology Proof Report

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#149]
1. The quotations don’t seem in place within the genre onto
—> eg.

**A ballade (from French ballade, [baˈlad], and German Ballade, [baˈlaːdə], both being words for "ballad"), in classical music since the late 18th century, refers to a setting of a literary ballad, a narrative poem, in the musical tradition of the Lied, or to a one-movement instrumental piece with lyrical and dramatic narrative qualities reminiscent of such a song setting, especially a piano ballad. (DBpedia, 2017)**

— this seems to be almost always the case throughout the doc

2. Authors missing from the following citation:

Susan Brown, Abigel Lemak, Colin Faulkner, and Rob Warren. Cultural (Re-)formations: Structuring a Linked Data Ontology for Intersectional Identities. In The Proceedings of the Digital Humanities Conference, Montreal, Canada, 2017.

3. For the bibliography, it seems to have imported abstracts from Zotero in some cases: looks odd and should be removed

4. The in-text citations are not linked to anything — should they be?

**Comment by lemaka** [comment]
happy to make these changes manually (though perhaps not the one re: quotation makrs), but just wanted to first check in quickly here

**Comment by rwarren2** [comment]
Are the quotes supposed to be there for all of these? I thought some were adaptations?

If you can edit the DH citation (don't have a cwrc account), I'll see what I can do about the inline ones.

**Comment by rwarren2** [comment]
@lemaka Can you fix the follow in cwrc ontology biography entry:

`Authors missing from the following citation:
Susan Brown, Abigel Lemak, Colin Faulkner, and Rob Warren. Cultural (Re-)formations: Structuring a Linked Data Ontology for Intersectional Identities. In The Proceedings of the Digital Humanities Conference, Montreal, Canada, 2017.`

**Comment by SusanBrown** [comment]
Is this done @lemaka ? Are all the items above taken care of?
