### ISSUE TITLE
extracting adjectival genre forms

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#151]
Consider if there is anything we can do in extraction to reflect combinations of genre such as feminist+novel.

**Comment by rwarren2** [comment]
We can simply tag the document with multiple hasGenre?

**Comment by SusanBrown** [comment]
Yes we could, but that would not distinguish between two genres when one is nested inside the other, so that one has detective + novel, and when two genres are used separately. However, I am not sure that the nesting has been consistent enough to merit the distinction.


On Aug 14, 2017, at 5:44 PM, rwarren2 <notifications@github.com<mailto:notifications@github.com>> wrote:


We can simply tag the document with multiple hasGenre?
