### ISSUE TITLE
Review contraryTo for Political Affiliations

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#153]

**Comment by jadepncr** [comment]
**Contrary to**
abolitionism > pro-slavery 
anti-american > american nationalist / pro-american
anti-bonapartism > bonapartism 
anti-european > pro-european 
anti-feminism > suffrage 
anti-racism > racism 
anti-war > pro-boer war 
antidisestablismentarianism > disestablismentarianism
bolshevism > anti-bolshevism 
bonapartism > anti-bonapartism 
communism > anti-communism, liberalism 
disestablismentarianism > antidisestablismentarianism
dreyfusard > anti-dreyfusard 
fascism > anti-fascism 
feminism > anti-feminism 
imperialism > anti-imperialism 
jewish emancipation > antisemitism 
liberalism > communism 
monarchism > anti-monarchism
nazism > anti-antisemitism 
pacifism > anti-pacifism 
pro-american > anti-american
pro-boer war > anti-boer, anti-war
pro-catholicism > anti-catholicism 
pro-choice > conservatism 
pro-slavery > abolitionism, black anti-oppression, anti-racism
racial equality > racism 
racism > racial equality, abolitionism, black anti-oppression, anti-racism
sexual reform > conservatism 
zionism > anti-zionism


//Suggestions for other relational predicates//

**Related to**
anti-racism > black anti-oppression
birth control activism > feminism, pro-choice, sexual reform
bolshevism > communism 
co-operative movement > social reform 
communism > bolshevism, maoism, marxism , socialism 
conservatism > neo-conservatism 
conservative feminism > conservatism 
dress reform > feminism 
educational reform > social reform
elder rights > civil rights 
gay rights > civil rights 
girondins > jacobinism 
housing movement > social reform, civil rights 
indian independence > anti-imperialism
indigenous rights > human rights 
irish home rule > irish nationalism, irish unionism ( ?) 
jacobism > girondin  
labour movement > socialism, social reform 
liberal unionist party > liberalism, irish home rule 
maoism > communism 
marxism > communism, revolutionary politics 
nationalism > patriotism 
nazism > antisemitism, fascism 
pacifism > anti-war movement, anti-conscriptionism
patriotism > nationalism 
pro-catholicism > catholicism 
pro-choice > birth control activism
property law reform > social reform 
revolutionary politics > marxism 
sabbatarianism > catholicism 
sexual reform >  birth control activism, social purity, pro-choice 
stalinism > communism, marxism, bolshevism 
temperance movement > conservatism
womanism > anti-racism 

**Broader term**
birth control activism > social reform 
children's welfare > human rights 
civil libertarianism > libertarianism 
educational reform > civil rights
irish nationalism > nationalism 
mariage law reform > social reform 
spanish republicanism > republicanism 

**Other problems (but not entirely sure):**
- should anti-caste movement and society of friends be related to feminism ? 
- dreyfusard cannot be related to antisemitism (not every dreyfusard was anti-semitic) 
- capitalism does not exist as an ontological term, but it appears as a contrary term of anti-capitalism

**Comment by SusanBrown** [comment]
I've reviewed and approved the above. @joelacummings or @alliyya can proceed to put in these relationships. Not all inverse relationships are covered here but assume they should be. Some of these relationships may have replicated ones that are already in the ontology as a result of our review process.

**Comment by joelacummings** [comment]
Ok I'll start on it tonight!

**Comment by rwarren2** [comment]
Yes, the Dreyfus story is sufficiently complex that the word needs nailing down.

**Comment by joelacummings** [comment]
All relations are added that were possible.

**Comment by lemaka** [comment]
@jadepncr to add definitions in the ontology for the above
