### ISSUE TITLE
Add pantheist to religions

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#158]

**Comment by alliyya** [comment]
@SusanBrown add this term with definition gathered from https://en.wikipedia.org/wiki/Pantheism / http://dbpedia.org/resource/Pantheism

**Comment by susanirenebrown** [comment]
Was this a question about whether this definition was ok? It’s fine.

**Comment by alliyya** [comment]
Yup, sorry for not being clear there. 

Is there any religion that is a broader/narrower transitive that I should note down as well?

**Comment by susanirenebrown** [comment]
I don’t believe so offhand.
