### ISSUE TITLE
Review French definitions for Sexuality

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#161]

**Comment by lemaka** [comment]
- [ ] fix typo under hétérosexualité: "ll’hétérosexualité"
- [ ] fix typoe "et **la** «la nécessité"

**Comment by JasmineDW** [comment]
@jadepncr Just want to double check this line under 'lesbianisme'. Wondering if we need to add "qui contient" or an equivalent: 

> Adrienne Rich interprète l'hétérosexualité comme obligatoire pour les femmes dans un contexte patriarcal, et évoque un continuum lesbien, **[qui contient?]** les «diverses expériences spécifiques aux femmes—au cours de leur existence ou à travers l'Histoire— et non simplement le fait qu'une femme a eu ou a consciemment désiré avoir des expériences sexuelles avec une autre femme»

**Comment by alliyya** [comment]
See Translation catch-up #479 for updates
