### ISSUE TITLE
Review french definition for Language

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#164]

**Comment by jadepncr** [comment]
- [ ] langue 

Une langue ou un dialecte humain, à l'oral et/ou à l'écrit.

**Comment by alliyya** [comment]
@jadepncr Could you also provide a definition for the the note about the term

```xml
<skos:note xml:lang="en"> <![CDATA[<a href="http://id.loc.gov/vocabulary/languages.html">Library of Congress Languages</a>]]> codes are typically used for instances of <![CDATA[<i>language</i>]]> .</skos:note>
```

Thanks!

**Comment by jadepncr** [comment]
<skos:note xml:lang="fr"> Les codes de la <![CDATA[<a href="http://id.loc.gov/vocabulary/languages.html">Bibliothèque du congrès</a>]]> sont normalement utilisés pour les instances de <![CDATA[<i>langage</i>]]> .</skos:note>

Here!

**Comment by alliyya** [comment]
Awesome, thanks so much!
