### ISSUE TITLE
Review french definition for Geographic Heritage

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#167]

**Comment by lemaka** [comment]
looks good -- we only have two instances (english and jewishGeographicalHeritage -- but neither have, nor seem to require, a definition.

**Comment by lemaka** [comment]
going to do a scan of geographical heritage across Orlando just to be safe

**Comment by lemaka** [comment]
yes, there are certainly more geographic heritage instances than the ones captured in our current ontology (not sure if they are crucial at this point, but a scrape would be helpful in assessing which ones need to be added)

the french definition itself is fine

**Comment by alliyya** [comment]
http://sparql.cwrc.ca/testing/cwrc.html#GeographicHeritage
skos:note:  Geonames terms are often used for locations and for many instances of geographic heritage.

This is a rather dated ticket and will likely be reassessed during Jade's review of the whole ontology. 
Closing
