### ISSUE TITLE
Review french definition for Political Affiliation

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#170]

**Comment by lemaka** [comment]
I've caught a few missing definitions (which could be because they don't have english equivalents -- will do some more digging). There are also a few typos -- @alliyya , can we replace quotes with guillaumes throughout the french version?

- [ ] http://sparql.cwrc.ca/testing/cwrc#anarchism -- cut down? (it's very long!)
- [ ] http://sparql.cwrc.ca/testing/cwrc#anti-Apartheid -- doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#anti-Boer -- doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#anti-CorporalPunishment  -- doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#anti-Monarchism -- doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#anti-Suffrage -- doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#antidisestablishmentarianism --  doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#britishNationalism --  doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#christianSocialism --  doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#civilLibertarianism --  doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#communalism --  doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#communism -- cut down? (it's very long!)
- [ ] http://sparql.cwrc.ca/testing/cwrc#conscientiousObjection --  doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#disestablishmentarianism --  doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#dressReform --  doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#educationReform --  doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#egyptianNationalism --  doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#elderRights --  doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#fascism -- cut down? (it's very long!)
- [ ] http://sparql.cwrc.ca/testing/cwrc#freeTradeMovement --  doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#germanNationalism --  doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#greekNationalist --  doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#indianIndependence -- typo "45xCe modèle est-il pertinent ?"
- [ ] http://sparql.cwrc.ca/testing/cwrc#irishHomeRuleMovement --  doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#irishUnionism -- typo (extra space) " Pour"
- [ ] http://sparql.cwrc.ca/testing/cwrc#liberalUnionistParty -- typo/duplicate text: * Portail de la politique britannique" Portail de la politique britannique"
- [ ] http://sparql.cwrc.ca/testing/cwrc#multiculturalism -- typo: missing opening quotation: Le multiculturalisme
- [ ] http://sparql.cwrc.ca/testing/cwrc#multiracialism -- doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#nonjurorsMovement -- doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#polishNationalism -- doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#poorLawReform -- doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#prisonReform -- doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#pro-Choice -- typo (extra space): " Pour
- [ ] http://sparql.cwrc.ca/testing/cwrc#pro-Slavery -- doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#racialEquality -- doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#radicalism -- doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#revolutionaryPolitics -- doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#sabbatarianism -- doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#socialPurity -- doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#socialReform -- doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#socialism -- cut down? (it's very long!)
- [ ] http://sparql.cwrc.ca/testing/cwrc#spanishRepublicanism -- doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#toryPartyBritain -- doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#welshNationalism -- typo (missing opening quote & strange duplicants): Le nationalisme &  * Portail de la politique britannique Portail de la politique britannique * Portail du pays de Galles" Portail du pays de Galles"
- [ ] http://sparql.cwrc.ca/testing/cwrc#whiggism -- doesn't have a definition
- [ ] http://sparql.cwrc.ca/testing/cwrc#womanism -- doesn't have a definition

**Comment by alliyya** [comment]
See Translation catch-up #479 for updates
