### ISSUE TITLE
Addition of Competency Questions

### ISSUE THREAD

**Issue by joelacummings** [cwrc/ontology#171]
Within the description of the ontology in the OWL file we should add competency questions to give users and ourselves the goals and use cases of the ontology. This will allow future users to determine if the ontology will serve their needs. Additionally, it gives us developers goal points and requirements for the ontology to meet. 

Competency Questions are considered to be 

> "problems to define an ontology's requirements in the form of questions that an ontology must be able to answer."

An example of a competency question from a Health Ontology is: 

> “What is the epidemiological proﬁle of patients in a given region, i.e. age range, gender and ICD (International Classiﬁcation of Diseases)?”

Attached is the paper by Fox and Gruninger which introduces competency questions. 

[gruninger-ijcai95.pdf](https://github.com/cwrc/ontology/files/1271233/gruninger-ijcai95.pdf)

**Comment by joelacummings** [comment]
Google Doc: https://docs.google.com/document/d/1Tkb84-AuUps3a5qrA3X5mg6BrvWG9XC0FKzZPqIKSqY/edit?ts=59f2baee#heading=h.yjamgjgysznn

**Comment by joelacummings** [comment]
Once these are added I will directly add them to the Ontology, via a CompetencyQuestion Class.

**Comment by SusanBrown** [comment]
Added sufficiently for this next release.

Sub annotation properties will be needed to group them better for adding into the ontology proper.
