### ISSUE TITLE
Ontology Licensing

### ISSUE THREAD

**Issue by rwarren2** [cwrc/ontology#172]
Currently, we have both ontologies under a Creative Commons Attribution-NonCommercial 4.0 International License. This effectively bar people from using it for a commercial purposes, which includes say a museum using it for it's own systems. Should be move to something like a Creative Commons Attribution license to allow for more widespread, long term use of the ontologies (as opposed to the Orlando data)?

**Comment by SusanBrown** [comment]
Fine: let's move to CC-BY then.

**Comment by rwarren2** [comment]
Change in both ontologies.
