### ISSUE TITLE
Missing Definition for "anti-dreyfusard"

### ISSUE THREAD

**Issue by joelacummings** [cwrc/ontology#174]
Within Issue #153 a contraryTo from dreyfusard to anti-dreyfusard was suggested however, there is no definition for anti-dreyfusard within the ontology. I'm assuming this definition is necessary, correct me if I'm wrong.

**Comment by SusanBrown** [comment]
@lemaka Could you check whether there is an instance of it in the data. I think so but am not sure.

**Comment by joelacummings** [comment]
We are also missing Jacobinism which was also noted in #153, all other classes are linked however.

**Comment by SusanBrown** [comment]
Abi, this one I think we should definitely add regardless of whether we have instances. We can adopt this: https://en.wikipedia.org/wiki/Jacobin_(politics)


On Sep 9, 2017, at 10:33 PM, Joel Cummings <notifications@github.com<mailto:notifications@github.com>> wrote:


We are also missing Jacobinism which was also noted in #153<https://github.com/cwrc/ontology/issues/153>, all other classes are linked however.
