### ISSUE TITLE
Add genre definitions in english

### ISSUE THREAD

**Issue by rwarren2** [cwrc/ontology#18]
Reference from:
5. Where can we scrape for genre definitions?
From Getty: http://www.getty.edu/research/tools/vocabularies/aat/
General: http://web.cn.edu/kwheeler/lit_terms.html 
For poetry: http://www.poetrymagnumopus.com/index.php?showtopic=1236

**Comment by rwarren2** [comment]
Taxonomy graph needs tweaking since it's 117 pixels high right now and unreadable.

**Comment by alliyya** [comment]
**Missing English definitions**
aclef
adventure writing
advertising copy
afterpiece
afterword
answer
anthem
antiromance
apology
art criticism
ballad opera
ballet
bergamasque
biblical paraphrase
biographical dictionary
bisexual fiction
boutsrimes
broadside
burletta
cabaret
charade
closetdrama
comedy of intrigue
comedy of menace
coming out
companion
condition of england novel
conduct literature
courtshipfiction
criminology
dialogue of the dead
dialogue or debate
dissertation
documentary
dreamvision
erotica pornography
feminist theory
film tv script
folksong
gardening book
georgic
government report
graveyard poetry
harlequinade
imitation
industrial novel
introduction
journalism
kitchensink drama
kunstlerroman
legal writing
legend folktale
letter
letters from the dead to the living
literary criticism
liturgy
love
magic realist
map
medical writing
mixed media
mockforms
morality mystery play
multimedia
musicology
national tale
one act play
opera
oratorio
oriental
pageant
pantomime
paratexts
pedagogy
philosophical
pindaric
political writing
prefatory piece
proletarianwriting
psalm
psychoanalytical
quiz
radio drama
realist
religious
review
scholarship
school fiction
scientific writing
scrapbook
sexual awakening fiction
silverfork novel
slave narrative
social science
theatre of cruelty
theatre of the absurd
theology
thesaurus
thriller
tract pamphlet
travel writing
young adult writing

**Comment by alliyya** [comment]
**Missing French Defintions - possibly french labels as well**
abridgement
aclef
adaptation
adventure writing
advertising copy
afterpiece
afterword
agitprop
anagram
annotation
answer
anthem
anthology
antiromance
aphorism
apology
art criticism
autobiography
ballade
ballad opera
ballet
bergamasque
bestiary
biblical paraphrase
biographical dictionary
bisexual fiction
boutsrimes
broadside
burletta
cabaret
captivity narrative
chapbook
character
charade
childrens literature
clerihew
closetdrama
colouring book
comedy
comedy of intrigue
comedy of menace
comicbook
coming out
common place book
companion
computer program
condition of england novel
conduct literature
courtshipfiction
criminology
dedication
devotional
dialogue of the dead
dialogue or debate
diary
dictionary
didactic
directory
dissertation
documentary
domestic
drama
dreamvision
dystopia
encyclopaedia
epic
epilogue
epistolary
epitaph
epyllion
erotica pornography
exhibition catalogue
fable
fabliau
fairytale
farce
feminist
feminist theory
fiction
film tv script
folksong
gardening book
genealogy
georgic
giftbook
gothic
government report
grammar
graveyard poetry
guidebook
haiku
harlequinade
heroic
historical
history
hymn
imitation
industrial novel
introduction
journalism
juvenilia
kitchensink drama
kunstlerroman
lais
lampoon
legal writing
legend folktale
lesbian
letter
letters from the dead to the living
libretto
literary criticism
liturgy
love
lyric
magic realist
manifesto
manual
map
masque
medical writing
melodrama
mixed media
mockforms
morality mystery play
multimedia
musicology
mystery
national tale
notebook
novel
novella
nurseryrhyme
obituary
occasional poetry
ode
one act play
opera
oratorio
oriental
pageant
panegyric
pantomime
paratexts
pastoral
pedagogy
periodical
petition
philosophical
philosophy
pindaric
political writing
popular
prayer
prefatory piece
proletarianwriting
prologue
propaganda
psalm
psychoanalytical
quiz
radio drama
realist
regional
religious
review
revue
riddle
romance
sage writing
scholarship
school fiction
scientific writing
scrapbook
sentimental
sequel
sexual awakening fiction
short story
silverfork novel
sketch
sketch book
slave narrative
social science
song
sonnet
speech
testimony
textbook
theatre of cruelty
theatre of the absurd
theology
thesaurus
thriller
topographical poetry
tract pamphlet
translation
travel writing
utopia
verse novel
vignette
villanelle
young adult writing

**Comment by alliyya** [comment]
Being updated within
https://docs.google.com/spreadsheets/d/1jGLndleZu_tE07CkZrXNf93vnU7B8jYy7QzFswWvWFM/edit#gid=0

**Comment by alliyya** [comment]
#129
