### ISSUE TITLE
Second and third links here at head of HTML view of ontology are dead.

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#180]
![image](https://user-images.githubusercontent.com/545952/30834052-88d0dd00-a21f-11e7-89db-39df3d96aaa4.png)

**Comment by alliyya** [comment]
Those never resolve, because those graphs currently don't exist. I have added the genre taxonomy to the english template of cwrc.html. And this should be reflected in the next deploy. Also currently commented out the Gender,sex and orientation link as it is unused.
