### ISSUE TITLE
Bring sexual orientation predicates together

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#183]
These two predicates should be parallel. Unless anyone remembers anything different, I think the second predicate should be “has sexual orientation self-reported”. I don't see anything about it in the decisions in github. @jadepncr and @lemaka Do you recall a decision one way or the other?

![image](https://user-images.githubusercontent.com/545952/30834272-63baea14-a220-11e7-8b17-4eec8f6c226a.png)

**Comment by rwarren2** [comment]
@SusanBrown What do you "mean should be parallel"?

**Comment by SusanBrown** [comment]
@rwarren2 one is "has sexual orientation" and the other is "has sexuality self-reported": the wording should be parallel

**Comment by rwarren2** [comment]
Done.
