### ISSUE TITLE
why do we have "legal person" in our definition of persona

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#185]
FIBO definition for "legal person" doesn't seem to mesh w what we're doing -- can we find another link to FIBO?

**Comment by rwarren2** [comment]
Should be 'Person' from http://www.omg.org/spec/EDMC-FIBO/FND/AgentsAndPeople/People.rdf
"A person; any member of the species homo sapiens."

**Comment by joelacummings** [comment]
Will we create CWRCPerson which has a type of FIBO Person but utilizes the FOAF givenName, familyName and CWRC Genders as opposed to using the FIBO variants. Furthermore I will look into migrating maidenName and other terminology used to describe a person Orlando so CWRC person is more description and better matches what currently exists in Orlando. 

Decision on Personal was to derive it from the base definition of FOAF Person making it completely distinct from a CWRCPerson; although a CWRCPerson may have one more personas. I will define these terms within the ontology.

**Comment by rwarren2** [comment]
Note: Individuals listed within the metadata block of the ontology as authors should be explicitly typed as foaf:Person as well as CWRCPerson even through this is already true by reasoning since most metadata scrapers are naive.

**Comment by joelacummings** [comment]
I wasn't going to change those there doesn't seem to be a need to have them as CWRC person unless people want to define a huge number of properties about themselves...

**Comment by SusanBrown** [comment]
Not sure what this last comment by you means, Joel: we will have lots of properties for some authors and none for others. Should we only define those for which we have properties as CWRCpersons?

**Comment by joelacummings** [comment]
After talking with Deb we may want to define them all as CWRC Person. We will then assign additional properties to CWRC Person so we can control which properties we want to add. This should help avoid any confusion with authors who are familiar with FOAF Person and won't recognize our additions. I can now foresee adding additional attributes to the authors in our ontology so making them CWRC Persons and creating attributes as we need them seems best.

**Comment by joelacummings** [comment]
Just to clarify I think CWRC Person should still extend FOAF person since we are using a significant number of its attributes and is a case of where I think we are effectively using the FOAF ontology. It's attributes and definitions are well recognized.

**Comment by rwarren2** [comment]
I agree. This allows us to keep all of the personal properties to the CWRCPerson.
