### ISSUE TITLE
Preamble re: personas

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#189]
I've reviewed and streamlined this. A few queries remain but I think it is getting here.

@jadepncr Thanks for your great work on drafting it!

I am proposing that we expand it to include an overview of how we deal with persons and roles, even if we want to have subsections.

https://docs.google.com/document/d/1yT2lNf-ibpZEiRYfaim63j5EcRANc-BJiG771bd9Gu8/edit

**Comment by joelacummings** [comment]
Link to the discussion: [https://docs.google.com/document/d/1gFyGbkmH2SzbWMMrF92LFyY1KzucCTrl0R_SRLaZJXM/edit](https://docs.google.com/document/d/1gFyGbkmH2SzbWMMrF92LFyY1KzucCTrl0R_SRLaZJXM/edit)

**Comment by SusanBrown** [comment]
All new components of preamble and revisions to existing sections are here:
https://docs.google.com/document/d/1R0FgxmOARd2bSIvK2BYEqr9vMmoCkYj4oppshbBikXQ/edit?ts=5a86e467#heading=h.i766rjq6au6u
