### ISSUE TITLE
create pronoun vocabulary/definitions (they, s/he, etc.)

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#192]
Look for an authoritative set of definitions, if possible.

We will have hasPronoun and hasSelfDefinedPronoun

**Comment by rwarren2** [comment]
Create PersonalPronoun class and cross link with gender instances.

**Comment by alliyya** [comment]
@SusanBrown Is this something we still want to do, + do we have data from Orlando to support it?

**Comment by SusanBrown** [comment]
No, we don't have any data within Orlando to support/require it. It was more of a hypothetical getting-carried-away type of thing. We should put this in the icebox.
