### ISSUE TITLE
Create roles class and instances

### ISSUE THREAD

**Issue by rwarren2** [cwrc/ontology#194]
Some relationships can also be roles. Will need disambiguation.

Also, is the `<JOB>` tag in Orlando a role or something else?

**Comment by susanirenebrown** [comment]
Orlando doesn’t have roles per se. It has occupations (e.g. nurse) or significant activities (e.g. gardening) provided as nouns. 

Is there any real advantage to making them into roles? I was figuring we would have predicates along with lines of hasOccupation. There are attributes for things like whether it was paid or philanthropic (as much middle- and upper-class female work before the 19thC was).

cheers,
Susan

**Comment by rwarren2** [comment]
We need a role class to hold instances like `cwrc:student`. The predicate makes sense. Any objection I put the occupations eg:`nurse` as an instance of role too?

**Comment by susanirenebrown** [comment]
Presuming we can make something both a job and a role, then fine with me.

**Comment by joelacummings** [comment]
Roles are related to events to establish the role a person played in an event.
