### ISSUE TITLE
Review taxonomy images prior to update

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#195]
Pls provide for review by @susanirenebrown @lemaka @antimony27 

We should flag in the spreadsheets any relationships that should be there prior to the update. 

highlight the row yellow if you add a new relationship to it. If there are any existing relationships are already there, then strike through the text

Deadline: Dec. 5

**Comment by alliyya** [comment]
There's a folder under our Ontology Spreadsheets for relations, where you'll find the two spreadsheets for Religion and Political Affiliation and the associated images. You may find you need to download the image and zoom to be able to read the labels.

**Comment by alliyya** [comment]
@lemaka I know you were looking at these taxonomies earlier, is it done?

**Comment by SusanBrown** [comment]
Finished religion only, and it's the simplest! Have started on political affiliations. 
Will try to get back to this tomorrow morning.
