### ISSUE TITLE
review French for geonames revision

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#196]
@jadepncr Could you please review this change and revise the French if/as necessary? thx

**Comment by jadepncr** [comment]
Sure, I am just not sure what they are; are they terms such as "place" or "address" in the cwrc.owl? If it is the case I remember that I reviewed them this summer, but I can make a second pass.

**Comment by SusanBrown** [comment]
Sorry forgot to put in the link to the change: https://github.com/cwrc/ontology/commit/58a57dd38c1e9072c9924e9794da5d95c930ffc1

You'll see what I did highlighted.

**Comment by alliyya** [comment]
Was revised in ff8293e63369b0ff2ddec913a9543069d23dee93
