### ISSUE TITLE
Review current CWRC-Writer-generated RDF

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#197]
A sample of the RDF generated by the CWRC-Writer is embedded in the header of the sample document found here:
https://github.com/cwrc/CWRC-Writer-Templates/blob/master/templates/sample_letter.xml
We need to: 
1) review it for compatibility with the ontology
2) consider how the Web Annotation data model is being used here in relation to how we use it in the ontology 
3) review with a view to updating the annotations, if need be, to the current Web Annotation data  model which has been revised since this was produced.

**Comment by joelacummings** [comment]
Working document on this [here](https://docs.google.com/document/d/1-aD7RCLjKumP4UX0N738w6ThA1J5X9Y_I0h3-BwFU-c/edit?usp=sharing
)
