### ISSUE TITLE
#societyOfFriends vs #quakers

### ISSUE THREAD

**Issue by rwarren2** [cwrc/ontology#2]
We currently have both #societyOfFriends vs #quakers uri's. Which one should be kept and what should be it's official english label?

**Comment by SusanBrown** [comment]
If we go with the more simple structure I've just advocated in relation to Unitarianism, let us call it Quakerism, with an alternative label Society of Friends.

If we go the more elaborate route Quakerism can be the movement and SofF the denomination

**Comment by alliyya** [comment]
Society of friends to be deprecated in favour of preexisting quaker religion with alt label of society of friends

**Comment by alliyya** [comment]
Deprecated in favour of instance #quakerism
