### ISSUE TITLE
Subjects of Study

### ISSUE THREAD

**Issue by antimony27** [cwrc/ontology#200]
@SusanBrown can you please check here: https://docs.google.com/spreadsheets/d/11gDB6Soh5iI8YVG0vWBhrbiByvUfSieDwXrtyIg9MBQ/edit#gid=417128483

and respond to the 9 comments.

**Comment by SusanBrown** [comment]
Needs new scrape because some terms were missed. @joelacummings do you have code for this that Alliyya could start with?

**Comment by alliyya** [comment]
Scrape was redone quite a while ago and terms have been mapped to LOC where possible (Thanks to @JasmineDW) , they still need to be tested with education extraction scripts but resolving this issue as it is stale.
