### ISSUE TITLE
Define hasGenre, Genre

### ISSUE THREAD

**Issue by alliyya** [cwrc/ontology#202]

**Comment by lemaka** [comment]
@SusanBrown , how's:

**cwrc:literaryGenre**

Literary genre is a slippery system of classification used to catalogue and define the ever-evolving spectrum of literary forms and practices. Some genres are determined by their a) formal features (e.g. the English sonnet is a poem made up of fourteen lines in iambic pentameter) or b) contentual traits, such as themes of romance, horror, comedy, tragedy, and so on. In addition to form and content, the OED adds: genre is “characterized by a particular form, style, or purpose” (emphasis, mine). Within the context of literary studies, the question of “purpose,” especially when considered within a socio-political context, is of keen interest to scholars. For example, feminist literary scholars like Cynthia Huff (“‘That Profoundly Female, and Feminist Genre’: The Diary as Feminist Practice”, Giancarlo Lombardi (Rooms with a View: Feminist Diary Fiction, 1952-1999), Rita Felski (Beyond Feminist Aesthetics: Feminist Literature and Social Change) and others read diary fiction as a powerful genre used to spurr on the women’s movement.

**Getty term** 
<genres for literary, oral, and motion picture works>  url
ID: 300055907

**hasGenre**

The entity in question has a literary genre. See “literary genre” for more information.

**Comment by lemaka** [comment]
I didn't mention Bakhtin or the structuralist origins of genre-criticism -- should I?

**Comment by SusanBrown** [comment]
[in progress still]

cwrc:literaryGenre

Literary genres are used to classify texts within an ever-evolving spectrum of literary forms and practices. There is debate about whether genre inheres in texts themselves or emerges from contexts of reception, but the shifts in historical definitions indicate that genre has a strong social component.

Genres are most frequently related to formal features such as the English sonnet's fourteen lines of iambic pentameter, to characteristic subject matter such as themes of romance, horror, comedy, or tragedy, to aspects of style such as hard-boiled detective fiction, or to the rhetorical purposes of the text. In addition to form and content, the OED adds: genre is “characterized by a particular form, style, or purpose” (emphasis mine). Within the context of literary studies, the question of “purpose,” especially when considered within a political context, is of keen interest to literary scholars. For example, feminist literary scholars like Cynthia Huff (“‘That Profoundly Female, and Feminist Genre’: The Diary as Feminist Practice”, Giancarlo Lombardi (Rooms with a View: Feminist Diary Fiction, 1952-1999), Rita Felski (Beyond Feminist Aesthetics: Feminist Literature and Social Change) and others read "diary fiction" as a powerful genre used to spurr on women’s movements.

Getty term
<genres for literary, oral, and motion picture works>
url: http://www.getty.edu/vow/AATFullDisplay?find=genre&logic=AND&note=&english=N&prev_page=1&subjectid=300055907
ID: 300055907

hasGenre

The entity in question has a genre. See “literary genre” for more information.

**Comment by SusanBrown** [comment]
@antimony27 pls review
@lemaka pls also review; create new bibliography entries (Dubrow is Heather Dubrow, Genre, 1982)

**Comment by SusanBrown** [comment]
@alliyya These definitions can now be added.

**Comment by alliyya** [comment]
@SusanBrown                   
Is the use of Getty for *same as* or *wasDerivedFrom* or *closeMatch* relation, there's also http://dbpedia.org/resource/Literary_genre literary we can relate to.

**Comment by SusanBrown** [comment]
Let's use skos:closeMatch for the Getty and add the dbpedia one and use closeMatch for it as well.
