### ISSUE TITLE
Orlando people authority list reconcilation

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#203]
Add LOD identifiers to the Orlando authority list files. 
Aim for precision over recall.

This is going to be an iterative process involving experimenting to see what tool works best in terms of accuracy of matches and ease of review and refinement of the identifiers. 

Tool candidates: Karma, Google Refine -- perhaps take a brief scan for others on the LD4P (Linked Data for Production, a collaborative library project) for other possibilities.

Priorities for matching authorities: Wikidata, VIAF, Getty ULAN, DBpedia.  How we prioritize them will have a lot to do with the precision of the matching involved for different sources. Another consideration is that although VIAF is more authoritative than wikidata, Wikidata is the most linked into other authorities.

No doubt many questions will arise as we go forward. Don't hold back.

NB: if the source that we're reconciling with has birth and death date, we would like to grab that information for cases where we don't have it in our own data, and we'd want to retain the information of what the source is.

**Comment by alliyya** [comment]
Susan: Post to Linked Data listeserve to ask about Open Refine, Karma (data integration tool), or other alternatives

Gurjap to explore possibilities including looking at LD4P: research available tools similar to Open Refine; see if something exists that is more appropriate to our needs

**Comment by alliyya** [comment]
Reconciliation efforts captured elsewhere:
- https://gitlab.com/calincs/conversion/metadata-conversion/-/tree/master/CWRC/Orlando_reconciliation
- https://drive.google.com/drive/folders/1_hOCk9ebrcdH4UAGSrJ-is6bIA7_2irX
