### ISSUE TITLE
Review person definition

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#205]
@joelacummings Is this what I was supposed to review prior to updating?

` <owl:Class rdf:ID="NaturalPerson">
    <rdfs:label xml:lang="en">natural person</rdfs:label>
    <skos:definition xml:lang="en">A person that is alive, or was alive at some point in time.</skos:definition>
    <rdfs:subClassOf rdf:resource="http://xmlns.com/foaf/0.1/Person"/>
    <rdfs:isDefinedBy rdf:resource="http://sparql.cwrc.ca/ontologies/cwrc-ONTOLOGY_DATE"/>
  </owl:Class>
`

I don't see anything else that I should be reviewing. Is there not yet a more general definition of Person that would include fictional persons?

**Comment by joelacummings** [comment]
Yes this is what we need a definition for. The more general definition is FOAF:Person which this is a subclass of which would include fictional persons. This is only for actual people that exist or did exist at some point in time.

**Comment by SusanBrown** [comment]
I think we will need a separate definition for fictional people too, even though they too would be a subclass of foaf:person, to be able to separate them out. Wdyt?

**Comment by joelacummings** [comment]
Could create cwrc:FictionalPerson to satisfy that need.

**Comment by SusanBrown** [comment]
` <owl:Class rdf:ID="NaturalPerson">
    <rdfs:label xml:lang="en">natural person</rdfs:label>
    <skos:definition xml:lang="en">A human being who is alive, or was alive at some point in time. Natural persons may be fictionalized, in which case they are also classed as a FictionalPerson.</skos:definition>
    <rdfs:subClassOf rdf:resource="http://xmlns.com/foaf/0.1/Person"/>
    <rdfs:isDefinedBy rdf:resource="http://sparql.cwrc.ca/ontologies/cwrc-ONTOLOGY_DATE"/>
  </owl:Class>
  
  <owl:Class rdf:ID="FictionalPerson">
    <rdfs:label xml:lang="en">fictional person</rdfs:label>
    <skos:definition xml:lang="en">A person, broadly defined, who features in an imaginative work such as a literary work, as a character or in some other way that distinguishes the reference to them from the natural person who is being represented. In other words, there is a distinction between a simple allusion to a @@#NaturalPerson@@, and the fictionalization of that person within a text or other work of art.</skos:definition>
    <rdfs:subClassOf rdf:resource="http://xmlns.com/foaf/0.1/Person"/>
    <rdfs:isDefinedBy rdf:resource="http://sparql.cwrc.ca/ontologies/cwrc-ONTOLOGY_DATE"/>
  </owl:Class>`
