### ISSUE TITLE
Review Education in Biography spreadsheet (rows 3 - 10)

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#208]
Hi Joel! 

Could you please review what we've got under the Education tab in the Biography Spreadsheet and let us know if we've got the relations, terms, and definitions right? 

Anything in red requires special attention.

Do you prefer to be hailed in the spreadsheet via comments? Or mentioned by name and then flagged in a Github issue?

Please review everything in blue (row 3 - 10).

https://docs.google.com/spreadsheets/d/1L9V__vfiZ2hEZOsbVkMZ7-JlsToHHOuOKzbPIi-HTPs/edit#gid=1623510226

**Comment by joelacummings** [comment]
Issues work for me (or both if you want something specific in the document). I had a look through the doc and added comments on cells where I had questions or I responded.
