### ISSUE TITLE
FRBR - Bibliography references.

### ISSUE THREAD

**Issue by rwarren2** [cwrc/ontology#21]
First Edition should be the "work", earliest date will also be considered the "work". 
If there is no specific reference, do not create an expression.

**Comment by rwarren2** [comment]
Book - http://purl.org/ontology/bibo/Book
BookSection - http://purl.org/ontology/bibo/BookSection 
Conference Paper - http://purl.org/ontology/bibo/AcademicArticle isPartOf http://purl.org/ontology/bibo/Proceedings
Journal Paper - http://purl.org/ontology/bibo/AcademicArticle isPartOf http://purl.org/ontology/bibo/Journal
Website - http://purl.org/ontology/bibo/Webpage

**Comment by alliyya** [comment]
http://beta.cwrc.ca/islandora/object/cwrc%3Aontologysources
