### ISSUE TITLE
Currently Missing Definitions

### ISSUE THREAD

**Issue by alliyya** [cwrc/ontology#212]
Missing Both definitions
========================

**Interleaving drafts of definitions below:**

#Context
The Context class provides the discursive context for assertions in the ontology. Where the assertions have been generated from a source text, Context provides the text, or the relevant snippet of a longer text, from which they have been extracted.

#ReligionContext
Religion Context is a significant subclass of context. It is associated with the Cultural Form subclass Religion, and sometimes other intersecting Cultural Forms. Annotations typed as Religion Context provide information about and discussions of a person's subjectivity with regards to their religion. Religion Context provides depth to more granular categorizations of a person indicated by the properties hasReligion or hasReligionSelf-Reported.

#PoliticalContext
Political Context is a significant subclass of context. It is associated with the Cultural Form subclass Ethnicity, and sometimes other intersecting Cultural Forms. Annotations typed as Political Context provide information about and discussions of a person's subjectivity with regards to their political identity. Political Context provides depth to more granular categorizations of a person indicated by the properties hasPoliticalAffiliation.

#EthnicityContext
Ethnicity Context is a significant subclass of context. It is associated with the Cultural Form subclass Ethnicity, and sometimes other intersecting Cultural Forms. Annotations typed as Ethnicity Context provide information about and discussions of a person's subjectivity with regards to their perceived or self-reported ethnicity. Ethnicity Context provides depth to more granular categorizations of a person indicated by the properties hasEthnicity or hasEthnicitySelf-Reported.

#RaceEthnicity --> this should be depricated, right @SusanBrown ? bc it's actually RaceEthnicityContext as per https://github.com/cwrc/ontology/issues/219

#LinguisticAbility
Describes a person's proficiency in a language (speaking, reading, or writing).

#hasGender
Describes a person's gender. As with other @@#CulturalForm@@s, an individual may have more than one property or descriptor of this type. For further information about this property, see @@#Gender@@.

#hasNationality
Describes a person's nationality. As with other @@#CulturalForm@@s, an individual may have more than one property or descriptor of this type. For further information about this property, see @@#NationalIdentity@@.

#hasEthnicity
Describes a person's ethnicity. As with other @@#CulturalForm@@s, an individual may have more than one property or descriptor of this type. For further information about this property, see @@#Ethnicity@@.

#hasReligion
Describes a person's religion. As with other @@#CulturalForm@@s, an individual may have more than one property or descriptor of this type. For further information about this property, see @@#Religion@@. 

#hasSocialClass
Describes a person's social class. As with other @@#CulturalForm@@s, an individual may have more than one property or descriptor of this type. For further information about this property, see @@#SocialClass@@.

#hasSexuality
Describes a person's sexuality. As with other @@#CulturalForm@@s, an individual may have more than one property or descriptor of this type. For further information about this property, see @@#Sexuality@@.

#hasGeographicHeritage
Describes a person's heritage in relation to a place. Place names and boundaries change over time, and a conception of geographical heritage from one historical period may not be commensurate with those from an earlier or later period, even if they go by the same name. Similarly, a sense of geographical heritage may differ from a sense of identity with a political entity that goes by the same name. As with other @@#CulturalForm@@s, an individual may have more than one property or descriptor of this type. For further information about this property, see @@#GeographicHeritage@@.

#englishNationalHeritage
Indicates a subject's identification with or labelling as English as an inherited national identity.
-->we should decide if this kind of locution is good or whether the following would be better (both variants occur and we should probably edit out the less preferred one)

#welshNationalHeritage
Indicates a subject's identification with or labelling as Welsh as an inherited national identity.
skos:closeMatch: https://en.wikipedia.org/wiki/Welsh_people

#jewishNationalIdentity
Indicates a subject's identification with or labelling as Jewish or Israeli as a national identity. 
skos:closeMatch: https://en.wikipedia.org/wiki/Israelis
skos:relatedMatch: https://en.wikipedia.org/wiki/Zionism

#englishNationalIdentity -->
Indicates a subject's identification with or labelling as English as a national identity. 
skos:closeMatch: https://en.wikipedia.org/wiki/English_national_identity

#jewishGeographicHeritage
Indicates a subject's identification with or labeling as of Jewish heritage in relation to a place, which may or may not be Israel.
skos:closeMatch: https://en.wikipedia.org/wiki/Jewish_identity

#upper-middleClass --> can we use: https://en.wikipedia.org/wiki/Upper_middle_class ?
-->SB: yes, but add note: Overlaps with the @@#professional@@ class. 
--SB: also add complementary note to definition of professional class.
-->does it make sense in this case to use skos:closeMatch with our own term?

#americanNationalism
American nationalism emphasizes the distinctiveness of American language, culture, and history, and calls for a celebration of "Americanness," which might include white nationalist pride and anti-immigration.

#pro-American
A pro-American or "Americanophile" stance favours the policies, actions, or culture of the United States of America.

#whiteLabel
label: White identity
A subclass of @@#TextLabel@@, this discursive label reflects the ambiguity of whiteness associated with different @@#CulturalForm@@s. It provides a means of aggregating and searching multiple instances of "White" (e.g. whiteNationality, whiteRace) cultural identities.

#blackLabel
label: Black identity
A subclass of @@#TextLabel@@, this discursive label reflects the ambiguity of blackness associated with different @@#CulturalForm@@s. It provides a means of aggregating and searching multiple instances of "Black" (e.g. blackNationality, blackRace) cultural identities.

#eurasianLabel
label: Eurasian identity
A subclass of @@#TextLabel@@, this discursive label reflects the ambiguity of the term eurasian as associated with different @@#CulturalForm@@s. It provides a means of aggregating and searching multiple instances of "Eurasian" (e.g. eurasianGeographicHeritage, eurasianRace) cultural identities.

#englishLabel
label: English identity
A subclass of @@#TextLabel@@, this discursive label reflects the ambiguity of Englishness associated with different @@#CulturalForm@@s. It provides a means of aggregating and searching multiple instances of "English" (e.g. englishNationality, englishGeographicHeritage) cultural identities.
--make sure that EnglishLabel includes loc:eng and geonames:england as well as the routine culturalForms

#manLabel
label: Man
A subclass of @@#TextLabel@@, this discursive label reflects the ambiguity of manhood, masculinity, or maleness as associated with different @@#CulturalForm@@s. It provides a means of aggregating and searching multiple instances of "man" (e.g. man, cisMan) cultural identities.

#womanLabel
label: Woman
A subclass of @@#TextLabel@@, this discursive label reflects the ambiguity of womanhood, femininity, or femaleness associated with different @@#CulturalForm@@s. It provides a means of aggregating and searching multiple instances of "woman" (e.g. woman, transWoman) cultural identities.
-->should add the skos relationships to these two in relationship to each other @alliyya ?

#jewishLabel
A subclass of @@#TextLabel@@, this discursive label reflects the ambiguity of Jewishness associated with different @@culturalform@@ s. It provides a means of aggregating and searching multiple instances of "Jewish" (e.g. jewishNationality, jewishRace) cultural identities.

Missing Just French Definitions
===============================
#Religion
Une sous-classe de Forme Culturelle, les propriétés de religion associent les sujets à une religion ou un système de croyance particulier. Les types d’affiliation et les pratiques changent au cours du temps car elles varient considérablement en fonction de la religion, de la personne et des différents contextes. Cette propriété peut inclure ou non indiquer l’adhésion formelle à une organisation religieuse associée. 

#PoliticalAffiliation
Une sous-classe de Forme Culturelle, Affiliation Politique indique l’engagement politiques d’une personne ainsi que les connexions, les associations et les opinions qui y sont liées. Les affiliations renvoient à la fois aux connexions formelles avec un parti ou une organisation —telle que l’adhésion au parti— et aux autres partis pris politiques informels du sujet. Les affiliations politiques peuvent être multiple, parfois contradictoires ou en tension, et peuvent changer au cours du temps.

#TextLabels

#hasRaceColour

#hasLinguisticAbility

#hasNativeLinguisticAbility

#eurasianRace

#methodism

#occultism

#lowerMiddleClass
Cette classe inclut “les employés/es, les travailleurs/euses du clergé, les instituteurs/trices et les gouvernantes. Notez toutefois que certains instituteurs/trices étaient considérés comme Professionnel (Mr. Chips)”, de même que les femmes qui ouvrent et dirigent des écoles.

**Comment by lemaka** [comment]
I'll review these by tomorrow and send off whatever needs translation to Jade.

**Comment by lemaka** [comment]
also see issue https://github.com/cwrc/ontology/issues/144

**Comment by SusanBrown** [comment]
Add as appropriate: 

As with other @@#culturalForm@@s, an individual may have more than one property or descriptor of this type.

**Comment by SusanBrown** [comment]
@antimony27 @lemaka

**Comment by antimony27** [comment]
Looks good to me!

**Comment by antimony27** [comment]
hmmm. What about: 

A subclass of @@#TextLabel@@, this discursive label reflects the ambiguity of whiteness associated with different @@culturalform@@ s. It provides a means of aggregating and searching multiple instances of "white" (ie., whiteNationality, whiteRace).

**Comment by SusanBrown** [comment]
Slight elaboration:

**Comment by lemaka** [comment]
potentially daft question: @SusanBrown can I treat #englandLabel like #jewishLabel?

**Comment by lemaka** [comment]
@SusanBrown , I'm stumping on 

#englishNationalHeritage

#welshNationalHeritage

#jewishNationalIdentity

and 

#pro-American

Unless you've got definitions at the tip of your fingers, I think I have to go away and do a bit of research to do these justice.

**Comment by SusanBrown** [comment]
Will have a go.

On Feb 15, 2018, at 8:53 PM, lemaka <notifications@github.com<mailto:notifications@github.com>> wrote:


@SusanBrown<https://github.com/susanbrown> , I'm stumping on

#englishNationalHeritage

#welshNationalHeritage

#jewishNationalIdentity

and

#pro-American

Unless you've got definitions at the tip of your fingers, I think I have to go away and do a bit of research to do these justice.

**Comment by SusanBrown** [comment]
I am not sure about #englandLabel at all. Should it not be #englishLabel?

On Feb 15, 2018, at 8:31 PM, lemaka <notifications@github.com<mailto:notifications@github.com>> wrote:


potentially daft question: @SusanBrown<https://github.com/susanbrown> can I treat #englandLabel like #jewishLabel?

**Comment by SusanBrown** [comment]
Largely done. Race/ethnicity query outstanding.

**Comment by alliyya** [comment]
#224  #queerLabel needs a definition as well

**Comment by alliyya** [comment]
#222 #englishGeographicHeritage Needs a definition

**Comment by alliyya** [comment]
All in the ontology now!
