### ISSUE TITLE
cwrcEvent definition

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#213]
_Orlando documentation had virtually nothing to offer by way of definition, so I offer up the following._

cwrcEvents are narratological containers used to structure moments in space and time in a way that makes them referable. cwrcEvents have two temporal boundaries: a start and end date.

What do you think, @SusanBrown ? And should I refer readers to our still-in-the-works event ontology?

**Comment by lemaka** [comment]
I'm also wondering if we need to list all the possible events one can have in the cwrc ontology.

**Comment by SusanBrown** [comment]
I think this needs to await a more systematic working through of the various components of events. Am removing this from the milestone.

**Comment by lemaka** [comment]
okay, will hold off for now

**Comment by SusanBrown** [comment]
My sense is that we should be drawing as much as possible on existing event ontologies rather than just making up our own definitions, for the sake of compatibility, even if we do not want to adopt another event ontology wholesale.

**Comment by alliyya** [comment]
Currently using the sem for events and will be using http://semanticweb.cs.vu.nl/2009/11/sem/semdoc.html#sem:Event
