### ISSUE TITLE
'Contexts' need review in the CWRC onto

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#219]
There seems to be some confusion surrounding what terms require Contexts and what doesn't, particularly with regards to RaceAndEthnicityContext.

So what's a context in Orlando and what's a context in our cwrc onto -- are they supposed to be the same? 

http://orlando.cambridge.org/protected/svDocumentation?formname=t&d_id=CULTURALFORMATION#CULTURALFORMATION

UPDATE (April 25, 2018)

**Cultural Forms Contexts should include:** 
Class Context, Nationality Context, Race and Ethnicity Context, Religion Context, and Sexuality Context. 

We also added Gender Context (added on top of what's in Orlando).

All big bucket tags in Life (http://orlando.cambridge.org/protected/svTagSearch?formname=q&subform=1#LifeDiagram) have Contexts and in Writing (tentatively) it's Production Context, Reception Context, and Textual Features Context.

**Comment by lemaka** [comment]
@alliyya , could you please get rid of EthnicityContext and LanguageContext? they were errors to begin with (sorry!)

**Comment by lemaka** [comment]
@SusanBrown , we need to add a section in the preamble making clear the difference btw general "Contexts" and first-level big bucket tag contexts (to draw on Orlando lingo).

**Comment by SusanBrown** [comment]
Sure. This will take some time and concentration so probably not for the pending release.

**Comment by SusanBrown** [comment]
I suggest just elaborating on what I wrote for the last update slightly, to read as follows:

> a. Contexts
> The Context class provides the discursive context for assertions in the ontology. Where the assertions have been generated from a web-accessible source text, Context provides the text, or the relevant snippet of a longer text, from which they have been extracted. Contexts help to ground the data in its source materials, which can provide users with a sense of the nuance and complexity of assertions related to human subjects and cultural phenomena.
> 
> Contexts are typed by major semantic categories including, for biographical material, CulturalFormation, Birth, Death, Education, Occupation, and Politics, and, for literary content, Production, Reception, and Textual Features; these Context classes often contain subclasses such as race or ethnicity context. [link to RaceEthnicityContext] 
> 
> DC subject links connect these contexts to associated concepts in the ontology, and are also linked where possible using the provenance ontology to the full text from which they were extracted. The triples are linked to their associated contexts using The Web Annotation Data Model.

Does this seem adequate? If not I would appreciate specific suggestions about what more needs to be addressed.

**Comment by SusanBrown** [comment]
Thanks for reviewing it, @lemaka. 

I didn't capitalize race and ethnicity because we decided that we could not capitalize those terms, or indeed other such labels that aren't proper names, because it seems to reify them and make them look like Universal Abstracts.  But I think you are right that we need to single them out in some way, so I first tried revising and inserting quotes around them all, but came the conclusion that italicizing would be better. 

Wdyt? and since this affects the formatting of the ontology as a whole in html, in that we would adopt the same strategy for when we are referring to but not hyperlinking to a term in the ontology, I would love the opinion of @antimony27 @DeborahStacey @joelacummings @JasmineDW @alliyya and @GurjapSingh also, if you have a view.

**Comment by lemaka** [comment]
decision: **_bold and italicise_**

**Comment by lemaka** [comment]
bold and italicise and underline links

unless there is no link, then simply italicise all cwrc ontology terms

**Comment by SusanBrown** [comment]
To italicize in the prose:
`<![CDATA[<i>How the Irish Became White</i>]]>`

**Comment by SusanBrown** [comment]
I think this is done. Creating new issue for the decision.
