### ISSUE TITLE
Hyperlinked parenthetical citations aren't linking to anywhere.

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#220]
On http://sparql.cwrc.ca/testing/cwrc.html#cwrc:842ffbb4-11de-4212-8e6e-9d4d8d28d3a5

You are probably aware of this @alliyya , but just in case not.

**Comment by alliyya** [comment]
Definitely won't be fixed by milestone but I will make it my next priority for next week.

**Comment by alliyya** [comment]
Missing entries in cwrc bibliography:
(Encyclopedia Britannica, 1911)
(DBpedia, 2017)
(DBpedia, 2018)

**Comment by alliyya** [comment]
Missing entries in genre bibliography:
(L. K Wheeler, 2017)
(DBpedia, 2017)

**Comment by alliyya** [comment]
@GurjapSingh Could you check if these are in the bibliographies and add them if they aren't and add a link to them, thanks!

**Comment by GurjapSingh** [comment]
CWRC Bibliography
- Encyclopedia Britannica, 1911 (https://beta.cwrc.ca/islandora/object/cwrc%3A7c123714-5956-4ce5-bf15-39f3f7c5deed)
- DBpedia, 2017 (https://beta.cwrc.ca/islandora/object/cwrc%3A727d97bc-af78-4122-94be-aa78b2e97d5a)
- DBpedia, 2018 (https://beta.cwrc.ca/islandora/object/cwrc%3Ac5e7bace-95bb-4820-bd7d-6bb97c1badc5)

Genre Bibliography
- L. K. Wheeler, 2017 (https://beta.cwrc.ca/islandora/object/cwrc%3A509015ff-7641-473e-94c5-688e06952bb7)
- DBpedia, 2017 (https://beta.cwrc.ca/islandora/object/cwrc%3A727d97bc-af78-4122-94be-aa78b2e97d5a)
