### ISSUE TITLE
Deprecate england (as GeographicalHeritage) and englandLabel

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#222]
These are covered by english/englishLabel

To be deprecated: 

Instance: cwrc:england
URI: http://sparql.cwrc.ca/testing/cwrc#england

England

RDF Type:
owl:Thing
skos:Concept
cwrc:GeographicalHeritage
[back to top]
Instance: cwrc:englandLabel
URI: http://sparql.cwrc.ca/testing/cwrc#englandLabel

England

RDF Type:
skos:Concept
cwrc:TextLabels

**Comment by alliyya** [comment]
Deprecating england in favour of EnglishGeographicalHeritage(new) and deprecating england label infavour of #englishLabel

**Comment by lemaka** [comment]
@alliyya 

#englishGeographicHeritage
Indicates a subject's identification with or labeling as of English heritage in relation to a place, often England.
