### ISSUE TITLE
Add to preamble the sketch explaining how cultural forms and labels work?

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#223]

**Comment by lemaka** [comment]
Can you provide some more detail on this issue, @SusanBrown ?

**Comment by SusanBrown** [comment]
I think we need a diagram --either one of the ones prepared for the CF paper or the sex/gender one or perhaps a new and simplified one, explaining how the labels work.

**Comment by lemaka** [comment]
![figure5_jewishwriters](https://user-images.githubusercontent.com/16655795/37123635-f0b360ee-2232-11e8-8aab-ed823c16e544.png)

**Comment by lemaka** [comment]
- [ ] cwrc:jewishReligion --> needs to be cwrc:judaism
- [ ] rdfs:subclassOf --> needs to be skos:narrowerThan

**Comment by alliyya** [comment]
![image](https://user-images.githubusercontent.com/10135030/37123929-13e28da0-2234-11e8-9c56-c2447aace071.png)

**Comment by SusanBrown** [comment]
Update graffle with URIs/label
ensures graffle matches code in snippet above

**Comment by SusanBrown** [comment]
I just modified this one slightly to explain alt:Label as well: @alliyya and @joelacummings pls review quickly. https://drive.google.com/open?id=1q8j9kn9E-sAon20_1eVVQw4OvFu-vjJ9  Is this worth putting in? If so, insert in preamble at the end of this section? `<h3 id="labelsandvalues">f. Labels and values</h3>`

**Comment by joelacummings** [comment]
Looks good to me, I think it would make a good addition to the preamble as well.

**Comment by SusanBrown** [comment]
I believe this is done as I see it in the preamble.
