### ISSUE TITLE
Add relationships to label tag instances

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#224]
E.g. woman, cisWoman, transWoman need to be related to womanLabel

@alliyya  I believe that the relationship in accordance with this graffle https://drive.google.com/drive/folders/0B8C90DSaQG_sazJtMmVHc0s3M0k
should be woman isOneOf womanLabel
could you pls confirm

@lemaka following confirmation could you please add the relationships, or guide Alliyya to do so, consulting me if/as needed         

For the current release if time permits

**Comment by alliyya** [comment]
I noticed we don't have #queerLabel in the ontology is this a term that needs to be added for the current release? @SusanBrown

**Comment by alliyya** [comment]
@lemaka If you could review these relations and let me know any other you think may be missing. Thanks!

**Comment by SusanBrown** [comment]
Don't think we need it for the current release.  We should review the gender diagram and make sure we deal with everything on it in one batch.

**Comment by lemaka** [comment]
@alliyya 

label: queer identity
A subclass of @@#TextLabel@@, this discursive label reflects the ambiguity of queerness associated with different @@#CulturalForm@@s. It provides a means of aggregating and searching multiple instances of "Queer" (e.g. GenderQueer) cultural identities.

**Comment by lemaka** [comment]
sorry I'm getting to your query so late, @alliyya !

womanLabel:
woman, cisWoman, transWoman

manLabel:
man, transMan, cisMan

queerLabel:
genderQueer

I'm not exactly sure _how_ they should be related, however: 

skos: closeMatch?
skos: relatedMatch?

Did you have one in mind, @SusanBrown ? 

I vote for 'related.'

**Comment by SusanBrown** [comment]
@lemaka, I referred to the most recent graffle (and fixed the directional problem we had) to confirm that the relation should be oneOf -- but the ontology doesn't seem to reflect that. However I only looked at the HTML version. @alliyya is this what you used?

**Comment by alliyya** [comment]
@SusanBrown the relation is there, within the ontology, but not reflected in the documentation. I'm working on getting the oneOf relations to render properly in docgen right now.

**Comment by SusanBrown** [comment]
Ok good to know, thanks!
