### ISSUE TITLE
Revise "Geographical" to "Geographic"

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#225]
Our terms and labels are inconsistent. Revise Geographical to Geographic throughout.

Unfortunately, this extends to the URIs themselves. I know we don't want to deprecate wantonly. Is it merited in this case to obtain consistency, or should we confine the revisions to the labels only? Question for @alliyya @joelacummings @GuelphOntologyTeam

**Comment by alliyya** [comment]
Confined revisions to labels for now. Larger change would be needed for uris.
