### ISSUE TITLE
Define hasNationalHeritage and hasPoliticalAffiliation

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#230]
Add self-reported as well.

**Comment by lemaka** [comment]
@alliyya 

#hasNationalHeritage
Describes a person's national heritage. As with other @@#CulturalForm@@s, an individual may have more than one property or descriptor of this type. For further information about this property, see @@#NationalHeritage@@.

#hasPoliticalAffiliation
Describes a person's political affiliation. As with other @@#CulturalForm@@s, an individual may have more than one property or descriptor of this type. For further information about this property, see @@#PoliticalAffiliation@@.
