### ISSUE TITLE
cwrc:dissentProtestant

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#233]
An interesting issue has arisen as I have been trying to tidy up the religion relationships. A number of dissenting religions were grouped under dissentProtestant and others under Protestant. The thing is that dissent is a historical phenomenon specific to England, so it is pertinent to most of our data, but it does end at a certain point and doesn't apply to dissenting religions like Baptist groups and Presbyterianism in North America.

**Comment by SusanBrown** [comment]
I think the best thing to do, at least for the short term, is to add a note rather than relying entirely on the Wikipedia definition.

Here's my proposed text:
Dissenting Protestantism and nonconformism are historical phenomena that become less relevant in the United Kingdom from the early twentieth century onwards, and many groups such as Baptists and Presbyterians have significant followings in other parts of the world.

**Comment by SusanBrown** [comment]
@alliyya I would add this but I'm not sure how one shifts a definition from a straight-forward quote to a quote plus a comment.

**Comment by alliyya** [comment]
@SusanBrown 
So you'd like me to add this to the current definition and not replace it entirely? Or do you want me to add a `skos:note`
So the definition would look something like this ? Unless you'd like you proposed text to precede the existing definition.
In English church history, a nonconformist was a Protestant who did not &quot;conform&quot; to the governance and usages of the established Church of England. Broad use of the term was precipitated after the Restoration of the British monarchy in 1660, when the Act of Uniformity 1662 re-established the opponents of reform within the Church of England. By the late 19th-century the term specifically included the Reformed Christians (Presbyterians, Congregationalists and other Calvinist sects), plus the Baptists and Methodists. The English Dissenters such as the Puritans who violated the Act of Uniformity 1559 — typically by practising radical, sometimes separatist, dissent — were retrospectively labelled as nonconformists.[(DBpedia, 2017)](#_dbpedia_2017) Dissenting Protestantism and nonconformism are historical phenomena that become less relevant in the United Kingdom from the early twentieth century onwards, and many groups such as Baptists and Presbyterians have significant followings in other parts of the world.

**Comment by SusanBrown** [comment]
Yes this looks great.

Sent from my phone

On Feb 19, 2018, at 11:15 AM, Alliyya Mo <notifications@github.com<mailto:notifications@github.com>> wrote:


@SusanBrown<https://github.com/susanbrown>
So you'd like me to add this to the current definition and not replace it entirely? Or do you want me to add a skos:note
So the definition would look something like this ? Unless you'd like you proposed text to precede the existing definition.
In English church history, a nonconformist was a Protestant who did not "conform" to the governance and usages of the established Church of England. Broad use of the term was precipitated after the Restoration of the British monarchy in 1660, when the Act of Uniformity 1662 re-established the opponents of reform within the Church of England. By the late 19th-century the term specifically included the Reformed Christians (Presbyterians, Congregationalists and other Calvinist sects), plus the Baptists and Methodists. The English Dissenters such as the Puritans who violated the Act of Uniformity 1559 — typically by practising radical, sometimes separatist, dissent — were retrospectively labelled as nonconformists.(DBpedia, 2017) Dissenting Protestantism and nonconformism are historical phenomena that become less relevant in the United Kingdom from the early twentieth century onwards, and many groups such as Baptists and Presbyterians have significant followings in other parts of the world.
