### ISSUE TITLE
Proposed description of Contexts for Preamble

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#235]
_Contexts_
*The Context class provides the discursive context for assertions in the ontology. Where the assertions have been generated from a web-accessible source text, Context provides the text, or the relevant snippet of a longer text, from which they have been extracted. Contexts help to ground the data in its source materials, which can provide users with a sense of the nuance and complexity of assertions related to human subjects and cultural phenomena.*

*Contexts are typed by major semantic categories including, for biographical material, CulturalFormation, Birth, Death, Education, Occupation, and Politics, and, for literary content, Production, Reception, and Textual Features.  DC subject links connect these contexts to associated concepts in the ontology, and are also linked where possible using the provenance ontology to the full text from which they were extracted. The triples are linked to their associated contexts using The Web Annotation Data Model.*

We could cross-reference CulturalFormationContext and EducationContext and leave the others for now since I don't think we have any others.

Does this seem ok?

**Comment by SusanBrown** [comment]
@alliyya Could you please add this?

Could you also please switch the order of Persons, Contexts and Cultural Form in preamble so that it is: 
a. Contexts b. Persons, Personas, and Roles, c. Cultural Form, i.e. do not make Contexts a subsection of Cultural Form but place it on its own level. Keep “granular properties” a subsection, however.

Can you point me at the latest version of the sketch showing the OA relations? I've been deliberately vague here because I want us to review it, and I'd like to do so before talking to people here this week.

**Comment by alliyya** [comment]
@SusanBrown I'm not too sure what sketch you're referring to, this may be a question for @joelacummings ?

**Comment by SusanBrown** [comment]
That's ok, I can probably find it myself. Just thought you might have it to hand. Maybe @antimony27 can help me locate it. It's the one that shows the OA motivation and the link to the author as the target of the annotation.

**Comment by SusanBrown** [comment]
@alliyya Could you please review this? You have marked it done, but I do not see this content in the current version of the preamble.

Would also like to revise the order based on what comes before. So:
a. Contexts
b. Cultural Forms
     b.i. Granular Properties
c. Persons, Personas and Roles
d. Built-in Taxonomies

**Comment by alliyya** [comment]
Sorry I had previously completed this in c1cc6ddb45525a89e71e27bb7e511c4474553175 but it must have accidentally gotten overwritten. Sorry for not catching this earlier.
