### ISSUE TITLE
preamble revisions

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#238]
insert space between data of generation and “(Version Francaise)”

clean up extra spaces inserted after links because of my bad linking trying to avoid tagging the github user with the username “s”, as in  cultural form s.

link to cwrc:label not working, e.g. in Instance: cwrc:jewishLabel, manLabel etc.

French definition and wrong label are showing up for Fictional person, and english and french definitions are numbered

c. ii. Political affiliation [blurb for right before the diagram in the preamble]
Political affiliation categories cover a broad range of political parties, more and less organized movements, and various causes. The instances here involve a strong emphasis on British political matters historically of interest to women and a recognition that movements such as feminism are contested and change with time and location. Some affiliations are linked via SKOS relations, but there are other cross-currents among different groups that cannot be captured here as well as in the contextualized data itself. As for the other components of this ontology, this vocabulary makes no claims to comprehensiveness, having been derived from the Orlando dataset, and is open to expansion as needed.

**Comment by alliyya** [comment]
Not too sure where you're seeing these
> clean up extra spaces inserted after links because of my bad linking trying to avoid tagging the github user with the username “s”, as in cultural form s.
> link to cwrc:label not working, e.g. in Instance: cwrc:jewishLabel, manLabel etc.

**Comment by SusanBrown** [comment]
![image](https://user-images.githubusercontent.com/545952/36384394-20f494c2-155d-11e8-963e-25fce5be1629.png)
