### ISSUE TITLE
political affiliations relationships to add/remove

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#240]
Political affiliations

~dress reform skos:broaderTerm feminism~

~women’s education reform skos:broaderTerm feminism~

~prochoice skos:relatedTerm feminism
antivivisection skos:relatedTerm feminism
social purity skos:relatedTerm feminism
sexual reform skos:relatedTerm feminism
temperance movement skos:relatedTerm feminism
anti-caste skos:relatedTerm feminism~ (NOT BT)

~French nationalism skos:broaderTerm nationalism
German nationalism skos:broaderTerm nationalism
British nationalism skos:broaderTerm nationalism~

~Liberal Unionist Party skos:broaderTerm liberalism~

~antisemitism skos:broaderTerm racism
proslavery skos:broaderTerm racism
jacobinism skos:broaderTerm revolutionary
jacobism skos:broaderTerm revolutionary~

~jacobitism skos:broaderTerm pro-Catholicism~

- [x] black anti-oppression movement skos:broaderTerm racialEquality

- [x] feminism skos:broaderTerm civilRights
- [x] Jewish emancipation skos:broaderTerm civilRights
- [x] Indigenous rights skos:broaderTerm civilRights
- [x] gay rights skos:broaderTerm civilRights

- [x] elder rights skos:broaderTerm humanRights

- [x] poor law reform skos:broaderTerm socialReform
- [x] housing movement skos:broaderTerm socialReform

- [x] anti-nuclear movement skos:broaderTerm environmentalism

- [x] Conservative Party (UK) skos:broaderTerm conservativism 
- [x] Tory Party (Britain) skos:broaderTerm conservatives

**Comment by alliyya** [comment]
@SusanBrown Am I assume that the existing relation in the ontology is being replaced or just added?
ex.                        
women’s education reform skos:broaderTerm feminism

    <skos:broaderTransitive rdf:resource="#civilRights"/>
    <skos:related rdf:resource="#socialReform"/>
is currently in there for women's education reform

**Comment by SusanBrown** [comment]
Sorry i couldn’t see the existing relationships when I was noting the changes because I forgot to download the owl file for when I was offline.

For this one ditch the civil rights relationship as feminism will now be a NT of civil rights, but keep the social reform one.
