### ISSUE TITLE
Citation Errors

### ISSUE THREAD

**Issue by antimony27** [cwrc/ontology#243]
There are a number of citations that don't have proper formatting. This is likely a result of pulling from Zotero/CWRC (It seems we are still pulling from both places, is that right @alliyya ?)

![image](https://user-images.githubusercontent.com/11494469/36392821-f40f0e2e-157a-11e8-97a6-8e7318840e27.png)

If this is just a matter or misplaced brackets in the text, let me know and I can help. We ideally want all references to look like this: 

![image](https://user-images.githubusercontent.com/11494469/36392844-1ad858c6-157b-11e8-888f-08f2474af346.png)

**Comment by alliyya** [comment]
@antimony27 these were just what was dumped from spreadsheets, I've gone manually fix a bunch last time. But didn't get them all :( 

It's just a simple bracket misplace, so you can manually and fix if you would like. Thanks!

**Comment by antimony27** [comment]
Actually, I take that back. The only reference in that second image that is correct is the one for Haraway.

**Comment by antimony27** [comment]
@alliyya ok - I'll take a look and ping you if I have questions!
