### ISSUE TITLE
Figure 3 link broken

### ISSUE THREAD

**Issue by antimony27** [cwrc/ontology#244]
I can't get figure 3 to load. It looks like a broken link.

![image](https://user-images.githubusercontent.com/11494469/36434320-c4331878-162c-11e8-8dc4-180a8bdc1f85.png)

**Comment by alliyya** [comment]
If someone could point me to where an image of the ChangeSet examples diagrams are, I can add it to the repo and quash this bug :)

**Comment by antimony27** [comment]
@SusanBrown and I aren't sure where they are. @joelacummings Do you?

**Comment by SusanBrown** [comment]
If you can't find them, pls make a screenshot of what was in the previous version, expanded as large as you can on your screen, and bung it in for now.

**Comment by SusanBrown** [comment]
yes.

**Comment by joelacummings** [comment]
Located that image and added it.
