### ISSUE TITLE
quotes needed around the DBPedia definitions

### ISSUE THREAD

**Issue by antimony27** [cwrc/ontology#246]
Where we pull directly from DBPedia, there needs to be quotations around the def's themselves, throughout the ontology.

![image](https://user-images.githubusercontent.com/11494469/36439487-18cd4a08-163b-11e8-8644-2cbc673f1430.png)

**Comment by antimony27** [comment]
Like this, if possible?

![image](https://user-images.githubusercontent.com/11494469/36439584-67a0de1a-163b-11e8-85d7-5b1682fd9c81.png)

**Comment by antimony27** [comment]
And I suppose this should happen for all external sources? Getty, etc? @SusanBrown

**Comment by SusanBrown** [comment]
Yes.

**Comment by HannahJS99** [comment]
@SusanBrown @alliyya 
Closing out this issue because it seems that there are quotations around the definition DBpedia is cited.
