### ISSUE TITLE
request for deprecation

### ISSUE THREAD

**Issue by antimony27** [cwrc/ontology#247]
The URI for disestablissmentarianism is spelled wrong. Can we deprecate and fix it: disestablishmentarianism

![image](https://user-images.githubusercontent.com/11494469/36439843-116696ce-163c-11e8-8e55-1c3b11c4991d.png)

**Comment by alliyya** [comment]
As references to the term oddly have the correct spelling, I don't think it warranted a full deprecation. So I've updated the uri to match

**Comment by SusanBrown** [comment]
great
