### ISSUE TITLE
dissentProtestant and dissentingChristianity need to be merged

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#249]
keep dissentProtestant as the preferred term

ideally quote and cite both dbpedia definitions

skos:broaderThan relationship should be to protestantism not anglicanism--I think I fixed this already but please check

**Comment by alliyya** [comment]
Deprecating dissentingChristianity in favor of dissentProtestant, dissentProtestant will have two available definitions? @SusanBrown

**Comment by SusanBrown** [comment]
Yes, if that is kosher. If we have to choose one I guess choose the one that matches them label and refer to the other as a “See also”?
