### ISSUE TITLE
Citations needed within ontology

### ISSUE THREAD

**Issue by antimony27** [cwrc/ontology#250]
The following are places in the ontology that I noticed needed a citation: 

- [x] 1. Comprehensive school def'n
- [x] 2. PostSecondarySchool
- [x] 3. Section 9 - citation missing on formalism

**Comment by antimony27** [comment]
@SusanBrown Did you write the section on ontology design rules? Might you know what the missing citation is there?

**Comment by SusanBrown** [comment]
Nope. I think that was written by Rob. Maybe @joelacummings or @GuelphOntologyTeam could do so?

**Comment by joelacummings** [comment]
It was written by Rob. I'm not sure what he's citing there but I might suggest the general OWL 2 primer the ontology is based on: [https://www.w3.org/TR/owl-primer/](https://www.w3.org/TR/owl-primer/)

**Comment by SusanBrown** [comment]
Sounds fine to me. @alliyya Could you please add the citation?

So it can read:

> Beyond the formalism of The OWL 2 Web Ontology Language, ....

@joelacummings and @GuelphOntologyTeam, should this be expanded or elaborated at all based on more recent decisions/developments?

For instance, I am wondering now that we are referencing TEI if we should also mention it in the following. Are we including rdf:value tags for the TEI tags we are drawing on also?

> Whenever possible, the original Orlando XML tag equivalent is contained within the rdf:value tag of any term within the ontology.

**Comment by SusanBrown** [comment]
Document the mapping from Orlando tags and TEI tags to RDF in the Extraction metadata
Remove rdf:value mappings from the ontology itself
