### ISSUE TITLE
Definitions needed

### ISSUE THREAD

**Issue by antimony27** [cwrc/ontology#251]
The following terms are still in need of definitions:

- [x] 1. Organization
- [x] 2. prepSchool
- [x] 3. awardedTo
- [x] 4. hasEducation
- [x] 5. natively known language (self-reported) 
- [x] 6. literalForm (to be deprecated)
- [x] 7. personaTo (which should be changed to personaOf please @alliyya ) 

added by Abi:
- [x] cwrc:EducationalAward
- [x] cwrc:EducationalOrganization

**Comment by lemaka** [comment]
Organization definition --  did you want more than this, @SusanBrown?

Describes schools, companies, and any other type of recognized organization.

**Comment by lemaka** [comment]
related to https://github.com/cwrc/ontology/issues/269
