### ISSUE TITLE
discuss Property: cwrc:culturalFormTo

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#254]
Susan: I have no idea what this means or what it would do.

**Comment by joelacummings** [comment]
This is already in the ontology and is simply the inverse of ```hasCulturalForm``` allowing people to search by cultural forms and working backwards.

**Comment by SusanBrown** [comment]
Yes, I figured that out. I think it should perhaps be cuturalFormOf as I think that makes more sense syntactically— not sure if we should change the URL or just the label.

**Comment by joelacummings** [comment]
Let's just change both so they match. From now we can be consistent with our relation naming.
