### ISSUE TITLE
creating a “formal genres” category

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#256]
needs discussion

Susan: consider creating a “formal genres” category for grouping together categories that indicate an aspect of format or formal characteristics, e.g. graphic novel, comic book, map, sketch book, scrap book, commonplace book, mixed media, anthology, notebook, multimedia, computer program, gift book, epistolary.

**Comment by SusanBrown** [comment]
alternatively, just grasp the nettle and deal with form
