### ISSUE TITLE
creating a “descriptive genres" category

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#257]
needs discussion

Susan: consider creating a “descriptive genre" instance for grouping pastoral, lesbian, domestic, romance, didactic, gothic, Popular"; "Oriental"; "Industrial" - basically a grouping that indicates categories that describe some aspect of the text’s content or purpose, broadly conceived

**Comment by JasmineDW** [comment]
Add "Popular"; "Oriental"; "Industrial"

**Comment by JasmineDW** [comment]
Susan proposes: "Descriptive terms that designate types of writing by content or style"

**Comment by JasmineDW** [comment]
New title: Thematic Genres
