### ISSUE TITLE
create story as related term to fiction

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#258]
Susan: create story as related term to fiction and make it BT of fabliau and legendFolktale (and reliable to legend or folktale) and parable and myth (which should perhaps be combined with legend/Folktale).

**Comment by alliyya** [comment]
closed in 47d4adf481e5dbea119f514035340e43dc6c386e

**Comment by SusanBrown** [comment]
Removing from milestone because not meeting with them about it until next month
