### ISSUE TITLE
Update void dataset description in .well-know directory to enable discovery.

### ISSUE THREAD

**Issue by rwarren2** [cwrc/ontology#26]

**Comment by rwarren2** [comment]
@SusanBrown Is this ok for the CWRC data set description:

"The Canadian Writing Research Collaboratory is an online project designed to enable unprecedented avenues for studying the words that most move people in and about Canada. This dataset contains biographical, bibliographical and annotations from the project in a linked open data format."

**Comment by susanirenebrown** [comment]
Slightly revised and hopefully not too long:
The Canadian Writing Research Collaboratory's mission is to bring together researchers working with online technologies to investigate writing and related cultural practices relevant to Canada and to the digital turn. This virtual research environment enables researchers to leverage the power of digital tools by creating and uploading critical, biographical, bibliographical, historical, and primary source materials in text, image, audio, or video formats, and to enrich metadata and XML content with annotations in a linked open data format.

Will try to get the preamble fleshed out at least minimally tonight. Just about to surface (but only partially) from grant app craziness.

**Comment by rwarren2** [comment]
Ok. It will fit.
