### ISSUE TITLE
create informational genres as a rough synonym for nonfictional 

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#260]
Susan: create informational genres as a rough synonym for nonfictional (but noting that although the conveyance of specific content is a significant purpose, the contents may not be true, are vehicles for ideology like other texts, may have highly literary qualities, etc.) for things like 

- [x] documentary
- [x] cookbook
- [x] gardening book
- [x] review
- [x] government report
- [x] travel writing
- [x] exhibition catalogue
- [x] guidebook
- [x] manual

**Comment by SusanBrown** [comment]
ditto. Or we could have a separate meeting.

**Comment by SusanBrown** [comment]
Am I looped in here to think through Genre in REED? Or would you like me to help with the creation of the ones already in CWRC?

**Comment by SusanBrown** [comment]
Just want to bounce a few things off of you given your literary expertise. 

We will certainly need at some point to have REED review the genre list and see if we need to add things.

**Comment by lemaka** [comment]
Is Kim talking through Susan's account? Spooky!

I've added a checklist in the original query, so that we can discuss the definitions in the issue, and then add them to the checklist as we go.

**Comment by SusanBrown** [comment]
Added scholarship as NT
