### ISSUE TITLE
create music for grouping song and opera, and hymn

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#261]
Susan: create music for grouping song and opera, and hymn

**Comment by SusanBrown** [comment]
Again, I don't think we need the whole group for this. Thoughts?

**Comment by antimony27** [comment]
I assume I'm pulled in here b/c of REED. I'm starting to think through the EATS ---> CWRC crosswalk this week so I'll take a look at how music is included there, and then we can discuss, if that works?

**Comment by SusanBrown** [comment]
OK. I'll wait on this one then until I hear from you.

**Comment by jadepncr** [comment]
- [ ] Écrit musical: Écrit associé avec une forme de musique.

**Comment by alliyya** [comment]
This should be handled by the revised genre ontology.
