### ISSUE TITLE
create a performance category that groups

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#263]
Susan: create a performance category that would group drama and music and cabaret and ballet and film/tv script

**Comment by SusanBrown** [comment]
So according to this suggestion "performance" would be a genre and these would be subgenres.

I think we maybe can discuss this via this issue among the three of us in lieu of using meeting time. Wdyt?

**Comment by lemaka** [comment]
Agreed. Is "artistic output" too geeky of a choice?
