### ISSUE TITLE
Jacobism

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#265]
do we need both Jacobism and Jacobinism? (probably comes down whether a distinction is supported in the instances)

Please investigate this and look at the PA spreadsheet. A quick glance suggests the term Jacobism doesn't even occur within PA in Orlando. Maybe a typo. If it exists but seems to be a synonym of Jacabonism note the variant/alternative in spreadsheet for extraction purposes.

**Comment by alliyya** [comment]
https://docs.google.com/spreadsheets/d/1_6q0WZIF7xeCdUIwQs3JXEml8Wo_4a8KTNrT_Kodwls/edit#gid=0
PA Spreadsheet, see comments

**Comment by SusanBrown** [comment]
Yes, I vaguely recall looking into this before. Jacobins and Jacobitism are different things as the wikipedia entries establish. The question is what is Jacobism? Is it a typo for Jacobinism? Or Jacobitism? A close look at the 2 instances of Jacobism in Orlando should happen to see what it means.

**Comment by lemaka** [comment]
I've been searching and I can't seem to locate "Jacobism" anywhere in Orlando -- I think it's fair to say it's a typo!

**Comment by alliyya** [comment]
Jacobism to be deprecated in favour of Jacobinism?

**Comment by SusanBrown** [comment]
yes
