### ISSUE TITLE
Clarification linguistic ability terms 

### ISSUE THREAD

**Issue by jadepncr** [cwrc/ontology#266]
As I was reviewing French translations, I noticed some inconsistencies in terms related to the "Linguistic Ability" class. 

For example:
cwrc:hasLinguisticAbility: "Knowledge of the language for writing or reading"
And just after: 
cwrc:hasLinguisticAbilitySelfReported: "Self-reported oral or written ability with a language. For further information about this property, see ."
The second one mentions "oral and written", while the first one only mentions "writing or reading", and for SelfReported the reference to the class (after "see") is also missing. 

Another example: 
cwrc:hasNativeLinguisticAbility: "Knowledge of the language, acquired during a person’s upbringing, for writing or reading." 
Shouldn't we also include oral abilities?

**Comment by lemaka** [comment]
fixed
