### ISSUE TITLE
French education terms 

### ISSUE THREAD

**Issue by jadepncr** [cwrc/ontology#268]
French education terms ready to be transferred to the CWRC ontology

~- [ ]  **cwrc:Education**~

cwrc:Éducation: Indique la relation entre un sujet et son éducation, formelle ou informelle, à n'importe quel niveau.

- [x] **cwrc:Attends:**
cwrc:Scolarisation > Indique que le sujet fréquente ou a fréquenté un établissement éducatif en particulier ou a reçu une forme d'enseignement spécifique. 

~- [ ] **cwrc:RelatesByEducationTo**~
cwrc:lienÉducatifAvec > Indique la relation entre un sujet et son éducation, formelle ou informelle, à n'importe quel niveau.

- [x] **cwrc:ReligiousSchool**
cwrc:ÉcoleNonLaïque > Établissement éducatif officiellement associé de quelque façon avec une religion, allant des écoles paroissiales aux écoles confessionnelles. 

- [ ] **cwrc:SecularSchool:** A school that is not formally associated with a religious organization and/or one that _as_ avowedly secular in its educational principles, _often by not_ always publically-funded institutions that are funded by countries with a separation between religion and the state.
(typos in this one?) 

cwrc:ÉcoleLaïque >École qui n'est pas formellement associée à quelque organisation religieuse et/ou officiellement laïque dans ses principes éducatifs, souvent (mais pas toujours) financée publiquement dans les pays où la religion est séparée de l'État.

- [x] **cwrc:SingleSexSchool**
cwrc:ÉducationNonMixte > L'éducation non mixte, également connue sous le nom d'éducation unisexe, désigne un type d'éducation qui implique la séparation des élèves en fonction de leur sexe de naissance, qui sont réparti·e·s dans des classes, des bâtiments ou des écoles séparés.
(Note: manual translation, French DBPedia does not exist) 

- [x] **cwrc:CoEducationalSchool**
cwrc:ÉducationMixte > "La mixité ou, dans son sens ancien, la coéducation1 est l'instruction et l'éducation en commun des garçons et des filles, dans des groupes mixtes." 
(DBPedia) https://fr.wikipedia.org/wiki/Mixit%C3%A9_(%C3%A9ducation) 

- [x] **cwrc:BoardingSchool**
cwrc:Internat >
https://fr.wikipedia.org/wiki/Internat_(%C3%A9tablissement_scolaire)
"Un internat est une branche d'un établissement scolaire (école, collège, lycée, école d'enseignement supérieur...) qui offre la possibilité de loger et nourrir les élèves et les étudiants. À cette fin, un internat comprend généralement un dortoir ou des chambres, un réfectoire et des salles d'études, douche ou de divertissement."

- [x] **cwrc:GrammarSchool**
cwrc:GrammarSchool >
https://fr.wikipedia.org/wiki/Grammar_school
"Une grammar school est, dans les pays anglophones, un établissement d'enseignement secondaire ou, plus rarement, d'enseignement primaire. Les origines des grammar schools remontent à l'Europe médiévale."

- [x] **cwrc:PrivateSchool**
cwrc:ÉcolePrivée 
https://fr.wikipedia.org/wiki/%C3%89cole_priv%C3%A9e
"Les écoles privées sont des écoles qui ne sont pas administrées par leur gouvernement local, étatique ou national et qui conservent donc le droit de sélectionner leurs élèves et sont financées, en tout ou en partie grâce aux frais de scolarité qu'elle demande à ses élèves, plutôt qu'entièrement par des fonds gouvernementaux. La plupart des écoles privées offrent des bourses d'étude qui permettent de rendre la fréquentation plus abordable pour des étudiants possédant un talent quelconque, généralement au niveau académique ou sportif.
Le terme école privée désigne habituellement une école primaire ou secondaire et n'est que très rarement utilisé pour désigner une université."

- [ ] **cwrc:StateSchool**
https://fr.wikipedia.org/wiki/%C3%89cole_%C3%A9l%C3%A9mentaire_en_France
cwrc:ÉcolePublique
"L'école publique est gratuite et laïque. Elle a obligation d'accueillir les enfants habitant dans la zone qui lui est attribuée par la carte scolaire, qu'ils soient de nationalité française ou pas, en situation régulière ou pas."
(not sure about this one, the problem is that all the wiki pages are very specific because they secribe the French context) 
This one may be better: 
https://fr.wikipedia.org/wiki/%C3%89cole
"La plupart des États modernes considèrent comme de leur devoir de fournir au moins une éducation de base aux enfants de leurs citoyens. Pour cette raison, beaucoup d'écoles sont possédées et leur enseignement financé par les États."

- [x] **cwrc:DameSchool**
 cwrc:DameSchool
https://fr.wikipedia.org/wiki/Dame_school
"On désigne sous le nom de Dame schools les premières écoles primaires privées dans les pays de langue anglaise. C'étaient d'ordinaire des femmes qui enseignaient à leur propre domicile.
Il y en avait de toutes sortes : certaines étaient de simples garderies tenues par des femmes analphabètes, alors que d'autres donnaient aux élèves des bases solides. Les lacunes de ce système furent mises en évidence en 1838 par une étude de la Statistical Society of London1. Cette étude affirmait que la moitié des élèves des Dame school n'apprenaient que l'alphabet, une proportion négligeable pratiquant les mathématiques et la grammaire. Les Dame schools se firent plus rares en Grande-Bretagne après que l'enseignement eut été rendu obligatoire en 1880 : les écoles où les cours ne couvraient pas le programme fixé par le gouvernement pouvaient être fermées.
Dans la première école d'Australie, qui était une Dame school créée en 1789, c'est une détenue, Isabella Rossen, qui enseignait les bases aux enfants."

- [x] **cwrc:DaySchool**
cwrc:ÉcoleExterne
https://fr.wikipedia.org/wiki/%C3%89cole
"Une école est un établissement où l'on accueille des individus appelés « écoliers » ou élèves afin que des professeurs leur dispensent un enseignement de façon collective. Le mot école vient du latin schola, signifiant « loisir consacré à l'étude », lui-même provenant du grec schole (« le loisir »note 1), lequel constituait un idéal souvent exprimé par les philosophes et une catégorie socialement valorisée opposée à la sphère des tâches productives."

- [ ] **cwrc:ComprehensiveSchool**
(no equivalent in French, would be "école" as well)

- [x] **cwrc:SecondaryModernSchool**
cwrc:ÉcoleSecondaireModerne
https://fr.wikipedia.org/wiki/Syst%C3%A8me_tripartite_%C3%A9ducatif_au_Royaume-Uni
"Les écoles secondaires modernes, ou Secondary Technical Schools (en), avaient pour objectif une professionnalisation rapide de leur élèves."

~- [ ] **cwrc:SecondaryTechnicalSchool**~
cwrc:ÉcoleSecondaireTechnique
https://fr.wikipedia.org/wiki/Syst%C3%A8me_tripartite_%C3%A9ducatif_au_Royaume-Uni
"Les écoles secondaires techniques, ou Secondary Technical Schools (en), avaient pour but de former des techniciens; peu de ces écoles furent construites en raison de l'opposition de syndicats estimant que la formation professionnelle était de leur ressort et du manque de ressources."

**Comment by alliyya** [comment]
_A school that is not formally associated with a religious organization and/or one that as avowedly secular in its educational principles, often by not always publically-funded institutions that are funded by countries with a separation between religion and the state._

A school that is not formally associated with a religious organization and/or one that is avowedly secular in its educational principles, often but not always publicly-funded institutions that are funded by countries with a separation between religion and the state.

Is this better @lemaka

**Comment by alliyya** [comment]
cwrc:Education isn't in the ontology, do you mean cwrc:EducationalOrganization? @jadepncr 
cwrc:RelatesByEducationTo and cwrc:SecondaryTechnicalSchool are both also not in the ontology/spreadsheet

**Comment by jadepncr** [comment]
Sorry @alliyya it was a mistake; I was working with a deprecated spreadsheet (it was easier for me as I had done the translation work there before, but I did not cross-checked with the current version of the ontology).

After checking, I still have these to translate--I will edit this post later in the day and tag you when it is done. 

- [ ] cwrc:EducationContext
This optional attribute attached to Education records the mode of education and allows us to distinguish the important material effects between a domestic and an institutional education. This attribute allows us to trace the historical developments in women's access to education, for example, the informal domestic education of women writers in the early periods versus women's entrance to post-secondary education in the twentieth century

- [ ]  cwrc:DomesticEducationContext
Education that takes place at home. For example, if a woman writer in the Victorian period was taught by her brother or a governess.

- [ ] cwrc:EducationalOrganization
A school is an institution designed to provide learning spaces and learning environments for the teaching of students (or "pupils") under the direction of teachers.

- [ ] cwrc:InstitutionalEducationContext
Education or learning that takes place in an institutional setting.

**Comment by alliyya** [comment]
Also missing translations for these education terms
- [ ] [cwrc:TradeSchool](http://sparql.cwrc.ca/testing/cwrc.html#TradeSchool) - Trade School
- [ ] [cwrc:PrimarySchool](http://sparql.cwrc.ca/testing/cwrc.html#PrimarySchool) - Primary School
- [ ] [cwrc:SecondarySchool](http://sparql.cwrc.ca/testing/cwrc.html#SecondarySchool) - Secondary School
- [ ] [cwrc:PostSecondarySchool](http://sparql.cwrc.ca/testing/cwrc.html#PostSecondarySchool) - Post-Secondary School
- [ ] [cwrc:PrepSchool](http://sparql.cwrc.ca/testing/cwrc.html#PrepSchool) - Prep School
- [ ] [cwrc:hasStudent](http://sparql.cwrc.ca/testing/cwrc.html#hasStudent) - has Student
- [ ] [cwrc:SelfTaughtEducationContext](http://sparql.cwrc.ca/testing/cwrc.html#SelfTaughtEducationContext) - Self taught education context
- [ ] [cwrc:EducationalAward](http://sparql.cwrc.ca/testing/cwrc.html#EducationalAward) -educational award prize
- [ ] [cwrc:educationalAwardScholarship](http://sparql.cwrc.ca/testing/cwrc.html#educationalAwardScholarship) -educational award scholarship

Thanks @jadepncr !

**Comment by jadepncr** [comment]
- [ ] [cwrc:TradeSchool](http://sparql.cwrc.ca/testing/cwrc.html#TradeSchool) - Lycée professionnel 
"En France, le lycée professionnel (LP) est un établissement d'enseignement professionnel qui offre un enseignement professionnel en relation avec les métiers des entreprises, afin d'acquérir des compétences, des connaissances et des savoir-faire dans un domaine professionnel. Son but est l'insertion socioprofessionnelle." 
(https://fr.wikipedia.org/wiki/Lyc%C3%A9e_professionnel)

- [ ] [cwrc:PrimarySchool](http://sparql.cwrc.ca/testing/cwrc.html#PrimarySchool) - École primaire 
"L’enseignement primaire, ou l’école primaire, est, dans plusieurs pays, le premier degré de l’enseignement. Il permet notamment l'apprentissage de la lecture, de l'écriture et des bases des mathématiques. Les enfants débutent leurs études primaires vers l’âge de 6 ans et les achèvent vers l’âge de 11 ans."
(http://dbpedia.org/page/Primary_education)

- [ ] [cwrc:SecondarySchool](http://sparql.cwrc.ca/testing/cwrc.html#SecondarySchool) - Collège
"En France, le collège est un établissement d'enseignement — public ou privé — qui se situe entre l'école primaire et le lycée et assure le premier niveau de l'enseignement secondaire (de la 6e à la 3e) en principe de 11 à 14 / 15 ans environ (l'âge obligatoire minimum de sortie scolaire est de 16 ans en France)."
(https://fr.wikipedia.org/wiki/Coll%C3%A8ge_(%C3%A9tablissement))

- [ ] [cwrc:PostSecondarySchool](http://sparql.cwrc.ca/testing/cwrc.html#PostSecondarySchool) - Post-Secondary School

"Le terme d'études supérieures désigne généralement l'éducation dispensée par les universités, les collèges anglo-saxons, avec en France un système plus dual de grandes écoles et d'autres institutions comme les grands établissements décernant des grades universitaires ou autres diplômes de l’enseignement supérieur. Ces études visent à acquérir un niveau "supérieur" de compétences, généralement via une inscription ou concours d'entrée, un cursus ponctués par des examens. Historiquement, il s’agissait autrefois d'abord de former les élites recrutées par les États, les armées et les religions, puis (à partir de la révolution industrielle) par les monde économique et industriel et de la culture ou de l'enseignement. Mais d'autres dimensions, socioculturelles et éthiques ou de développement durable sont apparues à la fin du XXe siècle, ajoutant une dimension de service public visant à permettre aux étudiants, de trouver leur voie ou domaine d'excellence, de se préparer aux métiers futurs tout en faisant progresser le savoir. Ces études se déroulent souvent autour de campus, dans un système public ou privé selon les cas, et souvent catégorisés en « Sciences dures », « sciences de l'ingénieur » et « sciences humaines et sociales ». Les types de diplômes évoluent avec le temps, mais tendent à s'homogénéiser aux niveaux européens et internationaux avec les licences, des masters, et des doctorats pour faciliter les systèmes d'équivalence ou de reconnaissance mutuelle de diplômes. Cette formation inclut des cours et des stages, et peut également comporter des participations à la recherche scientifique (notamment au niveau du doctorat) et intégrer de la formation continue, mais accepte souvent aussi des « auditeurs libres » qui viennent simplement accroître leur culture générale ou spécialisée."

(http://dbpedia.org/page/Higher_education) 
(Note JP: this definition could be shortened) 

- [ ] [cwrc:PrepSchool](http://sparql.cwrc.ca/testing/cwrc.html#PrepSchool) - École préparatoire

"Une école préparatoire (preparatory school, souvent abrévié prep-school) est, dans le système éducatif britannique, une école préparant les enfants âgés entre 2 et 13 ans aux concours d'entrée aux écoles privées de plus ou moins grande renommée, les public school, telles que Eton College, Harrow School, Winchester College ou encore Marlborough College. Les élèves fréquentent la plupart du temps les prep-schools en tant que demi-pensionnaires, mais il est possible dans certains établissements d'être pensionnaire. Ces écoles préparatoires sont dites indépendantes, sont mixtes ou bien réservées aux garçons ou aux filles seulement, et les frais de scolarité sont généralement élevés, pouvant aller jusqu'à quatorze mille livres sterling par an. Certaines écoles se spécialisent dans les premières années de l'enseignement, accueillant les élèves de 2 à 8 ans, et sont appelées écoles pré-préparatoires (pre-preparatory school, abrévié prep-prep school). Ce système d'éducation indépendante se distingue du système public en ce que les élèves changent d'école à des âges différents. Ainsi, un élève issu du système privé suivra en principe le parcours suivant : De 2 à 8 ans : école pré-préparatoire De 8 à 13 ans : école préparatoire De 13 à 18 ans : public school Alors qu'un élève du système financé intégralement par le gouvernement britannique suivra la scolarité suivante : De 4 à 11 ans : école primaire De 11 à 18 ans : école secondaire (Noter que les écoles secondaires publiques se divisent en deux catégories, les comprehensive schools, ouvertes à tous, et les grammar school, accessibles sur sélection par concours d'entrée.)"

(http://dbpedia.org/page/Preparatory_school_(United_Kingdom))

- [ ] [cwrc:hasStudent](http://sparql.cwrc.ca/testing/cwrc.html#hasStudent) - a Un·e Étudiant·e

Indicates that the student was educated by the entity in question,—an instructor, an educational institution, or a particular type of schooling.

Indique que l'étudiant·e a été éduqué·e par l'entité en question (instructeur·rice, établissement éducatif,ou type d'éducation particulière).  

- [ ] [cwrc:SelfTaughtEducationContext](http://sparql.cwrc.ca/testing/cwrc.html#SelfTaughtEducationContext) - Contexte Éducatif Autodidacte 

Éducation ou apprentissage acquis en autodidacte. 

- [ ] [cwrc:EducationalAward](http://sparql.cwrc.ca/testing/cwrc.html#EducationalAward) -Récompenses scolaires

Décrit les différents types de récompenses liées au parcours scolaire (bourse, prix, etc) qui peuvent être décernées à une personne. Une bourse d'entrée à Oxford étant différente d'un premier prix au concours d'orthographe, distinguer les différents types de récompenses aide à comprendre les conditions matérielles affectant l'accès du sujet à l'éducation.

- [ ] [cwrc:educationalAwardScholarship](http://sparql.cwrc.ca/testing/cwrc.html#educationalAwardScholarship) - Bourse d'étude 

Une bourse d'études est une aide financière qui permet à un·e étudiant·e de poursuivre sa formation. Les bourses sont accordées en fonction de divers critères qui reflètent généralement les valeurs et les objectifs de l'organisation donatrice ou fondatrice de la récompense. L'argent d'une bourse d'études ne peut pas être remboursé. 

@alliyya Here are the remaining terms ready to be transfered! Thank you for spotting them.
