### ISSUE TITLE
make sure these are terms in Education: Companion; Instructor; Contested Behaviour

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#269]
not in the transferred Education terms, have to be created

**Comment by SusanBrown** [comment]
Are you sure these need to be assigned to me, Abi? I suggest you put them in the spreadsheet, consult the Orlando documentation, and have a crack at them. The third may be a challenge, I admit ;)

**Comment by lemaka** [comment]
oops! didn't mean to assign you, Susan!

**Comment by lemaka** [comment]
**cwrc: hasCompanion** 

Describes a significant relationship with a person during the course of their education.

**cwrc: hasContestedBehaviour**

Describes significant behaviour in school which is perceived as negative. This property particularly tracks a systemically discriminated and/or oppressed individuals' struggles against restrictive educational institutions.

**cwrc: hasInstructor**

Describes information regarding influential instructors in a person's life.

What do you think, @SusanBrown ? The second sentence under hasContestedBehaviour is a bit dodgy. Will return...

**Comment by SusanBrown** [comment]
Approved and ready to go into the onto @alliyya. @jadepncr please go ahead and translate.

**Comment by SusanBrown** [comment]
@jadepncr These can be translated now. :)

**Comment by alliyya** [comment]
@jadepncr 
Could you provide a translation for the term
hasCompanion
label: has Companion
defn: Describes a relationship with a person, usually a peer, in the context of the subject's education.
Thanks!

**Comment by jadepncr** [comment]
- [ ] a un·e camarade

Décrit la relation du sujet avec une personne, habituellement un·e camarade, dans le contexte de son éducation.

Hi @alliyya, sorry I missed this one, it is now translated.
