### ISSUE TITLE
Linkages to medical ontology for cause of death and injury

### ISSUE THREAD

**Issue by rwarren2** [cwrc/ontology#27]
Colin,

snowmed portal with cause of injury / death. Possible linkages for data:

http://bioportal.bioontology.org/ontologies/SNOMEDCT?p=classes&conceptid=5754000

**Comment by colinraybrian** [comment]
This is great! We might need to find something else for diseases, as this ontology lacks definitions.

**Comment by GuelphOntologyTeam** [comment]
1) Use Startup Mortality List from WHO (corresponds to ICD10) 
2) Multiple causes of death - to follow the WHO directives for ranking 
3) Mappings
   a) archaic terms -> modern medical terms
   b) all Orlando CoDs -> WHO SMoL terms/codes[https://app.zenhub.com/files/72563885/4b33e5c5-4f16-49c0-b02d-cf02ec2235cc/download](https://app.zenhub.com/files/72563885/4b33e5c5-4f16-49c0-b02d-cf02ec2235cc/download)

Lists of CoD terms in Orlando
1) All CoDs [https://app.zenhub.com/files/72563885/b37d2988-5726-4425-a594-a410b53d19fb/download](https://app.zenhub.com/files/72563885/b37d2988-5726-4425-a594-a410b53d19fb/download)
2) All Single CoDs [https://app.zenhub.com/files/72563885/33acada3-f038-434b-820e-8ea57ea66f9f/download](https://app.zenhub.com/files/72563885/33acada3-f038-434b-820e-8ea57ea66f9f/download)
3) All Multiple CoDs [https://app.zenhub.com/files/72563885/ff569c9d-1533-4b7a-9b1a-9acbaf87aa6a/download](https://app.zenhub.com/files/72563885/ff569c9d-1533-4b7a-9b1a-9acbaf87aa6a/download)
4) Mapping from modern to archaic terms  (already in Orlando) [https://app.zenhub.com/files/72563885/eb661ac2-bf58-4ef9-af5e-086c37ee7c91/download](https://app.zenhub.com/files/72563885/eb661ac2-bf58-4ef9-af5e-086c37ee7c91/download)

**Comment by alliyya** [comment]
Single causes of death have been extracted, multiple causes/health factors are a bigger/later issue.
