### ISSUE TITLE
Sexuality and gender terms consistency

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#271]
Concepts: heterosexual, homosexual, lesbian, sexualityBisexuality, sexualityCelibacy, sexualityFrigidity, sexualityLibertinism, sexualityPromiscuity,

some have the sexuality prefix and others not

Question: should they not be consistent. (the labels are consistent, so we're talking about the URIs)

Also, I don't follow what this reference to foaf is doing--and can't see what in foaf it would be linking to either as property or instance:
![image.png](https://images.zenhubusercontent.com/5a60ec3a4b5806bc2bc34e2e/414a292b-a73c-4316-bdab-344d90948b84)

Question: can someone explain what this foaf reference is doing here in the bisexuality definition?

To Do:
- [ ] cwrc:sexualityBisexuality should be cwrc:bisexual

**Comment by joelacummings** [comment]
I agree we should be consistent so my question would be is the sexuality prefix necessary? At least to me the words without the prefix still relate to sexuality however I'm unsure if they would potential be overloaded in the ontology. If they would not be I'd suggest removing the prefix and using the definition to define them as being sexual in manner. The foaf:name I think might have to do with a plan Rob had but seems very inconsistently implemented. Alliyya would probably know about that then me.

**Comment by alliyya** [comment]
Should cwrc:transWoman and cwrc:cisWoman be rdfs:subClassOf  cwrc:woman or rdf:type ?

**Comment by SusanBrown** [comment]
I don’t think the prefix is necessary. There may be some ambiguity/overlap with theme/topic terms and genre terms, however, so we should discuss if we will carry over the label strategy in such cases.I don’t think the ambiguity works the way it does with CF so I’m thinking not. However, probably work talking it through.


On Mar 19, 2018, at 5:12 PM, Alliyya Mo <notifications@github.com<mailto:notifications@github.com>> wrote:


Should cwrc:transWoman and cwrc:cisWoman be rdfs:subClassOf cwrc:woman or rdf:type ?

**Comment by SusanBrown** [comment]
Also some terms and labels are adjectival forms and some are noun forms. 

Propose that we regulalarize them to adjectival forms parallel to the gender terms (e.g. hasSexuality bisexual).

**Comment by alliyya** [comment]
Susan has reversed her proposal on adjectival vs noun forms. Nouns are preferred, (e.g. hasSexuality, bisexuality)

**Comment by SusanBrown** [comment]
But we also want to have a larger discussion at the meeting tonight re the possibility of the context remaining Sexuality but the personal property being SexualOrientation.  if you have a chance to look at how the instance data looks with respect to this question, that would be great.

**Comment by SusanBrown** [comment]
That last request was a request for @lemaka

**Comment by lemaka** [comment]
@SusanBrown can we get a definitive "we're going w adjective"/"we're going w nouns" call from you? :) 

I can then add it to the "to do" list in the issue description.

Just following up on the notes we took last meeting, which seemed to lean towards adjectives -- the comments above have the date, but not the time stamp...

I'll paste what was captured in our minutes here:

_hasSexuality will have instances in adjective form (no more “isms” within the context of Sexuality): bisexual, lesbian, homosexual, gay, butch (in the future), etc._

**Comment by SusanBrown** [comment]
Take into account possibility of hasSexualOrientation

**Comment by SusanBrown** [comment]
Overall I think that unless there is compelling reasons to do otherwise, we are best to go with noun forms for entities/instances.

**Comment by lemaka** [comment]
look to genre onto for noun/adjective inconsitency

**Comment by lemaka** [comment]
pulling in @jadepncr & @JasmineDW for your two cents (if you'd like to contribute to this discussion)

**Comment by SusanBrown** [comment]
Decisions:
get rid of sexuality prefix
get rid of foaf reference (unless @joelacummings @alliyya or @DeborahStacey )
adopt policy of making entities nouns but note in preamble or FAQ (which?) that in some cases things that are technical adjectival form operate functionally as nouns, so in the case of e.g. lesbian we will use the adjectival form for the label but indicate the implied noun in the definition e.g. lesbian (identity)

**Comment by lemaka** [comment]
@alliyya can you confirm that this has been adopted?

I'll double check whether this has been captured in the preamble and hopefully, we can close this by the end of today

**Comment by alliyya** [comment]
Looking at it now [here](http://sparql.cwrc.ca/testing/cwrc.html#cwrc%3ASexuality)

- wrt _get rid of sexuality prefix_, you want to deprecate the terms and create new uris without sexuality prefixing it?
- The labels of the sexual identities all reflect a noun, 3 uris don't however (heterosexual, homosexual, lesbian) is this fine?

**Comment by SusanBrown** [comment]
Yes we decided it was fine to have adjectival forms for these.



On Jul 18, 2018, at 12:39 PM, Alliyya Mo <notifications@github.com<mailto:notifications@github.com>> wrote:


Looking at it now here<http://sparql.cwrc.ca/testing/cwrc.html#cwrc%3ASexuality>

  *   wrt get rid of sexuality prefix, you want to deprecate the terms and create new uris without sexuality prefixing it?
  *   The labels of the sexual identities all reflect a noun, 3 uris don't however (heterosexual, homosexual, lesbian) is this fine?

**Comment by alliyya** [comment]
wrt get rid of sexuality prefix, you want to deprecate the terms and create new uris without sexuality prefixing it? @SusanBrown

**Comment by SusanBrown** [comment]
yes pls remove the prefix
