### ISSUE TITLE
Further clarifying/elaborating re: labels

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#272]
Want to clarify what relationship there is between "label" entities and the CF entities that relate to them.

Sketch proposing "represents" predicate:
https://drive.google.com/open?id=1_ggQM6H-qFdbXY2Xfk-dZ11HD9RUqY8Z
@joelacummings was this from you? Do you or @alliyya or @lemaka have any recollection of a decision around it? I don't recall one but that doesn't mean anything.  

Was this superceded by use of skos:narrower, as seems to be the case with #englishLabel? http://sparql.cwrc.ca/ontologies/cwrc.html#englishLabel                                            

Also, I feel quite certain that we collectively revised Fig 5 from the DH2017 paper and that this might help clarify things too, but I can't find a recent revision. @lemaka Could you see if you can find a sketch from the past few months that updates https://drive.google.com/open?id=0BxtOoyeTw_a6LWN6NEhOMF9TRkk ? I recall confirming the direction of the arrows from the label to instances, for instance, but I find nothing in Gdrive Figures folder.

**Comment by joelacummings** [comment]
Yes related was my proposal, don't worry I had to remind myself of it as well ;-). I don't recall whether there as decision made on it. I also don't think we've made any changes or decisions on English label since then either. Maybe someone has some notes on that.

**Comment by lemaka** [comment]
updated figure 5: https://drive.google.com/open?id=1zVKQALSTJaG9PwPAC3BLq3GDZKOQtykT
(editable version here: https://drive.google.com/open?id=1KKINCvY3Xc7N6pFX1KloAkXRqRkMzPWu)
