### ISSUE TITLE
adopt Joel's time tracking?

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#277]
@joelacummings and @SusanBrown to review the ways in which Joel track's his time w spreadsheets, and consider whether it would be a useful thing for the rest of the team to adopt.

**Comment by joelacummings** [comment]
Here's the [link](https://docs.google.com/spreadsheets/d/1yySEcnAk_bp3CLPBD0Qhvn9x8dNkHDzdzfCIwJTbb-c/edit#gid=0) to the spreadsheet. I document hours (previously by week) by pay periods along with a description of what I've done and the GitHub issues started or completed.
