### ISSUE TITLE
two new relationships (cwrc:represents and cwrc:functionallyRelated)

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#279]
Decision A: new relationship → **cwrc:represents** 

- [x] We need a definition -- make clear that matter and thought are the same in our ontology, cite Barad

→ see Gender_only_v 9; Jew women writer v 3.3 under Figures in [Drive](https://drive.google.com/drive/folders/0B8C90DSaQG_sazJtMmVHc0s3M0k) for example 

Decision B: **cwrc:functionallyRelated** (as opposed to semantically related to...)

- [x] Also needs definition.

**Comment by joelacummings** [comment]
I'll take a crack at this with a diagram and definition as a starting point.

**Comment by joelacummings** [comment]
[Working document for represents](https://docs.google.com/document/d/1msXWl8g2OhiPmrKDP7RAs43q7vFozwY_5lKqsh08LBc/edit#)

**Comment by SusanBrown** [comment]
Great start on preamble; I will weigh in here as well, if that is ok.

**Comment by joelacummings** [comment]
A start on functionallyRepresents:

> Functionally represents denotes relationships to external terms that while related have a contradictory aspects to their definition but they may be used in other works when discussing terms that are defined in CWRC. Functionally related however means there is no semantic relation these relations are for researchers studying the subject as the relationship is too complex to denote semantically given the information available.

**Comment by joelacummings** [comment]
Yeah it seems a bit strong to me, I agree it should be phrased differently. Wordsmiths where are you?

**Comment by SusanBrown** [comment]
I’m on it. Will try to have a crack at it today ;)



On Apr 17, 2018, at 12:43 PM, Joel Cummings <notifications@github.com<mailto:notifications@github.com>> wrote:


Yeah it seems a bit strong to me, I agree it should be phrased differently. Wordsmiths where are you?

**Comment by SusanBrown** [comment]
Just want to confirm--I will tackle this first thing tomorrow:

2 predicates: 1) represents and 2)functionallyRelated

right?

**Comment by joelacummings** [comment]
Yes the two of them.

**Comment by SusanBrown** [comment]
Document for working on preamble and definition re Functionally represents. https://docs.google.com/document/d/1O8_9d4LzuaqeDUbX-Nbn96P5vMIbLagkbd8qxUuXWH0/edit @JasmineDW

**Comment by SusanBrown** [comment]
I've gone some distance with both of these. They are not yet done but probably worth reviewing and commenting on in relation to the paper draft to ensure we are in agreement.

**Comment by alliyya** [comment]
Are either of these terms ready to be put into the ontology @SusanBrown?

**Comment by alliyya** [comment]
@joelacummings Are we creating the both cwrc:hasfunctionalRelation and cwrc:functionalRelationOf

**Comment by joelacummings** [comment]
@alliyya  We will probably only need hasFunctionalRelation since this will be used to link to external ontologies and the inverse relation will not be used.

**Comment by alliyya** [comment]
Status update: regarding these terms?

**HasRepresentation**
- [ ] label and definition created
- [ ] term in ontology
- [ ] preamble blurb drafted
- [ ] preamble blurb ready to be put on the web
- [ ] Inside the html
**RepresentationOf**
- [ ] label and definition created
- [ ] term in ontology
- [ ] preamble blurb drafted
- [ ] preamble blurb ready to be put on the web
- [ ] Inside the html
**HasFunctionalRelation**
- [ ] label and definition created
- [ ] term in ontology
- [ ] preamble blurb drafted
- [ ] preamble blurb ready to be put on the web
- [ ] Inside the html

**Comment by lemaka** [comment]
hasFunctionalRelation
Approved 21 April 2018 - add to ontology

Predicate

Label: has functional relation 

Definition:

Relates terms within the CWRC ontology to external terms that are semantically incommensurate but that may be pragmatically related for processing purposes such as search and retrieval. 

For example, the cwrc:gender instance “woman” relates functionally to appearances:SexISO5218-2 because important datasets employ the ISO5218 value “female.” 

hasFunctionalRelation can be leveraged by search tools to broaden the results returned. 



For Preamble:

hasFunctionalRelation

The Functional Relation predicate indicates that the two terms may be treated as related for functions such as querying and retrieval, but it also denies a semantic relationship between the two terms. This predicate is designed to bring together incommensurate terms for processing purposes but also to exclude them from semantic operations. This differentiates from, for instance, the skos:semanticRelation property and the skos:closeMatch predicate which serves a similar purpose but asserts a semantic proximity.

One of the purposes for this relation is to facilitate comparisons and relationships to other ontologies and vocabularies with which users are more familiar. Use of this relationship does not assert that the two terms are not related semantically, but rather that the current semantic relationships available within OWL, SKOS, and other ontologies used by this ontology are not sufficiently nuanced to allow for a semantic relationship to be specified in a way that can be processed appropriately by other tools (such as inference engines).

**Comment by SusanBrown** [comment]
The above is the draft for funtionallyRelated.

For the draft for RepresentationOf/hasRepresentation, see:
https://docs.google.com/document/d/1msXWl8g2OhiPmrKDP7RAs43q7vFozwY_5lKqsh08LBc/edit#

Tried to make it pithy but it has turned out quite long. There is a preamble section following the actual definitions.

Would appreciate feedback from anyone who cares to weigh in.

**Comment by GurjapSingh** [comment]
@SusanBrown the references are in the bibliography now.
Links to text
- https://link.springer.com/content/pdf/10.1007%2F3-540-70894-4_3.pdf
- https://www.tandfonline.com/doi/pdf/10.1080/09518398.2013.788754
- https://plato.stanford.edu/cgi-bin/encyclopedia/archinfo.cgi?entry=peirce-semiotics

Links to the Bibliography
- http://beta.cwrc.ca/islandora/object/cwrc%3Aebbb5e23-2c34-4810-b921-1d72694af314
- http://beta.cwrc.ca/islandora/object/cwrc%3A21bad544-af11-4b8d-869f-2d26f53943c8
- http://beta.cwrc.ca/islandora/object/cwrc%3A713873c7-011a-4b34-b5dc-d6d147575119
