### ISSUE TITLE
Family and Friends terms and Intimate Relationships and definitions

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#281]
Draft: 
- [x] Orlando Sub-Element
- [x] Class
- [x] Predicate
- [ ] Inverse Predicate
- [x] Attributes
- [x] Attribute Values
- [x] Instances
- [ ] Label
- [ ] Ontology relationships
- [x] Definitions from Orlando
- [x] Definition for Ontology -- @SusanBrown ready for review
- [ ] French Label
- [ ] French Translation
- [ ] Triples in data file
- [ ] Extraction Location
- [ ] Xpath indication 

https://docs.google.com/spreadsheets/d/1L9V__vfiZ2hEZOsbVkMZ7-JlsToHHOuOKzbPIi-HTPs/edit?usp=sharing

**Comment by lemaka** [comment]
definitions and terms for 

- [ ] hasEroticRelationship
- [ ] hasNonEroticRelationship
- [ ] hasPossiblyEroticRelationship

ready for review @SusanBrown (row 47 -49)

**Comment by lemaka** [comment]
mull over following predicates:

hasChildren
hasChildlessness???

(cc'ing you @SusanBrown)

**Comment by lemaka** [comment]
ready for review @SusanBrown 

- [ ] **hasFriend or Associate**

Describes familiarity with the subject ranging from friendship to enmities and associations. It also provides a way, for example, to indicate that a woman writer had coffee with Samuel Johnson on one notable day, but that they weren't necessarily friends. See @@#hasFriendOrAssociate@@, @@#hasEroticRelationshp@@, @@#hasIntimateRelationshp@@, @@#hasPossiblyEroticRelationshp@@. 

- [ ] **hasIntimateRelationship**

Describes a relationship that involves any type of intimacy ranging from emotional to psychological to material and to sexual. This element seeks to counter the traditional assumption that women's only intimate relations happen within the context of marriage or heterosexual relations between sexual partners. It understands lifelong female friendships, defining psychological connections or erotically-charged same sex or opposite sex relationships as important to a woman's life. This element captures information concerning both brief sexual affairs and lifelong non-sexual relationships (see attribute erotic for distinguishing between the two). This element also seeks to redress the historical and ideological silence placed upon women's same-sex relationships; it recognizes that biographical information concerning these relationships often is impossible to uncover; therefore this element allows us to recognize these relations as significant while not assuming, in the absence of biographical proof, that they were sexual. See @@#hasFriendOrAssociate@@, @@#hasEroticRelationshp@@, @@#hasIntimateRelationshp@@, @@#hasPossiblyEroticRelationshp@@. 

- [ ] **hasEroticRelationship**

Describes intimate relationships that are erotic and/or explicitly sexual. Erotic in this context sometimes suggests that sexuality was an issue in the relationship, whether or not it was acted upon. In not wishing to assume that heterosexual relations between sexual partners are the only standard for intimate relationships, we include both erotic and non-erotic relations as central to a subject’s life and use @@#hasEroticIRelationship@@ to distinguish between the two. See @@#hasFriendOrAssociate@@, @@#hasEroticRelationshp@@, @@#hasIntimateRelationshp@@, @@#hasPossiblyEroticRelationshp@@. 

—> add that we are more interested in affect than physical acts?

- [ ] **hasNonEroticRelationship**

Describes and intimate relationship with the subject that is neither erotic nor sexual in nature. See @@#hasFriendOrAssociate@@, @@#hasEroticRelationshp@@, @@#hasIntimateRelationshp@@, @@#hasPossiblyEroticRelationshp@@. 


- [ ] **hasPossiblyEroticRelationship** 

Describes an intimate relationship that may or may not be erotic in nature. This predicate also seeks to redress the historical and ideological silence placed upon same sex relationships; it recognizes that biographical information concerning these relationships often is impossible to uncover. 
@@#hasPossiblyEroticRelationship@@ registers the possibility of a sexual relationship, when, in the absence of biographical proof, it is impossible to claim such as fact. See @@#hasFriendOrAssociate@@, @@#hasEroticRelationshp@@, @@#hasIntimateRelationshp@@, @@#hasPossiblyEroticRelationshp@@.

**Comment by alliyya** [comment]
@lemaka I would like to hold off on putting these terms in the ontology, since only one of the terms is done and makes references to the other terms that are not created. (Would be awkward to make reference to non-existent terms. 

Will hold off till this set of definitions is fully fleshed out.

**Comment by lemaka** [comment]
@alliyya roger that

@SusanBrown the spreadsheet, github, and the ontology are now reconciled (added new column for link to corresponding DBpedia url); will also take a crack at extraction instructions for hasChildren, hasNoChild, hasChildLoss

**Comment by lemaka** [comment]
gentle ping: @SusanBrown Extraction Locations (Column S) ready for review by yourself and then @joelacummings in Biography Spreadsheet (linked at the top) under "Family" tab

**Comment by alliyya** [comment]
Terms are ready to be added pending decision on naming of predicates with "with" suffix

**Comment by lemaka** [comment]
**Decision: use hasIntimateRelationshipWith**

**Comment by alliyya** [comment]
resolved in 155664a3f4884dddd33277ac1f4473e19389c726
