### ISSUE TITLE
Death terms and definitions

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#282]
Draft: 
- [x] Orlando Sub-Element
- [x] Class
- [x] Predicate
- [ ] Inverse Predicate
- [x] Attributes
- [x] Attribute Values
- [ ] Instances
- [ ] Label
- [x] Ontology relationships
- [ ] Definitions from Orlando
- [ ] Definition for Ontology
- [ ] French Label
- [ ] French Translation
- [ ] Examples from Orlando
- [ ] Instance in the CWRC Ontology Data file
- [x] Extraction Location
- [x] Xpath indication 

https://docs.google.com/spreadsheets/d/1L9V__vfiZ2hEZOsbVkMZ7-JlsToHHOuOKzbPIi-HTPs/edit?usp=sharing

**Comment by SusanBrown** [comment]
@joelacummings Ready for review

**Comment by alliyya** [comment]
Causes of death handled by II ontology, health factors are a later issue.
Add hasDeathPlace, hasDeathDate
