### ISSUE TITLE
Events terms and definitions

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#283]
Draft: 
- [x] Orlando Sub-Element
- [x] Class
- [ ] Predicate
- [ ] Inverse Predicate
- [x] Attributes
- [ ] Attribute Values
- [x] Instances
- [ ] Label
- [ ] Ontology relationships
- [ ] Definitions from Orlando
- [ ] Definition for Ontology
- [ ] French Label
- [ ] French Translation
- [ ] Examples from Orlando
- [ ] Instance in the UPTODATE data file
- [ ] Extraction Location
- [ ] Xpath indication 

https://docs.google.com/spreadsheets/d/1L9V__vfiZ2hEZOsbVkMZ7-JlsToHHOuOKzbPIi-HTPs/edit?usp=sharing

**Comment by lemaka** [comment]
Deb (Decision): use hasReference w sub properties like hasTemporalReference, hasPersonReference, etc. for floating dates, names, places, orgs, titles, and events not attached to a Chronstruct; attach to educationEvent and educationContext.

**Comment by alliyya** [comment]
is hasReference a term that we'll be creating or pulling from somewhere else?

**Comment by SusanBrown** [comment]
Not necessary to create hasReference.

March 28 decision superceded by the decision to use the Open Annotation data model for such references.
