### ISSUE TITLE
Occupation terms and definitions

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#288]
Draft: 
- [x] Orlando Sub-Element
- [x] Class
- [x] Predicate
- [x] Inverse Predicate
- [x] Attributes
- [x] Attribute Values
- [ ] Instances
- [x] Label
- [x] Ontology relationships
- [ ] Definitions from Orlando
- [x] Definition for Ontology
- [ ] French Label
- [ ] French Translation
- [ ] Examples from Orlando
- [ ] Instance in the UPTODATE data file
- [x] Extraction Location
- [ ] Xpath indication 

https://docs.google.com/spreadsheets/d/1L9V__vfiZ2hEZOsbVkMZ7-JlsToHHOuOKzbPIi-HTPs/edit?usp=sharing

**Comment by JasmineDW** [comment]
Link to Standard Occupational Classification (SOC) which has both terms and definitions:
https://www.bls.gov/soc/

**Comment by lemaka** [comment]
note from Biography Spreadsheet: "Susan: Don’t create Occupation as a class for now. To be decided."

is this still an outstanding issue, @SusanBrown @alliyya ?

**Comment by SusanBrown** [comment]
Yes, we are still waiting on this decision across all the sheets.

**Comment by SusanBrown** [comment]
This sheet is ready for review by you @joelacummings. There is just one significant question

**Comment by SusanBrown** [comment]
Note that current questions are in red in the body of the cell, instead of using comments. Things that need to be dealt with down the line that are not questions in need of response are also highlighted yellow but text is in black.

**Comment by alliyya** [comment]
Terms all in the ontology
