### ISSUE TITLE
Citations missing in write-up.

### ISSUE THREAD

**Issue by rwarren2** [cwrc/ontology#29]
The following citations are missing in the ontology documentation:

1. [reference Tulsa Studies  articles]
1. (Smith 273)
1. (Halpin and Hayes 2010)

**Comment by SusanBrown** [comment]
Asked @colinraybrian to add the third among some other missing ones. I have no access to Zotero or I'd have added them.

No. 2 is https://books.google.ca/books?id=l-FRDQAAQBAJ&pg=PT8&lpg=PT8&dq=james+smith+doing+dh+semantic+web&source=bl&ots=Q_0X66tZyg&sig=sUQEDvDQgVfyIKdJZLPwvvLI6uA&hl=en&sa=X&ved=0ahUKEwj26e_u_sTSAhXL7YMKHZ4EDBkQ6AEIHzAB#v=onepage&q=james%20smith%20doing%20dh%20semantic%20web&f=false

The others are:

Susan Brown, Patricia Clements and Isobel Grundy. An Introduction to the Orlando Project.” Tulsa Studies in Women’s Literature 26.1 (Spring; Silver Jubilee Issue). 127-34. 

Susan Brown, Patricia Clements and Isobel Grundy. “Archives: Personal Reflections.” Tulsa Studies in Women’s Literature 26.1 (Spring; Silver Jubilee Issue).  [ don't have the pagination]--pls look it up.

**Comment by rwarren2** [comment]
Which reference did you have in mind for "For a more detailed explication of
   cultural formation, see Brown et al 2017." ?

**Comment by SusanBrown** [comment]
Susan Brown, Abigel Lemak, Colin Faulkner (University of Guelph), and Rob Warren (Carleton University and University of Guelph). Cultural (Re-)formations:  Structuring a Linked Data Ontology for Intersectional Identities. DH2017 Abstract. Montreal, forthcoming.

Asked @colinraybrian to add along with the others.

**Comment by rwarren2** [comment]
Did it myself to crank out the document today.
