### ISSUE TITLE
Education terms and definitions

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#293]
Draft: 
- [x] Orlando Sub-Element
- [x] Class
- [x] Predicate
- [x] Inverse Predicate
- [x] Attributes
- [x] Attribute Values
- [x] Instances
- [x] Label
- [x] Ontology relationships
- [x] Definitions from Orlando
- [x] Definition for Ontology
- [ ] French Label
- [ ] French Translation
see https://github.com/cwrc/ontology/issues/268
- [x] Examples from Orlando
- [x] Instance in the UPTODATE data file
- [x] Extraction Location
- [x] Xpath indication 

https://docs.google.com/spreadsheets/d/1L9V__vfiZ2hEZOsbVkMZ7-JlsToHHOuOKzbPIi-HTPs/edit?usp=sharing

**Comment by lemaka** [comment]
check to make sure Education has:

- [ ] subject
- [ ] instructor
- [ ] contested behaviour

**Comment by lemaka** [comment]
@alliyya to test extraction on Education

**Comment by jadepncr** [comment]
- [ ] Subject > Discipline 

[I was unable to find this one in the ontology]

- [ ] hasInstructor > aUnInstructeur·ice

Décrit la relation du sujet avec un instructeur pédagogique ou un·e mentor·e, formel·le ou informel·le.

- [ ] Contested Behaviour > Comportement contesté

Décrit le comportement, perçu comme négatif, dans le contexte de l'éducation du sujet. Souvent indicateur d'une lutte contre la discrimination systémique, y compris au sein des structures de l'éducation insitutionnelle.

Remaining French education terms ready to be imported @alliyya. Thank you!

**Comment by alliyya** [comment]
Extraction Review: 
Spreadsheet is missing instructions for extracting:

- Companion
- Contested Behaviour
- Degree (Term also not in ontology)
- Instructor
- Subject
- Text

**Comment by alliyya** [comment]
All of these terms are in the ontology now, Educational text is missing a definition @SusanBrown 
http://sparql.cwrc.ca/testing/cwrc.html#EducationalText

**Comment by alliyya** [comment]
@SusanBrown Still missing definition for educational text

**Comment by SusanBrown** [comment]
educational text
A text, cultural work, or an author or artist's general _oeuvre_, that is significant to a person's informal or formal education. 

Add to the end of the definition of cwrc:studies:
Using this predicate with an author's _oeuvre_ usually indicates the study of a portion, rather than the entirety, of that author's works.
