### ISSUE TITLE
Birth terms and definitions

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#294]
Draft: 
- [x] Orlando Sub-Element
- [x] Class
- [x] Predicate
- [ ] Inverse Predicate
- [x] Attributes
- [x] Attribute Values
- [x] Instances
- [x] Label
- [x] Ontology relationships
- [x] Definitions from Orlando
- [x] Definition for Ontology
- [ ] French Label
- [ ] French Translation
- [ ] Examples from Orlando -->**now obsolete**
- [ ] Instance in the CWRC Ontology Data file
- [x] Extraction Location
- [x] Xpath indication 

https://docs.google.com/spreadsheets/d/1L9V__vfiZ2hEZOsbVkMZ7-JlsToHHOuOKzbPIi-HTPs/edit?usp=sharing

**Comment by lemaka** [comment]
from @SusanBrown : @joelacummings I'm wondering if this is a logical inverse predicate, Joel, or do we not need one?] We didn't do this for Education but I would think that we want Events to point to their contexts. @GuelphOntologyTeam  Wdyt?

**Comment by joelacummings** [comment]
The inverse predicate would be ```birthEventTo``` that way we can be more generic in how events are linked, the same predicate would link the event back to the person as well.

**Comment by SusanBrown** [comment]
Is To a common locution in ontologies. I get what the preposition is doing, but it sounds very awkward.

EventOf, which is what we have now, also sounds very awkward. Not sure what would be best.

On Apr 4, 2018, at 10:00 PM, Joel Cummings <notifications@github.com<mailto:notifications@github.com>> wrote:


The inverse predicate would be birthEventTo that way we can be more generic in how events are linked, the same predicate would link the event back to the person as well.

**Comment by joelacummings** [comment]
Yes it's fairly the common. There are two schools when creating relations/inverse relations. The first is using a prefix for predicates and a postfix for inverse predicates, has_ and _To. The second methods  to use a lowercase words ```Event``` as the class and ```event``` as the predicate which acts as both a predicate and inverse predicate.

**Comment by SusanBrown** [comment]
@joelacummings This section of the Biography spreadsheet is now ready for your review.
@jadepncr You have translated most of what is here already but there are a few new things to translate.

**Comment by jadepncr** [comment]
Remaining birth terms are now translated!

**Comment by alliyya** [comment]
Add hasBirthPlace and hasBirthPlace

**Comment by alliyya** [comment]
#462 still open
