### ISSUE TITLE
Are birth and death always events?

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#298]
Should they be events as well as contexts by default even if we don't have event information about them, or is it sufficient (as per our conversation last week) to provide the context, if we really have no event-like info, and figure someone can add an event down the line.

**Comment by GuelphOntologyTeam** [comment]
As per our last discussion, I think that we should not create events if we do not have enough temporal information.  If and when temporal information becomes available, then an event can be created.

________________________________
