### ISSUE TITLE
CIDOC-CRM mapping and documentation

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#299]
- [ ] need to map sameAs relationships wherever we can, but we won’t align completely w CIDOC-CRM
- [ ] need to document the nature of our relationship w CIDOC-CRM in the preamble

**Comment by joelacummings** [comment]
Not using CIDOC-CRM at the moment using SEM for events so on pause.

**Comment by JasmineDW** [comment]
Can this be considered Done due to Erin's work with mapping? If not, we should close this issue and replace it with a new one that better-defines next steps.

**Comment by alliyya** [comment]
Agreed, we can create a more precise issue if need be; closing issue.
