### ISSUE TITLE
Review all SocialClass and add French language definitions.

### ISSUE THREAD

**Issue by rwarren2** [cwrc/ontology#3]
Please review the instances of SocialClass and create skos:definitions in the french language.

**Comment by SusanBrown** [comment]
@abi Would you be able to take this on? presumably Rob can review what you draft for idiom. French definitions do not have to be as developed as English ones, in my view.

**Comment by lemaka** [comment]
yes! I can definitely get on this

**Comment by SusanBrown** [comment]
@jadepncr Am I right that this now done and can be closed?

**Comment by jadepncr** [comment]
Yes !
