### ISSUE TITLE
Orlando credit page and about page require a password to access.

### ISSUE THREAD

**Issue by rwarren2** [cwrc/ontology#30]
It's out of scope for our work, but it makes it hard to give credit to Orlando if they URL's for credit and about aren't publicly accessible. Who should I ask about this?

http://orlando.cambridge.org/protected/svDocumentation?&d_id=ABOUTTHEPROJECT
http://orlando.cambridge.org/protected/svDocumentation?&d_id=CREDITSANDACKNOWLEDGEMENTS

**Comment by jefferya** [comment]
Here are the public versions:

http://orlando.cambridge.org/public/svDocumentation?&d_id=ABOUTTHEPROJECT

http://orlando.cambridge.org/public/svDocumentation?formname=t&d_id=CREDITSANDACKNOWLEDGEMENTS

**Comment by SusanBrown** [comment]
Oh sorry, thanks: Orlando seemed to be down when I tried to test them so i got them wrong.

**Comment by rwarren2** [comment]
Thank you!
