### ISSUE TITLE
Edit family terms for consistency 

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#305]
Capitalization
make sure that we are always introducing the definition of the term with the noun.

questions: 

- [x] do inverse predicates need definitions or not?
- [ ] make sure references to animals are consistent; try to make parallel terms parallel in their definitions

NB: "father of" is label for stepfatherOf
![image](https://user-images.githubusercontent.com/545952/38379998-77092fee-38d0-11e8-9ef9-644e59108d0d.png)

**Comment by lemaka** [comment]
@lemaka make sure to review/edit all of the family terms

**Comment by alliyya** [comment]
Inconsistencies in use of space/hypen in labels of stepfamily.
ex. 
step father
step-father
stepfather
Not too sure which is correct. @SusanBrown @lemaka

**Comment by SusanBrown** [comment]
stepbrother (Oxford Cdn Dixtionary)

Sent from my phone

On Apr 23, 2018, at 4:53 PM, Alliyya Mo <notifications@github.com<mailto:notifications@github.com>> wrote:


Inconsistencies in use of space/hypen in labels of stepfamily.
ex.
step father
step-father
stepfather
Not too sure which is correct. @SusanBrown<https://github.com/SusanBrown> @lemaka<https://github.com/lemaka>

**Comment by jadepncr** [comment]
@SusanBrown I see this is assigned to me; are all the family terms in the google sheet ready to be translated? 
https://docs.google.com/spreadsheets/d/1L9V__vfiZ2hEZOsbVkMZ7-JlsToHHOuOKzbPIi-HTPs/edit#gid=1512757216

I ask because cells are not pink yet.

**Comment by SusanBrown** [comment]
Hi Jade!  They still need final review but @lemaka can start turning them pink as she goes, I expect.

Sent from my phone

On Jun 23, 2018, at 12:40 PM, jadepncr <notifications@github.com<mailto:notifications@github.com>> wrote:


@SusanBrown<https://github.com/SusanBrown> I see this is assigned to me; are all the family terms in the google sheet ready to be translated?
https://docs.google.com/spreadsheets/d/1L9V__vfiZ2hEZOsbVkMZ7-JlsToHHOuOKzbPIi-HTPs/edit#gid=1512757216

I ask because cells are not pink yet.

**Comment by alliyya** [comment]
Translation should be covered by in Jade's review/translation of the ontology
