### ISSUE TITLE
Translations for Genre Terms

### ISSUE THREAD

**Issue by alliyya** [cwrc/ontology#308]
Hi, Jade if you could provide a translation for the two following terms that would be great!

- [x] genre
- [ ] literary genre

Here's their current english definitions
Genre:
_Genres are used to classify cultural works within an evolving spectrum of categories often on the basis of form, content, or style. There is debate over whether genre inheres in works themselves or emerges from contexts of reception, but the shifts in historical definitions indicate that genres have a strong social component (Miller 1984)._

Literary Genre:
_Literary genres are used to classify texts within an ever-evolving spectrum of literary forms and practices. There is debate over whether genre inheres in texts themselves or emerges from contexts of reception, but the shifts in historical definitions indicate that genres, literary and more broadly, have a strong social component (Dubrow, 1982; Miller 1984). Genres are most frequently related to formal features such as the English sonnet's fourteen lines of iambic pentameter, to characteristic subject matter such as themes of romance, horror, comedy, or tragedy, to aspects of style such as hard-boiled detective fiction, or to the purpose of a text. Within the context of literary studies, the question of &quot;purpose,&quot; especially when considered within a political context, is of keen interest to literary scholars. For example, feminist literary scholars like Cynthia Huff (&quot;‘That Profoundly Female, and Feminist Genre’: The Diary as Feminist Practice&quot;, Giancarlo Lombardi (Rooms with a View: Feminist Diary Fiction, 1952-1999), Rita Felski (Beyond Feminist Aesthetics: Feminist Literature and Social Change) and others read "diary fiction" as a powerful genre used to spur on women’s movements. For more on literary genre, see the introduction to this ontology._

Thanks!

**Comment by jadepncr** [comment]
Hi Allyya! the definitions are ready:

**Genre**

Les genres sont utilisés pour classer les œuvres culturelles parmi un éventail évolutif de catégories, souvent sur des critères de forme, de contenu ou de style. On se demande si le genre est inhérent aux œuvres elles-mêmes ou émerge des contextes de réception, mais les changements dans les définitions historiques indiquent que les genres conservent une forte composante sociale (Miller 1984).

**Genre littéraire**

Les genres littéraires sont utilisés pour classer les textes parmi un éventail de formes et de pratiques littéraires en constante évolution. On se demande si le genre est inhérent aux textes eux-mêmes ou émerge des contextes de réception, mais les changements dans les définitions historiques indiquent que les genres littéraires et les genres en général ont une forte composante sociale (Dubrow, 1982, Miller 1984). Les genres reposent le plus souvent sur des éléments  formels (les quatorze vers en pentamètre iambique du sonnet anglais), sur le traitement de thèmes caractéristiques (romance, horreur, comédie ou tragédie), sur des aspects stylistiques (ton cynique typique du roman policier), ou encore sur l'objectif d'un texte. Dans le contexte des études littéraires, la question de l'"objectif" est d'un intérêt fondamental dans la recherche académique, surtout lorsqu'elle s'inscrit dans un contexte politique. Par exemple, des universitaires féministes comme Cynthia Huff ("'That Profoundly Female, and Feminist Genre’: The Diary as Feminist Practice"), Giancarlo Lombardi (Rooms with a View: Feminist Diary Fiction, 1952-1999), Rita Felski (Beyond Feminist Aesthetics: Feminist Literature and Social Change) et d'autres soulignent l'influence significative du genre du journal intime sur l'expansion des mouvements féministes. Pour en savoir plus sur le genre littéraire, voir l'introduction de cette ontologie.

**Note:** Typo in the English definition, a bracket is missing after the title of Huff's article
