### ISSUE TITLE
Scrape of Significant Activity tag

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#313]
Need a scrape of all the strings occurring in the Significant Activity (SIGNIFICANTACTIVITY) tag.

These are unpaid occupations such as gardening, painting, charitable work. 

I doubt that there is a vocabulary for this but @GuelphOntologyTeam pls keep a look out in looking for paid occupations.

**Comment by joelacummings** [comment]
I just did a scrape with the reg and values merged along with their occurrence count. If we want/need a different format let me know. 

https://docs.google.com/spreadsheets/d/189xa92cSy7EuptJncXtsTfvWg-dzstFQNo3Ykne2HFc/edit?usp=sharing

**Comment by joelacummings** [comment]
Updated per #312.
