### ISSUE TITLE
Forebear graffle

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#316]
- [x] Draft 
- [x] Approve
- [ ] Add polish

https://drive.google.com/drive/folders/0B8C90DSaQG_sazJtMmVHc0s3M0k

**Comment by SusanBrown** [comment]
This is ready for review. We discussed it at a previous meeting and I believe what I have done reflects that discussion, and the data.

**Comment by alliyya** [comment]
duplicate of #339, awaits decision on identity
