### ISSUE TITLE
replication of definitions as Comments in generated version

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#32]
Seems be throughout the CF content, but not the genre content.

e.g.: 

Class: cwrc:Ethnicity

URI: http://www.cwrc.ca/ontologies/cwrc#Ethnicity

Ethnicity - Ethnicity is a subclass of CulturalFormation that captures information about a person's ethnic position. Ethnicity is a sub-element within culturalFormation and raceAndEthnicity. See raceAndEthnicity for a detailed description of the complexities of this discursive construction and the social practices surrounding it.

Comment: Ethnicity is a subclass of CulturalFormation that captures information about a person's ethnic position. Ethnicity is a sub-element within culturalFormation and raceAndEthnicity. See raceAndEthnicity for a detailed description of the complexities of this discursive construction and the social practices surrounding it.

in-domain-of:
cwrc:hasEthnicity
cwrc:hasEthnicitySelfDefined

**Comment by rwarren2** [comment]
Broken documentation generator. Needs to be rewritten. On the todo list.

**Comment by alliyya** [comment]
Documentation generator has been updated :)
