### ISSUE TITLE
Definitions required for epitaph and regional

### ISSUE THREAD

**Issue by antimony27** [cwrc/ontology#333]
- [x] epitaph
 --> we currently have a definition for "epitaph" that defines "epitaph poetry" instead, which needs to be fixed
- [x] regional

**Comment by SusanBrown** [comment]
Epitath: Wikipedia definition is fine. I can't find the dbpedia URI for it, though, through my usual lookup end point. @alliyya can you pls recirculate the tool for getting one from the other, but just go ahead and add the wikipedia definition?
https://en.wikipedia.org/wiki/Epitaph

regional writing: just added definition directly to ontology. Oddly there was a French one present already which makes me wonder if there was an English one that got lost somewhere.

**Comment by alliyya** [comment]
http://www.snee.com/bobdc.blog/2011/03/from-a-wikipedia-page-to-the-c.html
source for the Shortcut from a wikipedia entry to a dbpedia entry
https://en.wikipedia.org/wiki/Epitaph => http://dbpedia.org/page/Epitaph
All it does is switch around the main parts of the url
