### ISSUE TITLE
other-reported --> reported

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#338]
I think it would be clearer and less clunky if we drop "other".

So: 
has gender (could be self-defined or not or unknown)
has gender (self-reported)
has gender (reported)

[cwrc:hasGender
cwrc:hasGenderSelfReported
cwrc:hasGenderReported]

I think this works. Wdyt @lemaka @antimony27 @JasmineDW ?

**Comment by alliyya** [comment]
I can start creating these *Reported Properties and modifying labels? @SusanBrown 
ex.
uri: cwrc:hasGender
label: has gender --> has gender (could be self-reported or not or unknown)
definition: Describes a person's gender. As with other @@#CulturalForm@@s, an individual may have more than one property or descriptor of this type. For further information about this property, see @@#Gender@@
> I'm not sure if you want to also modify the definitions as well
 

uri: cwrc:hasGenderReported
label: has gender (reported)
definition: This indicates a person's reported gender. For more information on this property, see @@#Gender@@.

also deprecation of personalProperties

**Comment by SusanBrown** [comment]
Don’t modify has gender to add parentheses. The definition should make the possibilities clear but we don’t want a huge label. So the definition could read Describes a person’s gender, which may be self-reported or reported by another.

**Comment by alliyya** [comment]
**uri:** cwrc:hasGender
**label:** has gender
**definition:** Describes a person's gender, which may be self-reported or reported by another. As with other @@#CulturalForm@@s, an individual may have more than one property or descriptor of this type. For further information about this property, see @@#Gender@@

**uri:** cwrc:hasGenderReported
**label:** has gender (reported)
**definition:** This indicates a person's reported gender. For more information on this property, see @@#Gender@@.

Would be fine? I'll append _, which may be self-reported or reported by another._ to the necessary properties.

**Comment by SusanBrown** [comment]
yes, great.

**Comment by alliyya** [comment]
I remember we discussed `cwrc:PoliticalAffiliation` being an odd class to have a self-reported predicate, should `hasPoliticalAffiliationSelfReported` be deprecated? Are there instances where pa's are self-defined? 

These are all the predicates that will have `has<class>Reported` property created. 

hasEthnicity
hasEthnicitySelfReported

hasGender
hasGenderSelfReported

hasGeographicHeritage
hasGeographicHeritageSelfReported

hasLinguisticAbility
hasLinguisticAbilitySelfReported

hasNationalHeritage
hasNationalHeritageSelfReported

hasNationality
hasNationalitySelfReported

hasNativeLinguisticAbility
hasNativeLinguisticAbilitySelfReported

hasPoliticalAffiliation
hasPoliticalAffiliationSelfReported

hasRaceColour
hasRaceColourSelfReported

hasReligion
hasReligionSelfReported

hasSexuality
hasSexualitySelfReported

hasSocialClass
hasSocialClassSelfReported

**Comment by alliyya** [comment]
@lemaka Could you take a look at the Orlando schema and see that these are all appropriate and should have a self-defined attribute. Ex. `hasPoliticalAffilation`

**Comment by alliyya** [comment]
French definitions and English definitions should be glanced over and reviewed. 

- cwrc:hasGenderReported
- cwrc:hasGeographicHeritageReported
- cwrc:hasNationalHeritageReported
- cwrc:hasNationalityReported
- cwrc:hasRaceColourReported
- cwrc:hasEthnicityReported
- cwrc:hasReligionReported
- cwrc:hasPoliticalAffiliationReported
- cwrc:hasSocialClassReported
- cwrc:hasLinguisticAbilityReported
- cwrc:hasNativeLinguisticAbilityReported
- cwrc:hasSexualityReported

Have all been created in 4fec1cfb5b7fc99577fa35a8b16868d619453057

**Comment by SusanBrown** [comment]
@jadepncr Would national identity simply be identité nationale?

**Comment by alliyya** [comment]
Jade is revising/creating french definitions of all properties in another later issue.
