### ISSUE TITLE
Review racecolour and ethnicity in CF spreadsheet for free-form values that should be added

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#340]
https://docs.google.com/spreadsheets/d/1c2tSK7oqwHeSc1YFLjnEEgaGzVk8DMn1Y3O10I8PD08/edit#gid=371351779

Seems that we only added the reg values, whereas some (but not all) of the freeform values should be added.

**Comment by alliyya** [comment]
See also scrapes from #59 and #108

**Comment by JasmineDW** [comment]
To do: Make a new table with fixes and mark them with "noted"

**Comment by JasmineDW** [comment]
For Race and Colour: <a href='https://docs.google.com/spreadsheets/d/1c2tSK7oqwHeSc1YFLjnEEgaGzVk8DMn1Y3O10I8PD08/edit#gid=1585595240'> https://docs.google.com/spreadsheets/d/1c2tSK7oqwHeSc1YFLjnEEgaGzVk8DMn1Y3O10I8PD08/edit#gid=1585595240 </a>

- In whiteRaceColour, missing single quotation marks around colored in: "populations contrasting with 'black', American Indian, 'colored'..."
- Should #eurasian be added to the spreadsheet? It appears as a Concept under cwrc:RaceColour, but it's only listed under "Free form values" in the spreadsheet.
- Certain "Free form values" require definitions, modifications, confirmed deprecation (see legend in document)

**Comment by alliyya** [comment]
Only missing 2 instances for RaceColour, See issue #319
