### ISSUE TITLE
Discussion of use of altLabel in Preamble

### ISSUE THREAD

**Issue by joelacummings** [cwrc/ontology#347]
Need to discuss the use of altLabels.

**Comment by joelacummings** [comment]
First crack at it, needs to be revised. 

> When labelling types CWRC has decided to utilize two schemes for the purpose of searchability. rdf:label is to represent the CWRC terminology for a concept, instance or predicate this is terminology we use when describing the ontology in documentation as well as diagrams. However, in recognition of the external projects and data that will be integrated with CWRC. To support those with existing knowledge of such data skos:altLabel will be used to provide context of the data exists within the CWRC ontologies. skos:altLabel primarily exists for searching and retrieval the alt labels may not represent a direct replacement for rdfs:label.

**Comment by SusanBrown** [comment]
{my stab at a revision. Is the stuff about extraction TMI?}

For labelling, CWRC utilizes two schemes to promote searchability. rdf:label represents the CWRC terminology for a concept, instance, or predicate. This is the terminology used when describing the ontology in documentation and diagrams.  

To support those with knowledge of external projects and data that are integrated with CWRC, whose strings or terms have sometimes been linked for extraction purposes to CWRC terms, skos:altLabel provides additional linguistic context for CWRC ontology data. Within the ontology then, skos:altLabel primarily exists for searching and retrieval by allowing ontology terms to be located under a larger number of labels. Alt labels typically cannot serve as replacements for rdfs:label.
