### ISSUE TITLE
Generic provenance statements re: sources of terms missing

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#35]
From this version: http://sparql.cwrc.ca/testing/cwrc.html
As of 1:30am

**Comment by rwarren2** [comment]
"Note: This term and its definitions are derived from multiple sources. Please see the raw ontology for full provenance." is what I have for the moment. Changing this means changing the generator code which is more work than I can do for now.

I will have some suggestion for better provenance tracking at the end of next week.

**Comment by SusanBrown** [comment]
Not sure what I am supposed to do with this.

**Comment by rwarren2** [comment]
This is something I have to work on.

**Comment by alliyya** [comment]
@rwarren2 Has this been resolved in the updated document generator or something that needs to implemented?

**Comment by alliyya** [comment]
Or is this meant for terms that don't exactly have provenance statements

**Comment by rwarren2** [comment]
Resolved in new documentation generator.
