### ISSUE TITLE
blackwoman

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#350]
create a separate instance to be typed as both gender and ethnicity, and object of both hasGender and hasEthnicity

Make a graffle

See: https://docs.google.com/spreadsheets/d/1fGhAe1qutR-YKv9qeJkAERmUqFC5-GUh5W9ycHE9fI8/edit?disco=AAAAB3t7p1Y&ts=5ae10607&usp=comment_email_document

**Comment by alliyya** [comment]
from Susan: 
blackwoman

An intersectional identity that co-occurs with but is not reducible to the combination of "has gender woman" and "has race or colour black". See https://en.wikipedia.org/wiki/Black_women and (Kimberlé Crenshaw, 1989).
