### ISSUE TITLE
Review usage of foaf:name

### ISSUE THREAD

**Issue by alliyya** [cwrc/ontology#351]
We should assess, if we're using foaf:name appropriately and/or should be using this property.
Here's a list of them
```
<foaf:name>Event</foaf:name>
<foaf:name xml:lang="en">Place</foaf:name>
<foaf:name xml:lang="fr">Endroit</foaf:name>
<foaf:name xml:lang="en">language</foaf:name>
<foaf:name xml:lang="en">England (Geographic Heritage)</foaf:name>
<foaf:name xml:lang="en">Jewish (Geographic Heritage)</foaf:name>
<foaf:name xml:lang="en">man (gender)</foaf:name>
<foaf:name xml:lang="en">woman (gender)</foaf:name>
<foaf:name xml:lang="en">transman/transmale (gender)</foaf:name>
<foaf:name xml:lang="en">transwoman/transfemale (gender)</foaf:name>
<foaf:name xml:lang="en">heterosexual (sexual identity)</foaf:name>
<foaf:name xml:lang="en">homosexual (sexual identity)</foaf:name>
<foaf:name xml:lang="en">lesbian (sexual identity)</foaf:name>
<foaf:name xml:lang="en">bisexual (sexual identity)</foaf:name>
<foaf:name xml:lang="en">white (race colour)</foaf:name>
<foaf:name xml:lang="en">black (race colour)</foaf:name>
<foaf:name xml:lang="en">asian (race colour)</foaf:name>
<foaf:name xml:lang="en">jewish (race colour)</foaf:name>
<foaf:name xml:lang="en">eurasian (race colour)</foaf:name>
<foaf:name xml:lang="en">African (ethnicity)</foaf:name>
<foaf:name xml:lang="en">white (ethnicity)</foaf:name>
<foaf:name xml:lang="en">Jewish (Ethnicity)</foaf:name>
<foaf:name xml:lang="en">white</foaf:name>
<foaf:name xml:lang="en">black</foaf:name>
<foaf:name xml:lang="en">Jewish</foaf:name>
<foaf:name xml:lang="en">english</foaf:name>
<foaf:name xml:lang="en">Man (Label)</foaf:name>
<foaf:name xml:lang="en">Woman (Label)</foaf:name>
<foaf:name xml:lang="en">queer (Label)</foaf:name>
```

**Comment by joelacummings** [comment]
I think Rob introduced these -- probably for alternative labelling schemes. FOAF is not specific about usage of name. This is the FOAF definition of name "_name - A name for some thing._" This means it can be used for anything however.

```rdfs:label``` -- what we use consistently has this definition.
> rdfs:label is an instance of rdf:Property that may be used to provide a human-readable version of a resource's name.

FOAF is primarily designed for naming people and their relation to documents so part of this is my perception but I always think of a persons name like their example.


```xml
<foaf:Person rdf:about="#danbri" xmlns:foaf="http://xmlns.com/foaf/0.1/">
  <foaf:name>Dan Brickley</foaf:name>
  <foaf:homepage rdf:resource="http://danbri.org/" />
  <foaf:openid rdf:resource="http://danbri.org/" />
  <foaf:img rdf:resource="/images/me.jpg" />
</foaf:Person>
```

My opinion is we shouldn't use foaf:name for things are not people real or fake and should use rdfs:label, skos:altLabel, skos:prefLabel, skos:hiddenLabel etc to label our terms. 

I'd be interested in hearing other's opinions as though. Maybe someone also better knows Robs motivation for using foaf:name as I think that would help the discussion.

**Comment by SusanBrown** [comment]
I agree that we should primarily use the labels from rdfs and skos. 

The one thing that makes me wonder if we want to hang on to foaf:name is that we have a bunch of name tags in the Orlando data for things like married name, titled name, nickname etc. Would there be any advantage to linking those to foaf:name?

**Comment by SusanBrown** [comment]
Yes, maybe.

But am I right that you are advocating that we should go ahead and change things like this?

`<foaf:name xml:lang="en">England (Geographical Heritage)</foaf:name>`

**Comment by alliyya** [comment]
Yes, should I get rid of foaf:name usages such as any of the following
`<foaf:name>Event</foaf:name>
<foaf:name xml:lang="en">Place</foaf:name>
<foaf:name xml:lang="fr">Endroit</foaf:name>
<foaf:name xml:lang="en">language</foaf:name>
<foaf:name xml:lang="en">England (Geographic Heritage)</foaf:name>
<foaf:name xml:lang="en">Jewish (Geographic Heritage)</foaf:name>
<foaf:name xml:lang="en">man (gender)</foaf:name>
<foaf:name xml:lang="en">woman (gender)</foaf:name>
<foaf:name xml:lang="en">transman/transmale (gender)</foaf:name>
<foaf:name xml:lang="en">transwoman/transfemale (gender)</foaf:name>
<foaf:name xml:lang="en">heterosexual (sexual identity)</foaf:name>
<foaf:name xml:lang="en">homosexual (sexual identity)</foaf:name>
<foaf:name xml:lang="en">lesbian (sexual identity)</foaf:name>
<foaf:name xml:lang="en">bisexual (sexual identity)</foaf:name>
<foaf:name xml:lang="en">white (race colour)</foaf:name>
<foaf:name xml:lang="en">black (race colour)</foaf:name>
<foaf:name xml:lang="en">asian (race colour)</foaf:name>
<foaf:name xml:lang="en">jewish (race colour)</foaf:name>
<foaf:name xml:lang="en">eurasian (race colour)</foaf:name>
<foaf:name xml:lang="en">African (ethnicity)</foaf:name>
<foaf:name xml:lang="en">white (ethnicity)</foaf:name>
<foaf:name xml:lang="en">Jewish (Ethnicity)</foaf:name>
<foaf:name xml:lang="en">white</foaf:name>
<foaf:name xml:lang="en">black</foaf:name>
<foaf:name xml:lang="en">Jewish</foaf:name>
<foaf:name xml:lang="en">english</foaf:name>
<foaf:name xml:lang="en">Man (Label)</foaf:name>
<foaf:name xml:lang="en">Woman (Label)</foaf:name>
<foaf:name xml:lang="en">queer (Label)</foaf:name>
`

**Comment by SusanBrown** [comment]
Yes, I think so. Replace with `rdfs:label` if not already present.

**Comment by SusanBrown** [comment]
@alliyya can this be closed?
