### ISSUE TITLE
Graffle for TextLabel and hasRepresentation

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#355]
Please review.
png: https://drive.google.com/file/d/1q8j9kn9E-sAon20_1eVVQw4OvFu-vjJ9/view?
graffle: https://drive.google.com/open?id=1QpaljNsqmQUnQL9vTU2_hCvoldfPfw6y

Not at all sure about these predicate names since they are very awkward, so holding off adding until we have a bit more discussion.

I know we want to use the "has" form a lot, but "represents" and would be more graceful than "representation of"

**Comment by joelacummings** [comment]
The definition looks good to me, I think represents is fine (I think we initially called it that) as long as we are mostly consistent I'd say it makes sense.

**Comment by SusanBrown** [comment]
Ok, thanks. I have changed the predicates on the graffle to represents/representedBy and am moving it into the approved folder.
