### ISSUE TITLE
Translate missing/revised terms

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#356]
- [ ] EducationContext definitions (main one plus 3 subcontexts) need retranslating, as they came directly from the Orlando documentation.
- [ ] hasAward 
- [ ] hasEducation, so those need translating too.

Some if not all of these:
- [ ] Organization
- [ ]   prepSchool
- [ ]  hasEducation
- [ ]   5. natively known language (self-reported)
- [ ]   6. literalForm (to be deprecated)
- [ ]   7. personaTo (which should be changed to personaOf please @alliyya )
- [ ]   cwrc:EducationalAward
- [ ]   cwrc:EducationalOrganization

**Comment by jadepncr** [comment]
- [ ] EducationContext > **ContexteÉducatif**

Contexte Éducatif est une sous-classe de contexte important. Elle contient les sous-classes de contexte d'éducation domestique, d'éducation institutionnelle et d'apparentissage autodidacte. Les annotations entrées en tant que Contexte Éducatif ou en tant que sous-classe fournissent des informations et des discussions sur l'éducation d'une personne, qu'elle soit formelle ou informelle.


- [ ] self taught education context > **contexte éducatif autodidacte** 

Contexte éducatif lié à l'apprentissage mené de façon autonome. 

- [ ] hasAward > **aUneRécompense** 

Indique une récompense, un prix ou une distinction qu'une personne a gagné, tel qu'un prix littéraire ou un prix d'éducation.

- [ ] hasEducation > **aUneÉducation**

Relie une personne à des renseignements sur son contexte éducatif. 

- [ ] Organization > **Organisation** 

Une institution publique ou privée telle qu'une maison d'édition, une école, un groupe politique ou une entreprise.

- [ ]   prepSchool > **École préparatoire** 

Within a North American context, prep schools are private educational institutions that prepare students for college. Within a British context, they are private schools for students -- the age range of the students can vary significantly depending on when they went to school, though typically ranging from ages seven (though sometimes three) to thirteen.

Dans le contexte nord-américain, les écoles préparatoires sont des établissements d'enseignement privés qui préparent les étudiant·e·s à l'université. Dans le contexte britannique, ce sont des écoles privées pour les étudiants; la tranche d'âge des élèves peut varier considérablement en fonction du début de leur scolarisation, mais elle va généralement de sept (parfois trois) à treize ans.

- [ ]  hasEducation

(see above) 

- [ ]   5. natively known language (self-reported) > **Langue native (autodéclarée)**

Connaissance parlée, écrite ou lue d'une langue acquise durant l'éducation, qui peut être autodéclarée ou assignée par une autre personne, accompagné par le contexte fourni par le contexte de forme culturelle lorsqu'il est disponible. Comme pour d'autres formes culturelles, un individu peut avoir plus d'une propriété ou descripteur de ce type.

- [ ]   6. literalForm (to be deprecated)

Deprecated?

- [ ]  personaTo > **PersonaDe**

Inverse de a un persona, dont la définition est la suivante:
Associe un persona à une ou plusieurs personne(s) physique(s). 

- [ ] Educational award prize > **Prix éducatif** 

Un prix éducatif est une médaille ou une récompense, financière ou autre, attribuée par une institution ou une personne d'autorité à un individu ayant excellé par rapport à ses camarades, a concrétisé un projet d'envergure  et/ou a fourni un travail de grande qualité. 

- [ ]  educational award scholarship > **Bourse d'études** 

A scholarship is an award of financial aid for a student to further their education. Scholarships are awarded based upon various criteria, which usually reflect the values and purposes of the donor or founder of the award. Scholarship money is not required to be repaid.

Une bourse d'études est une bourse d'aide financière qui permet à un·e étudiant·e de poursuivre ses études. Les bourses sont accordées en fonction de critères variés, qui reflètent généralement les valeurs et les objectifs du/de la donateur·ice ou fondateur·ice de la bourse. Les bourses d'études ne sont pas destinées à être remboursées.

- [ ]   cwrc:EducationalOrganization

After double-checking, all present in the French version. 

@alliyya French terms eventually ready to be moved, thank you!
