### ISSUE TITLE
deprecate hasForbear

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#358]
We do not need this relationship given how we decided to treat forbear relationships

**Comment by SusanBrown** [comment]
Also deprecate forebearOf

**Comment by SusanBrown** [comment]
Or do they need to be deprecated? They are not in the published ontology. Can we not just delete them? @joelacummings @alliyya

**Comment by alliyya** [comment]
Forebearof needs to be deprecated as its in the published ontology, I don't see hasforebear so that can be removed
