### ISSUE TITLE
Do escaped characters for scare quotes constitute a problem?

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#359]
Not sure why we are using `&quot;`but am worried that because it is not unicode it could cause problems down the line.

Can someone explain why we are doing this? is it 1) necessary or 2) possibly a problem?

**Comment by alliyya** [comment]
It should not be a problem, I think the html entities were previously a remnant of issues with encoding as a fallback.

using " should be used over &quot; 

Only thing is one must use
`&amp;` when trying to use an ampersand(&)
as html/xml expects there to be an entity after it like &quot; or &lquot;
