### ISSUE TITLE
hasStepParent/hasStepChild inverse relations

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#360]
Should these not be inverse relationships? 

Also hasStepdaughter/Stepson and has stepParent and hasStepmother/Stepfather and has stepChild?

**Comment by joelacummings** [comment]
Yes they should be inverse relations, will fix.

**Comment by alliyya** [comment]
For properties that would be symmetric is the inverse necessary to exist in the ontology?
Ex.
`hasCousin` & `cousinOf`
`hasPartner` & `partnerOf`
`hasSibling` & `siblingOf`
`hasRelative` & `relativeOf` 
Unless these aren't necessarily symmetric.
