### ISSUE TITLE
Relationships: lived, intimate, erotic, and friendly

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#363]
This picks up on a specific issue I just raised in #281, which I am breaking out here for the sake of clarity/sanity. I think we should have individual issues for this sort of thing. I want to debate the matter of structure raised by this fact:

- Both FriendsAndAssociates _and_ IntimateRelationship elements have a subelement "LivesWith"
- IntimateRelationships has the Erotic attribute, with values yes/no/possibly

So the Erotic attribute, if present applies to everyone within the IR tag, whereas LivesWith may apply to a subset of people mentioned inside either tag. 

Because one is an element and one an attribute, I can't see getting away from creating two edges when they co-occur, but I think we can keep the number of edges that need to be created to two using subproperties. I propose the following (see stripped-down code below--if there are small errors pls don't point them out here so we can focus on the bigger issues). It relates all the terms to "friend or associate" as the most general property.

```xml
<owl:ObjectProperty rdf:ID="hasFriendOrAssociate">
    <rdfs:label xml:lang="en">has friend or associate</rdfs:label>
    <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#SymmetricProperty"/>
```

```xml
<owl:ObjectProperty rdf:ID="relatesIntimatelyTo">
    <rdfs:label xml:lang="en">relates intimately to</rdfs:label>
    <rdfs:subPropertyOf rdf:resource="#hasFriendOrAssociate"/>
```

```xml
<owl:ObjectProperty rdf:ID="relatesEroticallyTo">
    <rdfs:label xml:lang="en">relates erotically to</rdfs:label>
    <rdfs:subPropertyOf rdf:resource="#relatesIntimatelyTo"/>
   <skos:related rdf:resource="#hasPossiblyEroticRelationship"/>
```

```xml
<owl:ObjectProperty rdf:ID="possiblyRelatesEroticallyTo">
    <rdfs:label xml:lang="en">possibly relates erotically to</rdfs:label>
    <rdfs:subPropertyOf rdf:resource="#relatesIntimatelyTo"/>
    <skos:related rdf:resource="#relatesEroticallyTo"/>
```

``` xml
<owl:ObjectProperty rdf:ID="hasNonEroticIntimacy">
    <rdfs:label xml:lang="en">has non-erotic intimacy with</rdfs:label>
    <rdfs:subPropertyOf rdf:resource="#relatesIntimatelyTo"/>
```

```xml
<owl:ObjectProperty rdf:ID="livesWith">
    <rdfs:label xml:lang="en">lives with</rdfs:label>
    <rdfs:subPropertyOf rdf:resource="#hasFriendOrAssociate"/>
```

```xml
<owl:ObjectProperty rdf:ID="livesIntimatelyWith">
    <rdfs:label xml:lang="en">lives intimately with</rdfs:label>
    <rdfs:subPropertyOf rdf:resource="#livesWith"/>
```

```xml
<owl:ObjectProperty rdf:ID="livesErocitallyWith">
    <rdfs:label xml:lang="en">lives erotically with</rdfs:label>
   <rdfs:subPropertyOf rdf:resource="#livesIntimatelyWith"/>
    <skos:related rdf:resource="#livesPossiblyEroticallyWith"/>
```

```xml
<owl:ObjectProperty rdf:ID="livesPossiblyErocitallyWith">
    <rdfs:label xml:lang="en">lives possibly erotically with</rdfs:label>
    <rdfs:subPropertyOf rdf:resource="#livesIntimatelyWith"/>
    <skos:related rdf:resource="#livesEroticallyWith"/>
```

```xml
<owl:ObjectProperty rdf:ID="livesNonEroticallyWith">
    <rdfs:label xml:lang="en">lives non-erotically with</rdfs:label>
    <rdfs:subPropertyOf rdf:resource="#livesIntimatelyWith"/>
```

**Question 1: Do the relationships and the granularity make sense overall?** I think this is consistent with the direction we set at the retreat.

**Question 2: can we do better with terms/labels?** I'm afraid I just balked at "has possibly erotic relationships to", especially after failing to come up with a "has" construction for "livesWith" that wasn't laughably bad. I thought of e.g. "has intimate" , "has possible intimate" etc. but that seemed too arcane a way of putting it for general consumption.  As you'll see I ended up with an ungodly mix. Responses, please.

**Question 3: what about symmetry?** I have made  "friend or associate" symmetrical. Am I right that this would mean that all subproperties inherit that?

Some IntimateRelationships were definitely not reciprocated. We mention a rejected suitor and an accepted suitor in the same sentence. And in such cases the intimacy, if any, was almost more on the spurned suitor's side than the writer's.

This is a difficult one because we'd in probably at least 95% of cases want the relationship to be reciprocal. So we could as with Friends make it reciprocal but indicate in the definition that the term covers a spectrum of intimacy ranging from desired but unrealized to long-term relationships and that the level of desire or intimacy could be quite unbalanced as between the two persons. This would match the usage, I think.

LivedWith should be reciprocal, so I'm leaning towards reciprocality and explaining the range.

**Comment by joelacummings** [comment]
1. Yes the relations seem to make sense based on what is described and is consistent with other predicates. 

2. I think this is where are butting up with the reducing number predicates needed on an individual with having very specific predicates -- we will have to choose our labels and IDs carefully. I'm not sure I'll be much help with this but I agree the has relation will not always work. 

3. Yes the sub properties will inherit this -- they must always be more specific than their parents if that makes sense. I agree that we should be careful with using symmetric here, I'm not too familiar with the Orlando definitions but to me it seems that friends may not be symmetric? 

The symmetric may make it difficult because those reading the triples or in a visual tool will automatically see those relationships but even with the definition how will they know it really was both ways? This puts the burden on the user and I'm not sure if we want that.
