### ISSUE TITLE
Reconcile  higher-level genre groupings with CWRC primary genres

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#364]
http://cwrc.ca/terms/primary_genre.pdf

**Comment by alliyya** [comment]
Is this needed for the dataset? @SusanBrown 
Status update? @lemaka

**Comment by SusanBrown** [comment]
Yes, needed for the dataset.


On Aug 24, 2018, at 10:18 AM, Alliyya Mo <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this needed for the dataset? @SusanBrown<https://github.com/SusanBrown>
Status update? @lemaka<https://github.com/lemaka>

**Comment by SusanBrown** [comment]
This is done, is it not @lemaka, with the results reflected in the public version of the genre ontology?
