### ISSUE TITLE
update altLabels for Cultural Formation instances 

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#366]
from @alliyya : This also ties into how can we automate this wrt to the spreadsheets and extraction.

**Comment by alliyya** [comment]
Here's the a spreadsheet of the current alt labels in the ontology
https://drive.google.com/open?id=19BTVIxj0b8q_pcl_JJn_O0kI_U-rHc9_YF8jfl7H4H8

**Comment by lemaka** [comment]
what exactly is the task at hand here, @alliyya ?

my fish brain wont remember what "update" means in this context

**Comment by alliyya** [comment]
Duplicate issue of #424
