### ISSUE TITLE
Instances of Religious Organizations

### ISSUE THREAD

**Issue by JasmineDW** [cwrc/ontology#367]
1. Create instances of religious organizations (orgName inside denomination)

**Comment by alliyya** [comment]
Being worked on in https://drive.google.com/open?id=1uhwsU2mJvXLYi9ZZepG_tp1ZlHyUz5ECAqt8ftaZoKI

**Comment by alliyya** [comment]
Being automatically created from organization authority list and typed accordingly to the context they appear within(PA/Religion).
