### ISSUE TITLE
Scrape orgNames and Nationalities

### ISSUE THREAD

**Issue by JasmineDW** [cwrc/ontology#368]
1. Create a scrape of Org names within denomination tag by grabbing all reg tags
2. Create scrape of all nationalities
3. Create scrape of politicalaffiliation with woman-genderissue=GENDERYES

**Comment by joelacummings** [comment]
1. Denomination scrape -- https://docs.google.com/spreadsheets/d/1O9yaWpxjAHko52yS2iWqkgAK9OhkzISnxIKj0xUsv1E/edit#gid=0

**Comment by joelacummings** [comment]
2. Nationalities -- https://docs.google.com/spreadsheets/d/1MuRHq1R3q1j7s7DOexnB4FblUS3l5jVIyhf1G61ZYJQ/edit#gid=0

3. Political affiliations genderless -- https://docs.google.com/spreadsheets/d/1rT5kC4oUdH-5uZID-arrwizs1-yRJAN0tE-iNrqeQGs/edit#gid=0
