### ISSUE TITLE
put sample dataset up on sparql end point

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#369]
So that we can start getting HuViz set up to work with the sparql end point, let's prepare one of our test datasets and get it up there. We don't have URIs for the Orlando data but if we can use external URIs for everything for now, that will be fine.

@antimony27 could you suggest what the dataset would be and review it for completeness of URIs, then pass on to @joelacummings ? Joel, is there anything else we should be considering?

**Comment by joelacummings** [comment]
No sounds like a good idea to me, I will get the sprawl endpoint setup to be read only.

**Comment by alliyya** [comment]
@joelacummings has this been done?

**Comment by joelacummings** [comment]
No, will do so shortly though.

**Comment by alliyya** [comment]
Done now @joelacummings ?

**Comment by joelacummings** [comment]
Added BronteMini -- example query. 

```SPARQL
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cwrc: <http://sparql.cwrc.ca/ontologies/cwrc#>
SELECT * WHERE {

cwrc:CharlotteBronte ?p ?o .

} 
LIMIT 10
```

and CanAuthorsBiography
