### ISSUE TITLE
race or ethnicity

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#372]
I don't believe we need this:
http://sparql.cwrc.ca/testing/cwrc.html#RaceEthnicity

What do others think?

**Comment by alliyya** [comment]
I think this was originally created with thought of race or ethnicity context and the `RaceAndEthnicity` tag in orlando. We've split up ethnicity and race into their own classes, I don't think it is necessary if all our instances are within either ethnicity or race.

**Comment by SusanBrown** [comment]
Just go ahead and deprecate it.
