### ISSUE TITLE
Make "hasInstitution" decision For Education Events

### ISSUE THREAD

**Issue by JasmineDW** [cwrc/ontology#377]
Is “hasInstitution” a property of an event or not?

**Comment by alliyya** [comment]
If this wrt to linking a school to an event?

Based on our discussions of events this week.
A school(educationalorganization) would be an actor in the event and this predicate is not necessary? Wydt @SusanBrown

**Comment by SusanBrown** [comment]
Agree.



On Aug 24, 2018, at 10:44 AM, Alliyya Mo <notifications@github.com<mailto:notifications@github.com>> wrote:


If this wrt to linking a school to an event?

Based on our discussions of events this week.
A school(educationalorganization) would be an actor in the event and this predicate is not necessary? Wydt @SusanBrown<https://github.com/SusanBrown>

**Comment by alliyya** [comment]
Decision: Not making  “hasInstitution” a property of an event and instead EducationalOrganizations will be actors within the event.
