### ISSUE TITLE
Numbering Context annotations

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#385]
The graffle for the annotations is coming along: https://drive.google.com/open?id=1HswW74n7pCoUYAwMKXAp8BFRYZ22DXuk . Joel is going to add the triples this weekend.

In putting in the XML, I thought more about the length of snippets. I think they should be shorter and more numerous unless and until we arrive at a more sophisticated sense of how we might deliver context to users. 

So as the graffle lays out, my proposal is that each paragraph within each tag that is generating a Context generate a separate Context, and that they be numbered. I have articulated this in the spreadsheet for Death as follows:  

`Create {Subjectname}DeathContext instance(s) from contents of the <DEATH> tag.`

`Create 1 DeathContext instance per paragraph, numbering them as {Subjectname}DeathContext1 / {Subjectname} death context 1`

`Link each Context to person as Target of annotation as per OA graffle: https://drive.google.com/open?id=1HswW74n7pCoUYAwMKXAp8BFRYZ22DXuk`

`Order annotations so that the Context is the first Body of the annotation.`

**Decision**:

Where there is more than one paragraph relating to context, we would break them up so as to avoid too many things relating to one context;
This will make contexts more specific to the things they reference (and we will be working out a principle by which to omit text that goes beyond a certain # of words (greying out in graffles for now)
Where there's a chronstruct context is made by taking chronstruct AND paragraph following it. @alliyya to mull over whether we could do this in a way that would better balance lengths of Contexts.

`Create separate oa: annotations with the same first Body[i.e. the same the Context] motivatedBy "identifying" for NAMES, ORGNAMES, etc. mentioned in the prose IF AND ONLY IF they do not occur in a triple derived from that Context`

Does this seem acceptable?

**Comment by joelacummings** [comment]
So this would be creating more bodies if I'm understanding correctly. So the Death Context would have have one body per paragraph? The first paragraph is the one we would show by default. If that's the case that does seem acceptable to me. I think that's probably a better use of of Web Annotations particularly if we are able to use more motivations.

**Comment by SusanBrown** [comment]
I wasn't thinking it would create more bodies on a single annotation. 

I thought it would mean creating multiple annotations. And isn't it only one Motivation per annotation which will always be "describing" for the components related to the subject of an entry.

For entities that occur in the Context but that are not part of a triple a separate annotation would therefore need to be created, I think, in order to use the "identifying" motivation.

**Comment by SusanBrown** [comment]
Wdyt, @joelacummings ? I modified my initial comment to try to clarify what I was saying about mentions of people.

**Comment by lemaka** [comment]
Decision: Where there are more than one paragraph relating to context, we would break them up so as to avoid too many things relating to one context; 
So, context is more specific + greying out a part of the text; 
Where there's a chronstruct you take chronstruct AND paragraph following it.? @alliyya to mull over
