### ISSUE TITLE
translate death; death extraction

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#389]
The death tab in the bio spreadsheet is ready for translation.

Apart from the pending questions, whose cells are still in yellow, the extraction scripts can be started now as well.

**Comment by lemaka** [comment]
https://docs.google.com/spreadsheets/d/1L9V__vfiZ2hEZOsbVkMZ7-JlsToHHOuOKzbPIi-HTPs/edit#gid=767320556

**Comment by jadepncr** [comment]
All the pink cells are now translated.
