### ISSUE TITLE
Create sample oa triples for oa:motivatedBy "identifying"

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#390]
Joel, could you please create some sample triples for this, and expand the graffle to show how it would work, to serve as a basis for extraction?

graffle is here:
https://drive.google.com/open?id=18WRW2CDV3mEFeEqKboeOkMzOy4ChMqrz

**Comment by joelacummings** [comment]
We currently do not have hasFamily so I will leave that out for the time being.

**Comment by joelacummings** [comment]
Triples added!
