### ISSUE TITLE
retranslate portions of CF definitions

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#396]
- [x] NationalIdentity significantly revised

- [x] the phrase "this class and its subclasses" was revised through CF definitions to "this class and its instances"

Commit#02dc156

**Comment by jadepncr** [comment]
- [ ] National Identity/Nationalité

Une sous-catégorie de @@#FormeCulturelle@@, cette propriété indique la nationalité d'une personne, accompagnée du contexte fourni par les annotations de @@#ContexteDeNationalité@@ lorsqu'il est disponible. Elle diffère de la citoyenneté et n'est pas proportionnelle à la zone géographique ou au territoire de la personne, **même si elle est généralement liée au pays ou à la zone géographique actuelle ou passée. Pour cette raison,  <![CDATA[<a href="(see https://fr.wikipedia.org/wiki/ISO_3166-2)>les codes de la norme ISO 2 pour la représentation des pays et de leurs subdivisions-Partie 2 : Codes des subdivisions des pays</a>]]> sont utilisés dans la mesure du possible pour représenter les instances de nationalités, et seuls les termes pour lesquels aucun code pays n'existe apparaissent dans l'ontologie.** Comme d'autres catégories identitaires, la nationalité peut être plurielle, fluide ou contingente, et recoupe avec @@#NationalHeritage@@ ainsi qu'avec d'autres catégories identitaires. Les personnes qui utilisent cette classe et ses sous-classes sont encouragées à consulter les annotations de @@#NationalityContext@@ lorsqu'elles sont disponibles.

@alliyya Translation ready to be edited, thank you!
