### ISSUE TITLE
Organization ontology

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#397]
https://www.w3.org/TR/vocab-org/#org:originalOrganization

This looks pretty good to me, possibly good enough to import and almost certainly good enough for pulling terms from. @DeborahStacey @joelacummings do you know how widely used it is? LOV doesn't seem to indicate much use but it is a w3c one so I expect that is wrong.

**Comment by DeborahStacey** [comment]
Hi Susan


Looks good to me - at the very least we should use terms but unless we have a better idea this ontology for organization could be imported.


Deb

________________________________

**Comment by lemaka** [comment]
can we mark this as a decision, @SusanBrown, and close the issue?

**Comment by SusanBrown** [comment]
@joelacummings Shall we go ahead and import it? 

Perhaps you could review role, post, and location and see whether you foresee any problems, before advising.

**Comment by SusanBrown** [comment]
Consider in relation to event stuff.

**Comment by joelacummings** [comment]
Decision: will use as a namespace in the ontology
