### ISSUE TITLE
hasOrganization

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#398]
Proposed predicate: hasOrganization

Indicates that the organization in question belongs in some sense to the specified conceptual entity. For instance, a particular religion may have one or more organizational groups associated with it, a political campaign may have multiple political groups associated with it simultaneously or sequentially, or an artistic movement may have various contributing groups.  

Note: I think we probably need to distinguish this kind of association with an organization from the following: 
- Events may also have organizations associated with them. Seems like the organization is an actor or factor in the event. Sometimes the relationships will be quite specific thanks to the market, e.g. SubjectOfStudy
- A university may have multiple organizations that it sponsors/houses. Seems more like a whole/part relationship. (org:suborganizationOf may be fine for this)

**Comment by alliyya** [comment]
@SusanBrown Is this term ready to go in the ontology?

**Comment by SusanBrown** [comment]
Yes. Revised definition slightly.
