### ISSUE TITLE
proposal: hasAffiliation

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#399]
Proposed predicate:

hasAffiliation
Indicates a person's affiliation with a particular organization. Affiliations may be narrowed down by the particular Context, such as ReligionContext, in which the affiliation is mentioned, by the type of organization involved (where typing is present), or by subpredicates such as:
- cwrc:hasPoliticalAffiliation
- org:memberOf

NB. that we have already created the following. We will not have the reporting attributes for most other types of affiliations, at least not in the Orlando data. We will need to decide if we keep them or not. The above definition suggests that we keep them for now.
- hasPoliticalAffiliation
- hasPoliticalAffiliationReported
- hasPoliticalAffiliationSelfReported

**Comment by alliyya** [comment]
Given the predicates we've created wrt PoliticalAffiliation, do we still need this predicate?

**Comment by SusanBrown** [comment]
Maybe not. Hold off for now and see if other affiliations arise that would require this more general property.
