### ISSUE TITLE
Uber graph

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#40]
Create a reference graph combining our current graphs that reflects all of our decisions to date and commit to keeping it current.

**Comment by rwarren2** [comment]
Pulling in @alliyya since I'd like this to be generated automatically later on.

**Comment by rwarren2** [comment]
See https://drive.google.com/drive/folders/0B9lTUIf6YQsjQmhRemZQRmFrVE0 for some examples.

**Comment by alliyya** [comment]
Duplicate of #48
