### ISSUE TITLE
Religions and religious organizations

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#400]
Here in a sketch is my proposal for how these should work together. 
https://drive.google.com/open?id=1cssSMkJN25lqIRPd4W45JAiiM-7Ui6E1

![image](https://user-images.githubusercontent.com/545952/41758961-cac27476-75b9-11e8-9204-c52aacd544f5.png)

**Comment by alliyya** [comment]
cwrc:Organization should be deprecated in favour of org:FormalOrganization ? @SusanBrown 
And educational organization should be a subclass of org:FormalOrganization similarly to religious organization?

**Comment by SusanBrown** [comment]
Yes

On Jul 9, 2018, at 12:48 PM, Alliyya Mo <notifications@github.com<mailto:notifications@github.com>> wrote:


cwrc:Organization should be deprecated in favour of org:FormalOrganization ? @SusanBrown<https://github.com/SusanBrown>
And educational organization should be a subclass of org:FormalOrganization similarly to religious organization?

**Comment by alliyya** [comment]
In terms of extraction for Religion:
What should happen if the DENOMINATION is with no reg value and contains an ORGNAME:

`<DENOMINATION><ORGNAME REG="Roman Catholic Church" STANDARD="Roman Catholic Church">Roman Catholics</ORGNAME></DENOMINATION>`
Right now `Roman Catholics`(the freeform of the orgname) is an alt label for Roman Catholicism the religion.
So the religion can possibly be ascribed to the person that way. (Matching freeform of the org to altlabels of religions)

But I'm wondering if it should go through a query to see what religion that organization belongs to. (However this may lead to edge cases where an organization belongs to multiple religions and we wouldn't know for certain what religion that person subscribes to)

OR: if there's only an orgname in a denomination tag, only create the org:memberOf relation for that entry. aka no hasReligion for the this person
 
@SusanBrown

**Comment by SusanBrown** [comment]
If they belong to an org, then give them membership in that religion as well but not vice versa.



On Jul 9, 2018, at 1:19 PM, Alliyya Mo <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #400<https://github.com/cwrc/ontology/issues/400> to @SusanBrown<https://github.com/SusanBrown>.

**Comment by alliyya** [comment]
Religious Organizations will always be connected to a Religion, the same cannot be said for a Political affiliation and Political Organization

**Comment by lemaka** [comment]
@alliyya @SusanBrown this looks done to me, can this be closed and marked w the 'decision' label?
