### ISSUE TITLE
cwrc:TextLabels needs label 

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#402]
label should be "textual label"

**Comment by alliyya** [comment]
http://sparql.cwrc.ca/ontologies/cwrc.html#TextLabels
This is missing that label?

**Comment by SusanBrown** [comment]
Is there a way we can see the label here in the list of classes?

![image](https://user-images.githubusercontent.com/545952/42121738-0988cb38-7bfa-11e8-99a0-89aded97c5d8.png)

**Comment by alliyya** [comment]
When you hover over the hyperlinks it should tell you the label if available, I forgot to add the label for the header section when I added the hyperlink but I can add that.

**Comment by alliyya** [comment]
We can add bracketed labels beside the uri if you want?
ex. [blackLabel](http://sparql.cwrc.ca/testing/cwrc.html#blackLabel) (black identity)
I'm just concerned about limited space in the tables

**Comment by alliyya** [comment]
Not exactly sure what panels you're referring to :/
![image](https://user-images.githubusercontent.com/10135030/42131391-26658752-7ccf-11e8-95fb-d68e8d4dc15a.png)
Is how I was imagining a possible way to add the labels

**Comment by SusanBrown** [comment]
That would be good, I think. Also would like cwrc:TextLabels (textual label) (8) unless you can figure out something better than the two sets of brackets.

**Comment by alliyya** [comment]
How does this look @SusanBrown for the label by the uri
![image](https://user-images.githubusercontent.com/10135030/42460578-39054af2-836c-11e8-810f-2bb72ee7ead3.png)

**Comment by SusanBrown** [comment]
looks good
