### ISSUE TITLE
Representing Space & Time with CIDOC-CRM

### ISSUE THREAD

**Issue by JasmineDW** [cwrc/ontology#409]
@joelacummings to look at Geonames; E92 Spacetime volume; E49 Time appellation; E44 Place appellation to get us started with which aspects of CIDOC-CRM we are wishing to adopt, what requires a SameAs relationship, and what needs to be created as an extension to their ontology.

**Comment by lemaka** [comment]
this looks related to https://github.com/cwrc/ontology/issues/410

**Comment by lemaka** [comment]
From agenda, assigned to @joelacummings : 
Please review subevents, properties of properties, their relationship to reification ( w reference to CIDOC-CRM forum, which Jasmine sent to Joel to look over)

**Comment by alliyya** [comment]
I think this can be closed, WDYT @joelacummings ?
