### ISSUE TITLE
Look at Geonames; E92 Spacetime volume; E49 Time appellation; E44 Place appellation

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#410]
Assigned to Joel in notes from July 11th meeting, in connection with adoption of CIDOC-CRM.

**Comment by lemaka** [comment]
is this linked to https://github.com/cwrc/ontology/issues/409 ?

**Comment by SusanBrown** [comment]
Duplicate of #409 . Good catch, Abi.
