### ISSUE TITLE
Difference report French/English versions 

### ISSUE THREAD

**Issue by jadepncr** [cwrc/ontology#412]
## General 

- [ ] Typo in the title: **"Version English"** in the link between brackets instead of **"Version anglaise"**

- [x] "Terms and details" categories do not appear in the same order in the two different tables of contents. @alliyya  (is this something that can be easily fixed?)

English shows:
1. Object Property
2. Class
3. Annotation property 
4. Class instances 

French shows: 
1. Class
2. Annotation property 
3. Object Property 
4. Class instances 

- [ ] Only 4 headers in the Fr while Eng shows 5 ("Version History" is missing) 

- [x]  All "Comment" in Fr version to be replaced by "Note" [should be "Note: La description de ce terme est basée sur celle de DBPedia."]

## Class 

Terms present in the Eng missing in the Fr:

- [x] certainty

_Probabilité

La probabilité décrit la qualité d'un fait dans l'ontologie. Elle est principalement utilisée pour représenter des informations qui peuvent être des faits non avérés._

- [x] comprehensive school 
"Après l'école primaire, on a le choix entre deux types d'établissement : grammar school (lycée) et comprehensive state (lycée général). Pour entrer dans une grammar school, il faut passer un examen nommé "11+". Les Grammar schools étant pour les étudiants les plus doués, et les places étant limitées, la grande majorité des enfants fréquentent les state comprehensive." (https://fr.wikipedia.org/wiki/Syst%C3%A8me_%C3%A9ducatif_au_Royaume-Uni#Enseignement_primaire_et_secondaire)

- [x] educational organization (only class title) 
French class title should be: _Établissement éducatif_ 

- [x] skos:note about Geonames missing in Fr Geographic Heritage 

_skos:note: Les termes Geonames sont souvent utilisés pour les lieux et de nombreuses instances d'héritage géogrpahique._

- [x] persona 

_Un persona, contrairement à un rôle, ne peut être incarné par quiconque, mais est spécifique à une personne physique, ou plus rarement à plusieurs d'entre elles. Un persona est une création originale, souvent inspiré par le contexte biographique, historique et sociologique auquel son/ses créateur·ice(s) est/sont attaché·e(s). Les personae tels qu'ils sont définis ici ne doivent pas être confondus avecune maladie mentale ou à un trouble dissociatif de l'identité, car ils ne relèvent pas d'une perception déformée ou incontrôlée de la réalité. Le persona est avant tout une entité identitaire capable d'interargir avec le monde extérieur et qui peut parfois être confondue avec une personne physique réelle. Il est incarné et développé par une personne physique, et peut avoir une activité sociale, littéraire, artistique ou politique._

- [x] role 

_Rôle 

Le rôle d'une Personne ou d'un·e Acteur·ice au sein d'un Évènement, d'une Œuvre Créative ou une Organisation._  

- [x] state school 

_State school

State school est un terme utilisé en Australie, en Nouvelle-Zélande et au Royaume-Uni  pour distinguer les écoles gérées par le gouvernement des écoles privées._ 

(translated to French based on the Spanish DBpedia's description) 

Classes with different descriptions in English and in French: 

- [x] Language&Langue 
see issue #164 

- [x] National Identity&Nationalité (added: "either as self-reported . . .") 

_> Identité nationale_ 

_Une sous-catégorie de forme culturelle, cette propriété indique l'identité nationale d'une personne, qu'elle soit autodéclarée ou attribuée par d'autres, accompagnée du contexte fourni par les annotations de contexte national lorsqu'il est disponible. Elle diffère de la citoyenneté et n'est pas proportionnelle à la zone géographique ou au territoire de la personne, même si elle est généralement liée au pays ou à la zone géographique actuelle ou passée. Pour cette raison, (voir héritage national ainsi qu'avec d'autres catégories identitaires. Les personnes qui utilisent cette classe et ses instances sont encouragées à consulter les annotations de contexte national lorsqu'elles sont disponibles._

- [x] Political Affiliation&Affiliation Politique 

_> Appartenance politique 

Cette sous-classe de forme culturelle indique les appartenances, les connexions et les associations qui font partie de l'engagement politique d'une personne. Elles renvoient aussi bien aux connexions formelles avec un parti ou une organisation qu'aux autres partis pris politiques informels de l'auteur·e. Les appartenances politiques sont définies au sens large et incluent des exemples comme « lutte contre la peine de mort » ou « fervent·e défenseur·se de l'Empire » en plus d'appartenance plus directes telles que « marxiste » ou « conservateur·ice ». Les appartenances politiques peuvent être multiple, parfois contradictoires ou en tension, et peuvent changer au cours du temps._

- [x] Political Context&Contexte Politique 

_Contexte Politique est une sous-classe de contexte importante. Elle est associée à appartenance politique, sous-classe de forme culturelle, et recoupe parfois avec d'autres Formes Culturelles. Les annotations entrées en tant que Contexte Politique fournissent des informations et des discussions sur la subjectivité d'une personne en lien avec son activité politique. Contexte Politique explore plus en détails les catégories granulaires d'une personne grâce aux propriétés **a une appartenance politique ou a une appartenance politique (autodéclarée)**._

- [x] Sexuality&Sexualité (different quotes between brackets) 

_Une sous-classe de forme culturelle liée à sexualité en contexte, les propriétés de Sexualité indiquent en un mot ou en une phrase les identifications ou les aspects de la sexualité (par exemple "lesbienne", "monogame", "hétérosexuelle", mais aussi "promiscuité"), non pas pour clore la discussion mais pour développer l'étude et l'analyse critique de ces catégories. Comme l'identité sexuelle peut être plurielle et fluide, une même personne est susceptible d'être associée à plusieurs termes. L'identité sexuelle peut être formulée par la personne elle-même ou être assignée par d'autres individus. Les termes utilisés peuvent se trouver en tension ou se montrer incompatibles, et reflètent différentes périodes de l'existence. Par exemple, lier une personne au terme "lesbienne" comme classe de sexualité ne signifie pas nécessairement que cette dernière était définitivement lesbienne, car une telle identification est souvent impossible à cause des lacunes historiques et des silenciations. En ce qui concerne les personnes toujours en vie, nous ne nous appuyons que sur des sources ou des déclarations publiques faites par le sujet elle/lui-même afin de ne pas dévoiler par inadvertance des informations privées sur sa sexualité. Voir (Campbell and Cowan, 2016)_

- [x] Single-sex school&Éducation non-mixte (Eng comes from DBpedia and the Fr is ours) 

- [x] Race and Ethinicity Context (1st sentence differs) 

_Contexte Ethnique ou Racial est une sous-classe de contexte de forme culturelle associée aux sous-classes race ou couleur et ethnicité et parfois à d'autres formes culturelles. Les annotations entrées en tant que Contexte Ethnique ou Racial fournissent des renseignements de contextualisation et des discussions sur l'identité d'un sujet concernant son appartenance raciale et/ou son ethnicité. Même si les catégories de race et d'ethnicité sont fréquemment manipulées au service d'intérêts déplorables, leurs répercussions idéologiques et matérielles sur la formation identitaire requièrent qu'on les prenne en compte. Ces catégories sont changeantes, historiquement constituées, développées de façon intéressée, et leur usage doit être resitué dans leur contexte. Elles sont finalement comprises ici comme discursives et représentationnelles même si elles ont des répercussions concrètes sur la réalité. La race et le couleur sont donc des constructions sociales: « Le fait d'être ou de ne pas être d'une certaine race n'est rien de plus que l'acceptation sociale et l'attribution sociétale d'une race à une personne. » (Damon Sajnani, 2015)_

- [x] Religion 

Sous-classe de forme culturelle, décrit la/les religion(s) ou le(s) système(s) de croyance d'une personne. Notez que par commodité nous utilisons l'étiquette Religion pour l'athéisme, même si le terme indique l'absence de religion.

In-text links missing in Fr version: 
- [x] Link to race or ethnicity context in class Race or colour 

## Annotation Property

Missing in French:

- [x] Competency question 

Une question qui peut être posée à l’ontologie et servira à déterminer les exigences ontologiques de haut niveau du CSÉC, permettant ainsi de prendre des décisions sur sa structure et ses composants.

## Class instances 

**Certainty**

- [x] high certainty 

Forte probabilité

Une valeur de probabilité prédéfinie utilisée dans le cas où un fait est considéré comme une information de haute qualité.  

- [x] low certainty 

Faible probabilité

Une valeur de probabilité prédéfinie utilisée dans le cas où un fait est considéré comme une information de basse qualité. 

- [x] medium certainty 

 Probabilité moyenne

Une valeur de probabilité prédéfinie utilisée dans le cas où un fait est considéré comme une information de qualité moyenne. 

- [x] unknown certainty 

Probabilité inconnue 

Une valeur de probabilité prédéfinie utilisée lorsque l'on ne veut pas exprimer d'opinion sur la probabilité. 

**Ethnicity**

Terms present in Eng and missing in Fr:

- [x] Chinese 

"Les Chinois sont les différents individus ou groupes de personnes associés à la Chine (ou à la Grande Chine), en raison de leur ascendance, leur hérédité, leur ethnie, leur nationalité, leur citoyenneté, leur lieu de résidence ou d'autre affiliation."

Note: La description de ce terme est basée sur celle de DBPedia.

(manual translation from English version of DBpedia)

- [x] Indigenous/**Amérindiens** (only label title) 

- [x] Jamaican 

Jamaïcains

"Les Jamaïcains sont les citoyens de la Jamaïque et leurs descendants dans la diaspora jamaïcaine. La plupart des Jamaïcains sont d’ascendance africaine, avec des minorités moins nombreuses d’Européens, d’Indiens de l’Est, de Chinois, de métis et d’autres. La majeure partie de la diaspora jamaïcaine réside au Canada, aux États-Unis, au Panama et au Royaume-Uni et dans d'autres pays anglophones."

Note: La description de ce terme est basée sur celle de DBPedia.

(manual translation from English version of DBpedia)

- [x] Punjabi

Pendjabis 

Les Pendjabis (en pendjabi : پنجابی / ਪੰਜਾਬੀ) sont un groupe ethnolinguistique associé à la région du Pendjab, parlant le pendjabi, une langue indo-aryenne. Pendjab signifie littéralement « terre des cinq eaux » (du persan : panj (« cinq »), āb (« eaux »)). Cette région a été mentionnée chez les Grecs sous le nom de Pentapotamie20, qui fut traduit plus tard en persan par les conquérants turco-persans21 de l'Asie du Sud et qui seront plus connus durant l'Empire moghol. Le Pendjab est souvent qualifié de grenier à blé du Pakistan et de l'Inde. La coalescence de diverses tribus, castes et des habitants du Pendjab en une identité pendjabie plus large a commencé au début du xviiie siècle. Avant cela, le sentiment et l'idée d'une identité et d'une communauté ethnoculturelles pendjabies n'existaient pas, même si une majorité des communautés du Pendjab partageaient depuis longtemps des points communs linguistiques, culturels et ethniques. Traditionnellement, l'identité pendjabie est principalement linguistique, géographique et culturelle. Son identité est indépendante de l'origine historique ou de la région, et désigne ceux qui résident dans la région du Pendjab, ou se sentent associés avec ses habitants, et ceux qui considèrent le pendjabi comme leur langue maternelle. L'intégration et l'assimilation sont des éléments importants de la culture pendjabie, puisque l'identité pendjabie n'est pas basée uniquement sur des liens tribaux. Tous les Pendjabis partagent plus ou moins un même socle culturel.

Source: https://fr.wikipedia.org/wiki/Pendjabis
 
- [x] Sottish 

Écossais 

Les Écossais correspondent au peuple et à la nation qui occupent l'Écosse. Ils sont les descendants des anciens Pictes, Gaëls, avec des apports de Bretons insulaires, d'Angles, de Saxons et de Normands (Vikings norrois, danois et plus tard les Normands de France).

Source: https://fr.wikipedia.org/wiki/%C3%89cossais_(peuple)

- [x] West-Indian 

Antillais 

"La population [antillaise] est mixte et donc de provenance diverse. Composée majoritairement de noirs d'origines africaines et de métis comme à la Jamaïque ou en Haïti, elle comprend aussi des individus d'origine européenne, hindoue, arabe, juive. À noter un très faible pourcentage d'Asiatiques. Quelques rares survivants des premiers occupants de ces régions, les Amérindiens, y sont encore présents, comme les Caraïbes à l’île de la Dominique."
Note: La description de ce terme est basée sur celle de DBPedia.

Source: http://dbpedia.org/page/Antilles

**Gender**

Note: 
- [x] Non-binaire to be replaced by **queer** 
- [x] woman in Eng version: final dot missing in De Beauvoir's citation 

Terms present in Eng and missing in Fr:

- [x] black woman 

Femme noire  

`Une identité intersectionnelle qui résulte de la combinaison de "a le genre femme" et de "a une identité de race ou de couleur noire". Voir @@https://fr.wikipedia.org/wiki/Afrof%C3%A9minisme@@ et <![CDATA[<a href="#cwrc:b9eeccf9-9380-4341-99dc-a83f5ee32909">(Kimberlé Crenshaw, 1989)</a>]]>.`

- [x] undefined 

Genre indéterminé 

Indique que le genre de la personne n'est pas déterminé par elle·lui-même ou n'est pas indiqué dans la source.

**Geographic Heritage**

- [x] England 

Anglais 

Indique qu'un sujet s'identifie ou s'est vu assigner une identité anglaise par rapport à un endroit, généralement l'Angleterre.

**National Heritage**
- [x] Africain (missing instance title) 
> **Africain**

- [x] European 

indique l'identité ou l'étiquetage d'un sujet à l'héritage national européen. 

- [x] Jewish 

Juif

"Les Juifs (en hébreu : יְהוּדִים / yehoudim, en grec ancien : Ἰουδαῖοι / Ioudaĩoi, en latin : Iudaei, etc.) sont les membres d’un peuple lié à sa propre religion, le judaïsme, et au sens large du terme à une appartenance ethnique et religieuse."
Note: La description de ce terme est basée sur celle de DBPedia.

Source: http://dbpedia.org/page/Jews 

- [x] Mohawk

"Les Kanien'kehá:ka, autrefois dénommés Agniers en français mais aujourd'hui plus connus sous le nom anglais de Mohawks, sont l'une des Six-Nations iroquoises, lesquelles sont, d’ouest en est : les Tuscaroras, les Sénécas (Tsonnontouans), les Cayugas (Goyogoins), les Onondagas (Onontagués), les Oneidas (Onnéiouts) et les Mohawks (Agniers)."

Source: https://fr.wikipedia.org/wiki/Mohawks

- [x] West-Indian 

Antillais 

"La population [antillaise] est mixte et donc de provenance diverse. Composée majoritairement de noirs d'origines africaines et de métis comme à la Jamaïque ou en Haïti, elle comprend aussi des individus d'origine européenne, hindoue, arabe, juive. À noter un très faible pourcentage d'Asiatiques. Quelques rares survivants des premiers occupants de ces régions, les Amérindiens, y sont encore présents, comme les Caraïbes à l’île de la Dominique."

Note: La description de ce terme est basée sur celle de DBPedia.

Source: http://dbpedia.org/page/Antilles

**National Identity**

- [x] African (typo) 

Indique qu'un sujet s'identifie à ou s'est vu assigner une identité nationale **africaine.**

- [x] sephardic 

Séfarade 

Indique qu'un sujet s'identifie à ou s'est vu assigner une identité nationale sérafade.

- [x] hanover 

Hanovrien

Indique qu'un sujet s'identifie à ou s'est vu assigner une identité nationale hanovrienne. Voir @@https://fr.wikipedia.org/wiki/Hanovre@@. 

- [x] florentin

Florentin

Indique qu'un sujet s'identifie à ou s'est vu assigner une identité nationale florentine. 

- [x] anglo-Irish

Indique qu'un sujet s'identifie à ou s'est vu assigner une identité nationale anglo-irlandaise. 

- [x] anglo-Indian 

Indique qu'un sujet s'identifie à ou s'est vu assigner une identité nationale anglo-indienne. 

- [x] Saxon

Saxon

Indique qu'un sujet s'identifie à ou s'est vu assigner une identité nationale saxonne. Voir @@https://fr.wikipedia.org/wiki/Saxons@@.

**Political affilialtions** 
**Appartenances politiques** 

Missing definitions in French:

- [ ] anti-apartheid 

"L'opposition internationale contre l'apartheid concerne les actions menées par la communauté internationale contre la politique de ségrégation raciale mise en place en Afrique du Sud de 1948 à 1991. Cette opposition a commencé principalement à se manifester après le massacre de Sharpeville, intervenu le 23 mars 1960 dans le township de Vereeniging dans la province du Transvaal. Le 6 novembre 1962, la Résolution 1761 de l'ONU était adoptée Les émeutes de Soweto, le 16 juin 1976, feront 79 morts et 178 blessés." (DBpedia, 2017)

Note: La description de ce terme est basée sur celle de DBPedia.

Source: http://dbpedia.org/describe/?url=http%3A%2F%2Fdbpedia.org%2Fresource%2FForeign_relations_of_South_Africa_during_apartheid&sid=21999

- [ ] anti-boer

Opposition à la politique des Boers en Afrique du Sud. Voir https://fr.wikipedia.org/wiki/Guerre_des_Boers

- [ ] lutte contre les châtiments corporels

Lutte contre l'usage des châtiments corporels, notamment sur les personnes mineures. Voir @@https://fr.wikipedia.org/wiki/Ch%C3%A2timent_corporel#Controverses_sur_l'usage_du_ch%C3%A2timent_corporel@@. 

- [ ] anti-monarchisme 

"La critique de la monarchie peut se référer à la monarchie en tant que forme de gouvernement ou au cas particulier de tel ou tel État monarchique. Dans plusieurs de ces États, la critique de la royauté est ou a été limitée, voire pénalisée (délit de lèse-majesté). La monarchie et les principes du droit divin de la royauté ont été critiqués au XVIIIe siècle pour aboutir en France le 21 septembre 1792 à la proclamation de l'abolition de la royauté lors de la Révolution française et le 4 juillet 1776 à la déclaration d’indépendance à la suite de la révolution américaine. Ainsi, plusieurs gouvernements monarchiques ont été remplacés par des Républiques, alors que d'autres pays ont remplacé leur monarchie absolue par une monarchie constitutionnelle. Le cas inverse est possible (Restauration, Monarchie de Juillet, Second Empire, monarchie espagnole). Dans leur principe comme dans leur réalité, les systèmes monarchiques ne sont incompatibles ni avec l'exercice des droits démocratiques, ni avec aucune liberté individuelle. Au contraire, les exemples contemporains montrent que ces dernières sont majoritairement garanties dans les États monarchiques et bafouées sous des régimes non monarchiques.[non neutre] Pour les adversaires de la monarchie, le régime monarchique ne respecte pas certains principes reconnus par le droit international."

Note: La description de ce terme est basée sur celle de DBPedia.

Source: http://dbpedia.org/page/Criticism_of_monarchy

- [ ] opposition au suffrage universel

To modify: Anti-suffragisme 

"L'anti-suffragisme était un mouvement politique composé principalement de femmes, initié à la fin du 19ème siècle afin de lutter contre le droit de vote des femmes en Grande-Bretagne et aux Etats-Unis. Il était étroitement associé au "féminisme domestique", s'appuyant sur la conviction que les femmes pouvaient être libres en restant au foyer."

Note: La description de ce terme est basée sur celle de DBPedia. 

(manually translated) 

- [ ] anti-establishment

"L'opposition à l'Establishment est une position politique qui s'est développée dans la Grande-Bretagne du 19ème siècle contre les propositions libérales pour le démantèlement de l'Église d'Angleterre, ce qui impliquait la suppression du statut de l'Église anglicane en tant qu'Église d'Angleterre, d'Irlande et du Pays de Galles. L'Irlande (anglicane) a été démantelée en 1871. Au Pays de Galles, quatre diocèses de l'Église d'Angleterre ont été démantelés en 1920 et sont devenus l'Église du pays de Galles. De nos jours, le terme anglais "antidisestablishmentarianism" réfère également par analogie à toute opposition aux institutions, que ce soit le gouvernement, dans son entièreté ou en partie, ou à la société comme système établi."

Note: La description de ce terme est basée sur celle de DBPedia. 

(manually translated) 

- [ ] nationalisme anglais

"Le nationalisme anglais, qu'il faut distinguer du nationalisme britannique incarné par le British National Party (extrême droite), vise à défendre les intérêts de la nation anglaise dans le cadre du Royaume-Uni et de l'Union européenne."

Note: La description de ce terme est basée sur celle de DBPedia. 

Source: http://dbpedia.org/describe/?url=http%3A%2F%2Fdbpedia.org%2Fresource%2FEnglish_nationalism&sid=22100&urilookup=1

- [ ] chartisme 

"Le chartisme est un mouvement politique ouvrier qui se développa au Royaume-Uni au milieu du XIXe siècle, à la suite de l'adoption de la « Charte populaire » (anglais : People's Charter). En 1832, la réforme électorale (Reform Act) établit un système électoral censitaire, au détriment des classes populaires. La Charte populaire fut adoptée en 1838, à l'initiative de l'Association des travailleurs londoniens. Elle réclamait le suffrage universel masculin, un juste découpage des circonscriptions électorales, l'abolition de l'obligation d'être propriétaire pour être éligible, des élections législatives annuelles, le vote à bulletin secret et l'indemnité parlementaire. Le mouvement resta actif et organisé jusqu'en 1848 et donna lieu à l’apparition des mouvements coopératifs et des mouvements syndicaux. Il connut trois grandes phases : entre 1838 et le début de 1840 ; à l'été 1842 et entre février et août 1848, correspondant aux trois grandes pétitions signées par des millions de Britanniques et déposées (pour les deux premières) au Parlement qui refusa d'en tenir compte. Le terme « charte » renvoie à la Magna Carta de 1215."

Note: La description de ce terme est basée sur celle de DBPedia. 

Source: http://dbpedia.org/page/Chartism

- [ ] socialisme chrétien

To be changed: **Christianisme social** 

"Le Christianisme social est un mouvement apparu au xixe siècle dans les milieux protestants français confrontés à l'environnement social, économique et politique difficile né de la Révolution industrielle et aux conditions de vie misérables des populations ouvrières à cette époque. Partie intégrante de la gauche chrétienne, le mouvement existe toujours aujourd'hui."

Note: La description de ce terme est basée sur celle de Wikipédia. 

Source: https://fr.wikipedia.org/wiki/Christianisme_social

- [ ] mouvement libertaire 

- [ ] parti conservateur 
- [ ] démocrate 
- [ ] sécularisme 
- [ ] réforme vestimentaire
- [ ] réforme de l'éducation
- [ ] nationalisme égyptien
- [ ] droit des personnes âgées
- [ ] mouvement pour le libre-échange 
- [ ] nationalisme (typo?) allemand
- [ ] nationaliste grec
- [ ] unification de l'Inde/Indian unification 
- [ ] mouvement Irish rule 
- [ ] land reform
- [ ] multiracialisme 
- [ ] mouvement du clergé réfractaire
- [ ] nationalisme polonais 
- [ ] défense des pauvres 
- [ ] nonjurors movement 
- [ ] réforme Poor Law 
- [ ] réforme pénitentiaire 
- [ ] pro-américanisme 
- [ ] unionisme irlandais
- [ ] proesclavagisme 
- [ ] équité raciale 
- [ ] radicalisme 
- [ ] révolutionnaire
- [ ] sabbatarianisme 
- [ ] abolition de la prostitution
- [ ] réforme sociale
- [ ] républicanisme espagnol
- [ ] wigghisme
- [ ] womanisme 

Note:
- [ ] anti-bolchevism repeats anti-communism 
- [ ] substantive bolshevism (eng) and adjective bolsheviks (fr) 
- [ ] substantive maison de Hanovre (fr) and adjective Hanoverian (en) 
- [ ] substantive Gironde (fr) and adjective Girondin (en)
- [ ] droits de l'homme to be changed in droits humains 
- [ ] révolution sexuelle to be changed in réforme sexuelle 

**Race or Colour**

Terms present in Eng and missing in Fr:

- [ ] blackwoman 
- [ ] indian
- [ ] indigenous (instance title) 
- [ ] scottish (instance title) 

**Role**

- [ ] actor

**Social Class**

- [ ] slave or forced labourer 

**Text labels**

- [ ] queer identity 

Note:
- [x] the two "black" links in "black identity" send to the same instance 

## Object Properties 

To be treated separately, almost all of them are to be translated. 

Note: in _italics_  new correct French text to be transferred.

**Comment by alliyya** [comment]
Hey @jadepncr I've done the first chunk there that was available, I assume this ticket is still being updating.
Will tackle the translations from the spreadsheets tomorrow, but unassigning myself from this one for now.
Just assign me back when there's more for me to do :) (You can check on testing to reflect the changes by tomorrow morning)


WRT: _the two "black" links in "black identity" send to the same instance_
They don't send to the same instance but they are labelled the same, however _this is intentional_ -SB
But I modified my script that creates the links to include a hover that indicates the uri.

**Comment by SusanBrown** [comment]
Hi @jadepncr and @alliyya. This ticket hasn't been touched since August 2018. Is it superceded by the more recent strategy and should it therefore be closed?

**Comment by alliyya** [comment]
Correct, I will close this issue.
