### ISSUE TITLE
Review extracted triples

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#413]
includes cultural forms & family, friends, and intimate relations

(sent over by @alliyya and @GurjapSingh)

**Comment by alliyya** [comment]
Comment from duplicate ticket:
Extracted triples are in the Extraction folder https://drive.google.com/open?id=1U2UOYURMgNgJk_HVIEk6T4hY8WX-KeDi
attached a readme in the cf folder

Any questions about them, feel free to comment on this ticket
