### ISSUE TITLE
Creating predicates for Context, ex. hasContext, hasCulturalForm

### ISSUE THREAD

**Issue by alliyya** [cwrc/ontology#415]
Decision is need for whether or not we're creating the predicates for hasContext, hasEducationContext, hasCulturalFormContext...
Or if OA Covers this and these terms can be removed from the biography spreadsheet and hasEducation which is already in the ontology should be deprecated in favour of an term from OA

[Minutes from June 16th](https://docs.google.com/document/d/1YIQ70lAdnyZxTdghASd-xdSf3rB6qNzJNnab7M3xtfc/edit#heading=h.83r47ygj0qbb):
Big Question: Due to developments in our use of Open Annotation, do we still need hasCulturalForm?

**Comment by SusanBrown** [comment]
We are going to see whether we need them once we see how things are looking with just classing Events and Contexts. We think probably not. Putting this on back burner for now.
