### ISSUE TITLE
Other Life Event / BiographicalContext query

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#416]
copying and pasting from spreadsheet comment from Susan:

@joelacummings  and @DeborahStacey Could you respond to this query and see if you think we need to discuss it? Also FYI I've created contexts for Leisure and Society, Violence, and Wealth and I don't think these sheets need review b/c they have no subelements so @alliyya  will just put them in the ontology.

https://docs.google.com/spreadsheets/d/1L9V__vfiZ2hEZOsbVkMZ7-JlsToHHOuOKzbPIi-HTPs/edit#gid=513414138

**Comment by joelacummings** [comment]
Response added in the document and will paste here


> NB that this would change all the biographical contexts to be typed by this rather than simply as Context. I think that there is sense in being able to group things like this (and it is in fact built into the Atwood graffle we've been discussing re the triples), and then we could also have Writing/Literary Context, (and possibly also Historical Context, Social Context etc. for events) but I would appreciate feedback before we create it. 

Yes I think more specific context types is what we want here. Subclassing context is great way of grouping things.

**Comment by SusanBrown** [comment]
Excellent. Will define.
