### ISSUE TITLE
Scrape of degree: REG values and strings for those that don't have REG

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#419]

**Comment by SusanBrown** [comment]
Look for ontology to use in LOV and elsewhere.

**Comment by alliyya** [comment]
Total Count:151 unique
-------------------------------------
41 : ba
31 : ma
17 : phd
8 : ba honours
8 : ba in english
8 : first class honours ba
6 : bachelor of arts
6 : honours ba
5 : ba degree
4 : first class honours
4 : diploma in education
4 : honours ba in english
3 : ba (honours)
3 : diploma
3 : ba in english literature
3 : bsc
3 : l.l.a. (lady literate in the arts)
2 : teaching diploma
2 : first class ba
2 : ba in history
2 : school certificate
2 : ba in english language and literature
2 : ba in english and history
2 : ba honours degree
2 : first class degree
2 : ma in english literature
2 : degree in law
1 : agrégation
1 : bachelor of arts with honours in english
1 : higher cambridge certificate
1 : ba first class honours in english
1 : chancellor's diploma
1 : teaching certificate,, first class
1 : elementary teacher's certificate
1 : b.sc. (with honours)
1 : titles of pandita (the feminine of pundit, which recognizes one skilled in sanskrit) and sarasvati
1 : ba (hons) in english language and literature
1 : in may 1898, after completing a latin requirement, gs graduated magna cum laude in philosophy from radcliffe college. she was now fully qualified for admission to johns hopkins.
1 : first class ba in english
1 : diploma in social work
1 : honours ba in greats
1 : mlitt
1 : 2:2 ba
1 : bsc in physics
1 : ma in english.
1 : doctorate
1 : ma in philosophy and literature
1 : mb medical degree
1 : diploma in journalism
1 : doctor of medicine
1 : certificate in the exam for women
1 : university certificate
1 : elementary school teachers' certificate
1 : teacher's certificate
1 : aegrotat (an unclassed degree allowed in case of illness)
1 : ba in english with first class honours
1 : md
1 : ba honours in english
1 : degree with first class honours
1 : diploma of education
1 : degree in advertising
1 : ba in drama and theatre arts
1 : cambridge certificate
1 : diploma in literature
1 : dphil
1 : dsc
1 : msc
1 : higher school certificate
1 : ma in classics
1 : diploma in school counselling
1 : certificat d'études françaises, 1er degré
1 : third class honours
1 : master mariner's certificate
1 : ba degee
1 : usa teaching certificate
1 : ba honours in medieval and modern french
1 : of a second class honours ba in english language and literature
1 : class three ba
1 : ba in arts
1 : honours ba degree
1 : classical tripos
1 : mphil in medieval literature
1 : certificate
1 : diploma in agriculture
1 : postgraduate certificate
1 : ba honours degree in english was a third class
1 : ba honours, second class
1 : ladies literary course
1 : teaching certificate, first class
1 : ba in ppe
1 : bachelor of arts degree (at pass level only)
1 : honorary ma
1 : master's degree
1 : certificate in social science
1 : ma (a first degree in scotland)
1 : ab degree
1 : doctor of divinity degree
1 : bachelor of journalism
1 : honorary doctorate of divinity
1 : education diploma
1 : ma in psychology
1 : postgraduate certificate in education, english as a second language
1 : bachelor
1 : teaching certificate
1 : ma in english
1 : postgraduate degree in teaching
1 : phd in philosophy
1 : ba, second class, in english language and literature
1 : earned but not awarded
1 : degree
1 : md degree
1 : ba in classics, class ii
1 : masters degree
1 : diplome d'etudes de civilisation française
1 : honours ba in french
1 : ba in modern history
1 : ba (second class honours)
1 : law degree
1 : second class honours ba
1 : phd in linguistics
1 : ba pass degree
1 : aegrotat degree
1 : second class teaching certificate
1 : double first honours ba
1 : ba honours in history
1 : two year degree
1 : b. litt.
1 : master's degree in public health
1 : honours ba in classics, first class
1 : ph.d.
1 : second class honours
1 : cambridge ba
1 : doctor of philosophy
1 : third class degree (in history)
1 : postgraduate diploma in writing for the stage
1 : higher national certificate
1 : ba in cultural anthropology
1 : ma degree
1 : diploma in psychopathology
1 : ba honours, third class
1 : second class honours degree
1 : d.phil.
1 : post graduate certificate of education
1 : ma in canadian literature
1 : blitt
1 : post graduate degree in theatre
1 : honours ba, second class,
1 : second class degree
1 : first in her ba
1 : certificate in the theory and practice of teaching
1 : teacher's diploma

I've added a spreadsheet for education scrapes with these in it in spreadsheet folder
https://docs.google.com/spreadsheets/d/1QrbfyP3x39LJdLj76T-ibeIcy5mwmDJM4bEgLWGUdYk/edit#gid=0

**Comment by SusanBrown** [comment]
Thanks. Can you easily dump these into a spreadsheet in the spreadsheets folder?


On Jul 23, 2018, at 11:23 AM, Alliyya Mo <notifications@github.com<mailto:notifications@github.com>> wrote:


Note some of these may include a name, orgname, school or subjects of study tag

**Comment by alliyya** [comment]
The subtags?
