### ISSUE TITLE
Scrape of literary RRECOGNITIONNAME: REG values and strings for those that don't have REG

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#420]

**Comment by SusanBrown** [comment]
In Writing docs not Bio docs

**Comment by alliyya** [comment]
Is this called something else in the writing docs? Like RECOGNITIONNAME under reception?

**Comment by SusanBrown** [comment]
Yes sorry RRECOGNITIONNAME — pls revise!

**Comment by alliyya** [comment]
Added to Writing Scrape spreadsheet https://docs.google.com/spreadsheets/d/12WpB_XHGYcyztDVnq8O9k3LE-jlkSeGC6kBwIpRMvu8/edit#gid=0
Total Count:834
-------------------------------------
33 : commander of the order of the british empire
30 : frsl
28 : civil list pension
26 : honorary dlitt
26 : booker prize
22 : prix femina
20 : fellow of the royal society of literature
18 : book society choice
17 : dame commander of the order of the british empire
16 : poetry book society recommendation
15 : officer of the order of the british empire
13 : james tait black memorial prize
13 : poetry book society choice
12 : shortlisted for the booker prize
12 : pulitzer prize
10 : cholmondeley award
9 : nobel prize for literature
8 : scottish arts council book award
7 : the poetry archive
7 : somerset maugham award
7 : carnegie medal
7 : queen's gold medal for poetry
7 : orange prize
6 : hawthornden prize
6 : book of the month club choice
6 : honorary fellow
6 : short listed for the booker prize
6 : guggenheim fellowship
5 : whitbread poetry award
5 : governor general's award
5 : poet laureate
5 : national book award
5 : whitbread prize
5 : dlitt
5 : t. s. eliot prize
5 : guardian fiction prize
5 : honorary degrees
5 : honorary degree
4 : nobel prize in literature
4 : book of the month
4 : eric gregory award
4 : companion of literature
4 : forward poetry prize
4 : book society recommendation
4 : honorary ll.d
4 : alice hunt bartlett award
4 : national poetry competition
4 : james tait black prize
4 : academy award
4 : forward prize
4 : yorkshire post book of the year award
4 : fawcett prize
4 : companion of honour
4 : o. henry prize
4 : dame of the british empire
4 : olivier award
3 : arts council award
3 : writer in residence
3 : w. h. smith award
3 : writers' guild award
3 : companion of the british empire
3 : obe
3 : george devine award
3 : honorary doctorate
3 : book of the month club selection
3 : silver dagger
3 : member
3 : cbe (commander of the order of the british empire)
3 : national book critics circle award
3 : whitbread award
3 : winifred holtby memorial prize
3 : harriet monroe memorial prize
3 : gold dagger award
3 : susan smith blackburn prize
3 : presidential medal of freedom
3 : order of the british empire
3 : the poetry archive,
2 : doctorate of letters
2 : whitbread prize for children's literature
2 : bollingen prize for poetry
2 : honorary d.litt.
2 : edgar allan poe award
2 : orange prize for fiction
2 : society of authors travelling scholarship
2 : melrose prize
2 : golden pen award
2 : order of merit
2 : pulitzer prize for fiction
2 : katherine mansfield menton prize
2 : first prize in the national poetry competition
2 : arts council bursary
2 : new york drama critics circle award
2 : richard hillary memorial prize
2 : frsc
2 : shortlisted for the orange prize
2 : sunday express book of the year
2 : prix goncourt
2 : los angeles times book prize
2 : mystery writers of america award
2 : oscar blumenthal prize
2 : shakespeare prize
2 : mythopoeic fantasy award
2 : neil gunn international fellowship
2 : lambda book award in lesbian poetry
2 : john llewellyn rhys memorial prize
2 : british arts council bursary
2 : pen/macmillan silver pen award
2 : john llewellyn rhys prize
2 : regina medal
2 : sony radio award
2 : age book of the year award
2 : scottish arts council award
2 : obie
2 : cholmondeley award for poetry
2 : writers guild award
2 : testimonial
2 : isabel sissons canadian children's story award
2 : pat lowther award
2 : commonwealth poetry prize
2 : booker prize nomination
2 : evening standard award
2 : angel literary award
2 : a. c. benson silver medal
2 : book of the month club
2 : fellow of the royal geographical society
2 : cheltenham festival prize
2 : bess hokin prize
2 : w. h. smith prize
2 : commandeur de l'ordre des arts et des lettres
2 : honorary fellowship
2 : whitbread award for fiction
2 : honorary member of the american academy of arts and letters
2 : silver dagger award
2 : jane harrison lecture
2 : clit
2 : walter scott prize
2 : david cohen british literature prize
2 : harvey darton prize
2 : e. m. forster award
2 : signal poetry award
2 : visiting professor
1 : emeritus fellowship
1 : whitbread children's book of the year
1 : prizes
1 : e. j. pratt medal for poetry
1 : poetry book society recommended translation
1 : membership of the royal irish academy
1 : dd
1 : forward prize for best first poetry collection
1 : order of canada
1 : tony godwin award
1 : nominated for a tony
1 : william e. heinemann award
1 : giles cooper award
1 : moravia prize for literature
1 : betty trask award.
1 : tanner lecturer at yale university
1 : members of aosdana
1 : guardian fiction award
1 : saltire first book of the year
1 : runner up for the casa de las americas prize
1 : diamond dagger
1 : darwin now
1 : vera bell prize
1 : honorary scholar at the radcliffe institute
1 : w. h. smith literary award
1 : travel grant for $7,000 from the chapelbrook foundation
1 : march biography award
1 : memorial fountain
1 : shortlisted for the whitbread award
1 : dylan thomas short story prize
1 : messenger prize
1 : nominated for the booker prize
1 : glass slipper award
1 : lewis carroll shelf award
1 : enid mcleod literary award
1 : honorary member of the irish literary society
1 : grandmaster award
1 : list of the top ten adult titles
1 : playwright in residence
1 : knighthood
1 : hans christian andersen award
1 : major hopgood award
1 : nominated as professor of poetry at oxford
1 : signal award
1 : award of the british academy
1 : oscar for best screenplay
1 : royal bounty
1 : member of the order of the british empire
1 : whitbread poetry prize
1 : bridport poetry prize
1 : metro goldwyn mayer prize
1 : hundred plays of the century
1 : somerset maugham prize
1 : saoi
1 : arts council national book award
1 : fipa d'argent
1 : british academy of film and television arts
1 : booker mcconnell prize nomination
1 : saltire scottish book of the year award
1 : tma martini award
1 : royal bounty fund
1 : poetry book society special commendation
1 : arts council bursaries
1 : stig dagerman award
1 : drama critics circle award for best foreign play
1 : top of the pops
1 : bhubanmohini dasi medal of calcutta university
1 : honorary member
1 : all london playwrights' award
1 : canadian children's book centre's best books for kids and teens
1 : benson medal
1 : dutton's book of the month
1 : eric gregory prize
1 : southern arts translation bursary
1 : charles henry foyle new play award
1 : list of women of the millennium
1 : saltire society scottish first book of the year award
1 : london magazine prize for prose
1 : honorary fellow of queen mary and westfield college, london university
1 : american book of the month club choice
1 : denyse clairouin prize
1 : deo gloria award
1 : whitbread literary award
1 : regional commonwealth writers' prize (eurasia)
1 : king of prussia's gold medal for science
1 : australian writers guild awgie award for fiction
1 : professorship of poetry,, oxford university
1 : irish post award
1 : book society
1 : silver inkstand
1 : award from the arts council
1 : gold pen award
1 : prix femina américain
1 : forward award
1 : honorary degree of doctor of letters
1 : eleanor rathbone building
1 : crawshay prize for nonfiction
1 : freedom of the city of leeds
1 : vera brittain award
1 : frsa
1 : northern rock foundation writer's award
1 : honorary mlitt.
1 : commander of order of the british empire
1 : macarthur foundation grant
1 : commander of the british empire
1 : michael braude award for light verse
1 : special award
1 : academy awards
1 : honorary doctorates
1 : wait honorary doctorate of technology
1 : rathbone house
1 : associate fellow
1 : wingate scholarship
1 : unches held by the queen at buckingham palace to celebrate the achievements of women
1 : ophar's book club choice
1 : arts council fellowship
1 : j. t. grein prize
1 : robert frost silver medal for lifetime achievement in poetry
1 : crime writers' association cartier diamond dagger
1 : litt.d
1 : popular culture association award
1 : award from the american academy of arts and letters
1 : nominated for the list of a hundred great black britons
1 : lex award
1 : paxton prize
1 : citizen of the year in the arts and culture and entertainment
1 : society of authors scholarship
1 : chosen by the book of the month club
1 : honorary degree from the university of nebraska in lincoln
1 : welsh arts council prize
1 : tma best new play
1 : list of best novels of our time
1 : cholmondeley award for literature
1 : secondary book of the month
1 : mythopoeic society prize
1 : scroll
1 : chevalier of the légion d'honneur
1 : partisan review fellowship
1 : royal asiatic society's burton memorial award
1 : sonning prize for european culture
1 : gold medal of royal society of literature
1 : charles taylor prize for literary non fiction
1 : observer as one of the best children's books of the year
1 : edgar
1 : grand prix de littérature policière
1 : doctor of divinity degree
1 : lady violet astor trophy
1 : harkness fellowship
1 : crime writers' association contest sponsored by ellery queen mystery magazine
1 : tait black memorial
1 : governor general's medal
1 : makar or poet laureate of scotland
1 : book guild
1 : grand cross of the order of the british empire
1 : back memorial grant
1 : honorary degree from her old university, exeter
1 : lifetime achievement award
1 : david higham prize
1 : research award from the leverhulme trust
1 : poet laureat of hope end
1 : emmy
1 : writers' guild prize for fiction
1 : love lyric competition in the bi monthly poetry review
1 : obie award
1 : honor book in the children's spring festival put on by book world
1 : gold medal of the highland society
1 : honorary degrees before, in 1937, accepting one from new york university
1 : sarah orne jewett scholarship fund
1 : la médaille de la ville de paris
1 : international dublin impac award
1 : kelus poetry prize
1 : honorary degree of d. litt.
1 : medal of honour for literature
1 : book society choice.186
1 : corresponding membership of the medieval academy of america
1 : typhoo tea handwriting competition
1 : georgette heyer award for historical fiction
1 : eileen anderson central television award for best play
1 : lenore marshall/nation poetry prize
1 : commonwealth writer's prize
1 : google doodle
1 : fellow of the university of wales at cardiff
1 : nestlé smarties prize
1 : rosemary crawshay prize, british academy
1 : best drama
1 : sunday times young writers of the year award
1 : short listed for the orange prize for fiction
1 : getty scholar
1 : best black writer in the world
1 : third place in the arvon/observer poetry competition
1 : messenger memorial prize
1 : grinzane cavour prize
1 : literary lion award
1 : bafta (british academy of film and television arts) award
1 : commonwealth writers' prize
1 : robert pitman award
1 : wales book of the year prize in english
1 : the order of the companions of honour
1 : guggenheim awards
1 : shortlisted for scottish writer of the year award
1 : prix du meilleur livre étranger
1 : horn book list
1 : guardian children's book prize
1 : library journal's bestseller list
1 : ingersoll t. s. eliot award
1 : prix des critiques for best theatrical work
1 : sheikh zayed book award
1 : companion of the order of the british empire
1 : junior book club book of the month
1 : one hundred plays of the century
1 : canadian authors' association award.
1 : con weickhardt prize for an unpublished novel
1 : eleanor rathbone memorial lecture
1 : lessing prize
1 : use as a sunday school prize
1 : poetry magazine award
1 : french légion d'honneur
1 : joint winner of the betty trask award
1 : queen's medal for poetry
1 : society of film and television arts award
1 : houghton mifflin poetry prize
1 : smarties prize
1 : scottish book award
1 : poetry ireland choice
1 : académie goncourt
1 : selected by the literary guild
1 : reith lecturer for the bbc
1 : badge of honour
1 : contest run by the weekend observer
1 : first prize f. n. a. c. la meilleur reçueil des nouvelles etrangères
1 : sunday express book of the year award
1 : contender for the miles franklin prize
1 : arvon/observer international poetry competition
1 : german federal republic shakespeare prize
1 : poetry book society selection
1 : membership of the royal society of literature
1 : mckitterick prize
1 : despite the note attached mentioning her permission, gallaher was furious at the changes. she wrote to the editor of the morning and evening mail complaining that she had not given permission for her work to be altered thus.58
1 : governor general's award for poetry
1 : offer of the order of merit
1 : nominated for the rainforest of reading award
1 : guardian award for children's fiction
1 : british book awards chose joanne rowling as author of the year
1 : astronomical society awarded its gold medal
1 : christopher ewart briggs memorial prize
1 : nominated for the pulitzer prize.
1 : honorary fellow of somerville college, oxford
1 : prix italia
1 : selection of the american book of the month club
1 : hawthornden prize for poetry
1 : arts foundation prize
1 : nominated for a national book critics circle award
1 : poetry business competition
1 : j. r. ackerley prize
1 : nominated for the national book award
1 : orwell prizes
1 : w. h. smith library award
1 : chapelbrook award
1 : american academy of arts and letters
1 : jewish quarterly literary prize for fiction
1 : sigmund freud prize
1 : runner up for a sony radio award
1 : visiting fellow
1 : london arts board new writer award
1 : officier de l'instruction publique de france
1 : a. c. benson medal of the royal society of literature
1 : international impac literary award
1 : frhs
1 : clitt
1 : honorary membership in the royal astronomical society
1 : hand of swift in marriage
1 : yorkshire post novel of the year award
1 : william dean howells medal
1 : author of the year at the 2003 british book awards
1 : prix caumont la force
1 : chevalier dans l'ordre des arts et des lettres
1 : honorary degree from harvard university
1 : irish american institute award for literature
1 : galaxy book of the year award
1 : patrick kavanagh award
1 : dylan thomas award
1 : gold medal of the royal antwerp geographical society
1 : jock campbell award
1 : eleanor farjeon award
1 : whitbread prize for fiction
1 : légion d'honneur
1 : giles cooper award for best radio play
1 : doctor of the university
1 : authors' club first novel award
1 : beta sigma phi first novel award
1 : katherine mansfield award
1 : dingle international award
1 : membership of the societé européene de culture
1 : v. s. pritchett memorial prize
1 : national book critics circle award for fiction
1 : d.lit
1 : w. h. smith children's poetry prize
1 : evening standard best play award
1 : augie
1 : bulwer lytton fiction contest
1 : annual poetry prize given by the sunday referee.
1 : silver musgrave medal
1 : musgrave gold medal
1 : fellow of the royal society of arts
1 : honorary doctor of arts
1 : royal red cross
1 : rooney prize (dublin)
1 : american literary society award
1 : baudelaire prize
1 : cardiff international poetry prize
1 : major arts council literature award
1 : crime writers association silver dagger
1 : visiting professor of english
1 : british crime writers association silver dagger award
1 : southern arts literary prize
1 : fawcett book prize
1 : world book choice
1 : second prize at the cheltenham festival
1 : the freedom of the city of london
1 : an annual pension of ¥20 from the royal bounty fund
1 : book of the year
1 : yale younger poets competition
1 : allied irish banks literary award
1 : bbc radio scotland poetry prize
1 : nominated for a writers' guild award
1 : senior citizen of the year
1 : irish american literary award
1 : norman washington manley foundation award for excellence
1 : heinemann prize for poetry
1 : whitbread children's book award
1 : prize from toronto publisher campbell and son as the best sunday school fiction for children
1 : duniv
1 : award for best actress in this film at the berlin film festival
1 : eichelberger prize
1 : prix quadriennale ville de geneve
1 : irish academy of letters
1 : best british writer's award
1 : elected a fellow of the royal society of literature.
1 : honorary dlitt degree
1 : los angeles times book award for fiction
1 : wellcome trust book prize
1 : w. somerset maugham award
1 : australia's living treasures
1 : katherine mansfield prize
1 : english centre of international pen award
1 : mondello prize
1 : centenary medal of the institute of jamaica
1 : chevalier de la légion d'honneur
1 : irish times/aer lingus international fiction prize
1 : guinness award
1 : poets' prize
1 : sahitya akademi
1 : oxford diocesan prize
1 : became the first woman fellow of king's college, london
1 : best novel
1 : book of the month by the daily mail
1 : national medal of the arts
1 : international impac dublin literary award
1 : most promising playwright
1 : eichelberger gold medal
1 : sunday times award for literary excellence
1 : shortlisted for the scottish saltire literary award
1 : honorary dlitt from exeter university
1 : hennessey literary award for short stories
1 : silver medal from the inter colonial exhibition
1 : president of the english association
1 : runner up for the pye radio award
1 : britannica australia award for literature
1 : joint book of the month club choice
1 : first prize in the peterloo poetry competition
1 : american national book critics fiction prize
1 : costa poetry award
1 : nominated for a national book award
1 : royal literary fund award
1 : geoffrey faber memorial award
1 : welsh book of the year
1 : scottish book of the year award
1 : w. h. smith and son award
1 : arts council bursary award
1 : pulitzer poetry prize
1 : one of 20 best of young british novelists
1 : scottish arts council
1 : membership in the royal scottish geographical society
1 : runner up for the booker prize
1 : chair of the society of authors
1 : honorary doctorate from sheffield hallam university
1 : appointed chancellor of the university of salford
1 : atlantic monthly prize
1 : australian literary society's gold medal
1 : cheltenham festival literary prize
1 : croix st louis
1 : fsa
1 : civil list
1 : american blue ribbon award
1 : black penmanship awards
1 : whitbread literary award for fiction
1 : shortlisted for the whitbread prize
1 : lannan literary award for poetry
1 : james black tait
1 : mind book of the year
1 : poet laureateship, which was offered
1 : order of st sava
1 : shortlisted for the forward poetry prize for best collection
1 : arise peace award
1 : crime writers' association ellis peters historical dagger
1 : heinemann prize
1 : giller prize
1 : nominated for a sony award
1 : centenary medal from the institute of jamaica
1 : literary guild book selection
1 : sean macbride peace prize
1 : scotland's national poet, with the title makar
1 : time out fringe award
1 : david higham prize for fiction
1 : children's laureate
1 : the poetry archive to offer online.
1 : nashville prize
1 : the guardian's christmas list
1 : edinburgh festival fringe first
1 : my book of the year
1 : james tait black memorial book prize
1 : daughter of mark twain award
1 : dame
1 : silver medal and $1,000 from the american academy of arts and letters
1 : cbe
1 : irish times/aer lingus irish literature prize for poetry
1 : patrick white literary award
1 : sir percy sykes medal
1 : officer of the order of australia
1 : palmes de l'académie française
1 : neustadt international prize for literature
1 : guggenheim fellowships
1 : samuel beckett award for television drama
1 : ala notable book
1 : cheltenham festival award
1 : miles franklin award
1 : kingsley amis award
1 : carnegie
1 : john oliver hobbes scholarship in english literature
1 : australian literary society gold medal award
1 : commonwealth writers first book prize
1 : lannan literary award
1 : oscar for best adapted screenplay
1 : sonning prize for contributions to european civilization
1 : honorary dlitt.
1 : shortlisted for arts council of wales welsh book of the year prize
1 : poetry archive
1 : penguin writers fellow at the british library
1 : honorary ma from the university of wales
1 : chevalier de l'ordre des arts et des lettres
1 : post of poet laureate
1 : nobel prize
1 : ellery queen's mystery magazine contest
1 : selection of the best young british novelists
1 : frederick niven literary award
1 : heywood hill lifetime award
1 : shortlisted for the kirkus prize (young readers' literature)
1 : young writer of the year
1 : author of the year award
1 : fellowship at princeton's institute for advanced study
1 : silver pen for the children's book of the year
1 : alberto moravia award
1 : clarendon lecturer at oxford
1 : eric gregory travelling scholarship
1 : honorary d.litt. degree
1 : ellery queen award
1 : yorkshire post prize
1 : s. t. dupont golden pen award
1 : fancied as a candidate for poet laureate
1 : international dublin impac literary award
1 : literary guild society
1 : katharine briggs memorial prize
1 : honorary member of the dramatic authors' society
1 : nominated both for the philip k dick award for science fiction and for the hawthornden prize
1 : first prize in a short story contest offered by hearth and home
1 : bodley medal
1 : radio 3 short story award
1 : literature board of the australia council senior fellowship
1 : selection of the literary guild of america
1 : shortlisted for the t. s. eliot prize
1 : cheltenham literature festival poetry competition prize
1 : john llewellyn rees memorial prize
1 : society of west end theatre award
1 : fellow at the center for advanced studies, wesleyan university
1 : acton prize
1 : guardian prize
1 : la times fiction prize
1 : silver medal of the institute of jamaica
1 : national poet of wales
1 : mystery writers of america edgar award
1 : sound stage radio drama special prize
1 : daisy miller prize
1 : shortlisted for the man booker prize
1 : book of the year by the times literary supplement
1 : pink paper play of the year
1 : f. g. bressani literary prize
1 : union league civic prize
1 : dutton mystery prize
1 : lippincott award
1 : m. d. zabel prize
1 : new zealand national book award
1 : short listed both for the orange prize
1 : golden gate
1 : best entertainment drama award
1 : london theatre critics award
1 : bass ireland award for literature
1 : burton medal
1 : london evening standard award
1 : new south wales premier's literary award
1 : padma sri award
1 : best film in the national film award contest in india
1 : honorary doctorate of letters
1 : south west arts literature award
1 : life peerage,
1 : ch
1 : runner up in its first atalanta scholarship competition
1 : mbe
1 : gregory medal
1 : robert frost medal
1 : shortlisted for the orange prize for fiction
1 : betty trask award
1 : darmstadt award
1 : bbc national short story award
1 : prafulla sarkar memorial ananda prize
1 : publishing for people award
1 : book of the year by the tablet
1 : honorary doctorate from oxford university
1 : certificate of merit
1 : hannah arendt prize
1 : ace (american council on education) award
1 : sir walter scott centenary prize
1 : booker mcconnell prize
1 : heslop gold medal
1 : d.litt. degree
1 : critics' choice
1 : honoray ma
1 : tom gallon award
1 : om
1 : frank o'connor short story award
1 : book league
1 : booker listing
1 : doubleday crime club's book of the month
1 : dial award
1 : mgm award
1 : prudence farmer prize
1 : mellon professor at the university of pittsburgh
1 : national book foundation medal for distinguished contribution to american letters
1 : fellows of the royal society of literature
1 : honorary fellow, downing college, cambridge
1 : life membership of the society of authors
1 : burney centre
1 : royal garden party invitation
1 : smarties book prize
1 : whitbread award for best first novel
1 : guinness book of world records
1 : travelling prize of the society of authors
1 : phoenix award
1 : poets' corner in westminster abbey
1 : order of manitoba
1 : eleanor rathbone chair of social science
1 : whitbread first novel award
1 : arts council translation prize
1 : member of the british empire
1 : shortlisted for the whitbread poetry award
1 : momart fellowship
1 : laurence olivier best fringe play
1 : welsh arts council award
1 : commonwealth writer's prize, eurasia
1 : mcvitie's prize
1 : created a baronet
1 : winifred holtby prize
1 : founding member of the newly formed screen writers guild.
1 : jewish chronicle book prize
1 : frances ridley havergal church missionary society memorial fund
1 : percy sykes medal
1 : eileen atkinson central television drama award
1 : short listed for the t. s. eliot prize
1 : order of commendatore
1 : whitbread novel award
1 : commandeur de l'ordre des arts et lettres
1 : long listed for the booker
1 : obe (order of the british empire)
1 : shortlistings for the booker prize
1 : oscar
1 : italia prize
1 : prize offered by campbell and son for the best sunday school fiction for children
1 : honorary doctorate from cambridge university
1 : short listed for the orange prize
1 : tinbergen professor
1 : best new play
1 : neil gunn fellowship
1 : annual gay news literary award
1 : o. henry awards
1 : nominated for the prix italia
1 : fellow of queen's college for women
1 : american booksellers' association award
1 : third prize in the competition, which had been organised by the observer
1 : wilfred owen prize
1 : life peerage
1 : booker prize shortlist
1 : wolfson history prize
1 : writer's award
1 : honorary fellow at timothy dwight college, yale university, new haven, connecticut
1 : fellow
1 : boardman tasker award for mountain literature
1 : california state treasure
1 : national academy of letters
1 : southern arts literature prize
1 : long listed for the orange prize
1 : cholmondeley
1 : honorary membership of the british mountaineering council
1 : young journalist award
1 : the daily telegraph's books of the week
1 : royal television society
1 : award from the society of authors
1 : anisfield wolf award
1 : honorary membership in the royal irish academy
1 : cbe (commander of the british empire)
1 : heywood hill literary prize
1 : arts council of great britain national book award for genre fiction
1 : etna taormina prize
1 : book of the year by the sunday express
1 : victoria gold medal
1 : haim greenberg literary award
1 : abbey's prize for new playwrights
1 : cheltenham prize
1 : humanities scholar 2005
1 : shortlisted for both the orange prize and the man booker prize
1 : new fiction society choice
1 : fellow of the royal society of edinburgh
1 : book society's choice
1 : selection by the book of the month club
1 : grace thayer bradley award
1 : senior resident fellow
1 : honorary littd
1 : eric gregory trust award
1 : national poetry society competition prize
1 : travelling scholarship from the american academy of arts and letters
1 : prix de la jeunesse étranger
1 : award at the cannes film festival
1 : whitney j. oakes fellow at princeton university
1 : order of australia
1 : international emmy award
1 : c. day lewis authors' fellowship
1 : annual pension of a hundred pounds on the civil list
1 : sarkar memorial ananda prize
1 : makar of glasgow
1 : geoffrey faber award
1 : fellow of manchester polytechnic
1 : eisteddfod competition
1 : poetry prize at highgate school
1 : cross pro ecclesia et pontifice
1 : costa
1 : somerville college ppe prize
1 : guest of honour at the annual dinner of women writers club of dublin
1 : thames tv bursary
1 : mail on sunday/john llewellyn rhys prize
1 : mary webb society
1 : william whitehead award of the gay and lesbian publishing triangle for lifetime achievement in letters
1 : jewish quarterly wingate literary prize
1 : irish american cultural award
1 : d. h. lawrence fellowship
1 : best young british novelists
1 : mystery writers of america grand master award
1 : signal poetry prize
1 : grand cross of the légion d'honneur
1 : erotica award
1 : festival of wellington poetry award
1 : short listed for a belfast city arts award
1 : distinguished alumni award
1 : los angeles times book award
1 : nominated for the nobel prize
1 : ocm bocas prize for non fiction
1 : committee of the royal literary fund
1 : austrian state prize for european literature
1 : deynse clarouin translation prize
1 : short listed for the sunday express book of the year award
1 : pinter prize
1 : irish arts council macauley fellowship
1 : memorial
1 : prix médicis
1 : shortlisted for the carnegie medal
1 : poetry book society
1 : shortlisted for the romantic novelists' association award
1 : woman of the century
1 : honorary degrees include those from the university of western ontario, 1995, harvard, the university of toronto, and the university of sofia
1 : c. day lewis fellowship
1 : top 100 in the bbc's the big read poll
1 : charleston chichester award
1 : david cohen british literature award
1 : gold medal of the american academy of arts and letters
1 : nominated for the booker mcconnell prize
1 : officier de l'ordre des arts et des lettres
