### ISSUE TITLE
Reviewing and Revising skos:altLabels

### ISSUE THREAD

**Issue by alliyya** [cwrc/ontology#424]
Post first pass of extraction
Some altlabels don't fit their term and are too general to make assumptions about them being equivalent terms for extraction. 

After this review, attempt extraction and review missed terms.

**Comment by lemaka** [comment]
Does this ticket need more information before action can be taken, @alliyya ?

**Comment by alliyya** [comment]
altLabels also should be reviewed to see if some should be more appropriately hiddenLabels.

**Comment by JasmineDW** [comment]
hiddenLabel exists for terms in the rdf file now. Closing this issue.
