### ISSUE TITLE
Add to persona definition

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#429]
Add the following:

" This definition is indebted to the Text Encoding Initiative's definition of the "persona" element. See @@http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-persona.html@@. "

**Comment by SusanBrown** [comment]
Note that I tried to do this myself but could not find the persona definition in cwrc.ttl which seemed very odd. Any explanation?

**Comment by alliyya** [comment]
cwrc.rdf is the file you'd like to edit to make changes.
