### ISSUE TITLE
French CWRC Preamble to transfer to code 

### ISSUE THREAD

**Issue by jadepncr** [cwrc/ontology#431]
Hi @alliyya, French version of the CWRC preamble ready to be transferred. 

[Available on this google doc](https://docs.google.com/document/d/1AzfRmXsNMxEBONkAeBCNpSHkNDMfYMJ-MnD7hDChxys/edit?usp=sharing)

I tried to keep the code but there may be some typos.

**Comment by alliyya** [comment]
Hey @jadepncr I noticed that in your revision was missing the section on [Has Functional Relation](http://sparql.cwrc.ca/testing/cwrc-preamble-EN.html#functionallyRelates).
Your translations will be visible on http://sparql.cwrc.ca/testing/cwrc-preamble-FR.html in about 30 min if you want to take a glance and make sure everything was inputted the way you intended :)
Thanks!

**Comment by SusanBrown** [comment]
:). Thanks both of you!

Sent from my phone

On Aug 8, 2018, at 6:06 PM, Alliyya Mo <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @jadepncr<https://github.com/jadepncr> I noticed that in your revision was missing the section on Has Functional Relation<http://sparql.cwrc.ca/testing/cwrc-preamble-EN.html#functionallyRelates>.
Your translations will be visible on http://sparql.cwrc.ca/testing/cwrc-preamble-FR.html in about 30 min if you want to take a glance and make sure everything was inputted the way you intended :)
Thanks!

**Comment by alliyya** [comment]
Still missing section on Has Functional Relation in french translation
http://sparql.cwrc.ca/testing/cwrc-preamble-EN.html#functionallyRelates

should be right after this section.
http://sparql.cwrc.ca/testing/cwrc-preamble-FR.html#changeSets
