### ISSUE TITLE
Provide definitions for hasTimeCertainty, punctiveTime, intervalTime

### ISSUE THREAD

**Issue by alliyya** [cwrc/ontology#435]

**Comment by SusanBrown** [comment]
Punctive time: A indication of a point or location in time. Punctive time can be used to anchor an event that has a duration, such as a wedding or an election. It may be represented by various levels of granularity, for instance a second or a year, or by two dates between which an event was known to occur.

**Comment by SusanBrown** [comment]
Interval time:  An indication of a span of time, usually represented in the form of a start and end date.

**Comment by SusanBrown** [comment]
hasTimeCertainty: Indicates the degree of certainty or precision of the temporal value or values associated with a time-based phenomenon such as an event or birth date.
