### ISSUE TITLE
"Editing" (Orlando genre term) missing from genre ontology

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#438]

**Comment by SusanBrown** [comment]
I think we may have decided that this should be extracted into an occupation Editor, since it really doesn't describe a genre per se.

**Comment by alliyya** [comment]
See [Genre Spreadsheet](https://docs.google.com/spreadsheets/d/1EKuEL1WCM9Zq4DpzTqBWN1vAlz4ab06C5yUyhv_t1Zc/edit#gid=996103665) for other missed Orlando Genre terms @SusanBrown

**Comment by alliyya** [comment]
Not extracting as an occupation

Has been added to the genre ontology as [genre:EditorialWork](http://sparql.cwrc.ca/testing/genre.html#editorialWork).
