### ISSUE TITLE
create CWRC primary genre subclass

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#441]
Create subclass of http://sparql.cwrc.ca/ontologies/genre.html#genre%3ALiteraryGenre whose members will be the genres thus identified by CWRC

**Comment by alliyya** [comment]
I believe this has been done? @SusanBrown

**Comment by SusanBrown** [comment]
they are the same

**Comment by alliyya** [comment]
Closing this issue as it's a duplicate of #428
