### ISSUE TITLE
Update Team HTML page

### ISSUE THREAD

**Issue by alliyya** [cwrc/ontology#453]

**Comment by JasmineDW** [comment]
@SusanBrown do we want to update all the dates & roles of past users? @HannahJS99 will put together a blurb about her role. Should any other folks be added?

**Comment by JasmineDW** [comment]
Jasmine to update general information (dates. role modifications) and add Thomas & Michaela (reach out about description of roles)

**Comment by HannahJS99** [comment]
I've added Thomas, Michaela, and myself to the Team page. @SusanBrown is this all that needed updated?

**Comment by SusanBrown** [comment]
Diane Jakacki contributed terms related to REED London to the genre ontology.

**Comment by alliyya** [comment]
Can this be closed @SusanBrown  & @JasmineDW ?
