### ISSUE TITLE
Review Subjects of Study instances specifically Languages

### ISSUE THREAD

**Issue by alliyya** [cwrc/ontology#455]
From: Triple(s) Check: Quality Assurance
> We should be using a consistent approach for languages as subjects (see Latin, German, and French LOC links for differences) 

Under Subjects tab
https://docs.google.com/spreadsheets/d/1QrbfyP3x39LJdLj76T-ibeIcy5mwmDJM4bEgLWGUdYk/edit#gid=2087087535

If someone could review the instances of languages in Subjects of Study and make sure that we are using MARC List of Languages when available:
http://id.loc.gov/vocabulary/languages/afr
instead of 
http://id.loc.gov/authorities/subjects/sh85001765

This way we're consistent with the usage of LOC languages in Subjects of study and Languages known

**Comment by lemaka** [comment]
I can tackle a chunk of these this week!

**Comment by lemaka** [comment]
@lemaka to pass this on to Thomas on Tuesday, Oct 16th

**Comment by alliyya** [comment]
@lemaka To Review
@alliyya to update extraction

**Comment by JasmineDW** [comment]
@alliyya was extraction update to include these modifications?
