### ISSUE TITLE
clean up Figure and Graffles folder in Google Drive

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#456]
review in the following order: 1st Approved —> 2nd Pending Polish —> 3rd In Progress

https://drive.google.com/drive/folders/0B8C90DSaQG_sazJtMmVHc0s3M0k

- [ ] Approved Graffles
- [ ] Pending Polish 
- [ ] In Progress

**Comment by alliyya** [comment]
@lemaka Are you still wanting to take this on to match up with your revised conventions in #337

**Comment by lemaka** [comment]
yes!

**Comment by lemaka** [comment]
I think we agreed to only change the style of the graffles that are being made moving forward or about to be used in a presentation or publication, given that many of the graffles are now stale.
