### ISSUE TITLE
suffrage and WomensEnfranchisement

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#459]
The latter should be folded into the former but it is not.  Seems to be connected to Harriet Taylor

**Comment by alliyya** [comment]
WomensEnfranchisement should be deprecated in favour of suffrage ? @SusanBrown

**Comment by SusanBrown** [comment]
Can this be closed now, @alliyya ? or do changes need to be made to extraction as well before it can be closed?

**Comment by alliyya** [comment]
closed in bf0dcb1c146d9af03e94a64dd4af63871ada72bf
