### ISSUE TITLE
hasAnnotation property?

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#460]
I should have raised this at our meeting yesterday, but I forgot.

Because of the structure of our extracted data, when you ask for all the properties of a person, you do **not** get the annotation data. In other words, all of the triples are returned, but not the Contexts related to them. 

You could of course get them if you asked for all properties with a person as object as well as subject, but I think that "give me all properties of person x" will be a common enough query, without the request for object, that we should consider creating a hasAnnotation property for people, in parallel with hasEvent, that will mean that the Annotation data doesn't get separated from the triples for that person.

What do people think?

**Comment by alliyya** [comment]
I think this issue would go away with the proposed schema approach, am I correct? wdyt @joelacummings

**Comment by alliyya** [comment]
Resolved with our usage of cwrc:contextFocus within the Complex<--> Simple model that we're now implementing.
