### ISSUE TITLE
Handling uncertainty with birthdates/deathdates

### ISSUE THREAD

**Issue by alliyya** [cwrc/ontology#462]
We possibly need more predicates to handle the uncertainty of the dates provided for a writer's birth/death date as currently provided by `hasBirthDate` and `hasDeathDate`

Ex. Cases of Daterange where we have a range of possible dates

`<DATERANGE CERTAINTY="C" FROM="1689-02" TO="1690-07-12" EXACT="FROM" CALENDAR="NEWSTYLE">1689-91</DATERANGE`

**Comment by SusanBrown** [comment]
Because we cannot flag uncertainty with xsd dates, and because not all of these dates are in events where the complexity can be flagged, I'm thinking the best thing to do might be to have a predicate such as hasApproximateBirthdate and hasApproximateDeathDate to cover cert=uncertain, RoughlyDated and dateRanges.

**Comment by SusanBrown** [comment]
Note from Joel on certainty: I'm wondering if this should be attached to a time object -- perhaps we are certain when some died but not certain when they were born for example or (vice versa) and want to attach different certainty to particular times?

**Comment by joelacummings** [comment]
We will need to look at defining ranges within the ontology where something can occur, I will check if anything exists that does this well.

**Comment by joelacummings** [comment]
Looking at [time:hasTime](https://www.w3.org/TR/owl-time/#time:hasTime) which allows any [TemporalEntity](https://www.w3.org/TR/owl-time/#time:TemporalEntity) so we could use a [Instant](https://www.w3.org/TR/owl-time/#time:Instant) or an [Interval](https://www.w3.org/TR/owl-time/#time:Interval) for where a death date may have occurred.

**Comment by alliyya** [comment]
Decision: 
-  Creating predicates: hasApproximateBirthDate & hasApproximateDeathDate
- use SKOS:closeMatch to relate hasApproximateBirthDate to hasBirthDate, etc
- use earliest Date for birth and latest date for Death when daterange has been used

new terms hasApproximateBirthDate & hasApproximateDeathDate need definitions @SusanBrown
