### ISSUE TITLE
XSLTs for producing unicode

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#463]
Try to get running from command line.

https://www.saxonica.com/documentation9.5/using-xsl/commandline.html

The following needs to be changed to https otherwise error that the doctype declaration is wrong: `<!DOCTYPE ORLANDO [ <!ENTITY % character_entities SYSTEM "http://cwrc.ca/schemas/character_entities.dtd"> %character_entities; ]>`

java -jar saxon9he.jar -s:/home/jefferya/Downloads/woolvi-b.xml -xsl:orlando_legacy_to_v2_bio_writing.xsl -o:woolvi-b_utf8.xml

**Comment by alliyya** [comment]
@GurjapSingh What's the status of this? Did you end up using oxygen or from cmdline? Any scripts that need to be added to the extraction repo?
