### ISSUE TITLE
Typo on line 192 of cwrc.rdf

### ISSUE THREAD

**Issue by ubermichael** [cwrc/ontology#464]
The `sh` at the end of line 192 is causing my validator some problems.

    <void:triples>TOTAL_TRIPLES_CWRC_ONTOLOGY</void:triples>sh

Removing the `sh` there fixes validation.

**Comment by SusanBrown** [comment]
Thanks so much for flagging this, @ubermichael. Should be ok now but let us know if you encounter any other problems.
