### ISSUE TITLE
Archive extraction datasets

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#468]
Talk to UG Lib about Docuverse archiving that will make it part of FRDR.

**Comment by alliyya** [comment]
Status update @SusanBrown ?

**Comment by alliyya** [comment]
Status update on this @lmustafa @SusanBrown, anything particular needed from Joel or myself?

**Comment by JasmineDW** [comment]
@alliyya is this done? If yes, please close!

**Comment by alliyya** [comment]
I think this was done? @SusanBrown

**Comment by SusanBrown** [comment]
Yes, done.
