### ISSUE TITLE
Reification

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#470]
Strategy for implementation:

- [ ] item one

Consider SHACL as one alternative to possible reification.

Possibly related (if not break out into separate issue):
Multiple instances of the same triple (e.g. someone visits a place more than once)
So this sounds like events will all just be typed with sem:Event? The only thing this rules out is a direct search of events by type. Something to consider is if they will always be associated with a context that can allow narrowing based on type.

**Comment by alliyya** [comment]
We're going with the context-centric model based on web annotation
