### ISSUE TITLE
Set up VM to run the 3D-Graph Viz from the Westgrid competition

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#472]
Will require coordination with the developer; probably easiest to give him access to the VM. I'll put you two in touch when you give me a heads up that you can proceed, @joelacummings

**Comment by alliyya** [comment]
@SusanBrown Is this still something we want to do?

**Comment by SusanBrown** [comment]
Ideally but I’d say we don’t have the cycles for it for the moment.
On Aug 9, 2019, 12:24 PM -0400, Alliyya Mo <notifications@github.com>, wrote:

@SusanBrown<https://github.com/SusanBrown> Is this still something we want to do?

**Comment by SusanBrown** [comment]
So move to icebox?
On Aug 20, 2019, 10:47 PM -0400, sbrown@uoguelph.ca, wrote:
Ideally but I’d say we don’t have the cycles for it for the moment.
On Aug 9, 2019, 12:24 PM -0400, Alliyya Mo <notifications@github.com>, wrote:

@SusanBrown<https://github.com/SusanBrown> Is this still something we want to do?

**Comment by JasmineDW** [comment]
@alliyya @SusanBrown What's the status of this?
