### ISSUE TITLE
small fixes

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#478]
![image](https://user-images.githubusercontent.com/545952/55293203-0427f880-53c2-11e9-853e-2e39dd978839.png)
bisexuality is alt term for bisexuality?

**Comment by alliyya** [comment]
Will update [testing](http://sparql.cwrc.ca/testing/cwrc.html) for anyone to review later this weekend. Possibly fix hook that was automatically updated testing

**Comment by alliyya** [comment]
[Testing ](http://sparql.cwrc.ca/testing/cwrc.html) has been updated. There's a few duplicates that weren't removed because my script was case-sensitive. 

Later follow-up issue with reviewing altlabels and hidden labels. https://github.com/cwrc/ontology/issues/424
