### ISSUE TITLE
sub Organization types

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#490]
PoliticalOrganization is defined but we have no instances of them that I can see. Were we going to generate them, ReligiousOrgs and EducationalOrgs from the data?

**Comment by alliyya** [comment]
PoliticalOrganization, ReligiousOrganization, EducationalOrganization instances are generated from the data and authority file. see: https://github.com/cwrc/RDF-extraction/blob/master/data/organizations.ttl
