### ISSUE TITLE
Place: FictionalPlace and MappedPlace

### ISSUE THREAD

**Issue by JasmineDW** [cwrc/ontology#492]
For Place create: FictionalLocation (like Narnia) and MappedLocation

**Comment by alliyya** [comment]
Decisions from meeting:
Classes:
     cwrc:Place
Subclasses: 
     cwrc:FictionalPlace, cwrc:MappedPlace 

Predicate for linking place and uri will be cwrc:hasLocation. 
The predicate cwrc:hasMappedLocation is deprecated in favour of using cwrc:hasLocation

Places will be typed as a cwrc:Place if it isn't mappable (ex. for usage of gazeteers like Getty). If mappable then type place as cwrc:MappedPlace.

Getty uri --> cwrc:Place
Geonames uri --> cwrc:MappedPlace

FictionalPlaces that are identifiable with either Getty or Geonames will be typed as accordingly and as a cwrc:FictionalPlace
