### ISSUE TITLE
citations

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#498]
Attempt to develop an approach using Open Citations http://opencitations.net/model which draws on the SPAR ontologies, especially
and
https://sparontologies.github.io/cito/current/cito.html#d4e1716
with a tiny bit of:
https://sparontologies.github.io/c4o/current/c4o.html

I think we are going to have to create blank nodes at least and most likely actual data instances for citation in order to have a way of including the page number information, i.e. we can't link directly using cito:cites or we will lose that essential detail.  

Graffle here: 
https://drive.google.com/open?id=10GdSrbee7JoQWdXUIaJO_bxfoU4_HFYi
https://drive.google.com/open?id=1kkuLMIPYL-4UpEC7YIQeb4FcQIXeuC6L (png)

I think where I am stuck it in figuring out what an Orlando bibcit is -- it is a cito:Citation or a biro:bibliographicReference? And nowhere can I find guidance on how exactly to include the information about where in the cited source the information occurs although presumably that is going to be a literal with some relation to the citation entity.

**Comment by joelacummings** [comment]
Had a go at revising the graffle: 

https://drive.google.com/open?id=10GdSrbee7JoQWdXUIaJO_bxfoU4_HFYi (graffle)
https://drive.google.com/open?id=1nLrLTPDJQ8tCgmo5yIqYmRqorzkxRkzx (png)

**Comment by alliyya** [comment]
Agreed upon graffle
https://drive.google.com/file/d/1yEZe-vlClDPE-soB7kj27-Poxmf7BCyG/view

TODO: update with proper orlando url possibly including xpath and text selector if there's space.
