### ISSUE TITLE
Genre URI's

### ISSUE THREAD

**Issue by rwarren2** [cwrc/ontology#5]
The Genre URI's we used for the NovelTM were long numbers. Should I keep the same URI for inclusion in the official CWRC ontology?
eg: The URI for the 'Drama' genre is:

http://localhost/OrlandoPubs#Genreffec9ec521e7009130e75d362a8ee15c 

Any objection? Or would you prefer something easier on the eyes like #GenreDrama?

**Comment by susanirenebrown** [comment]
I think I’d just as soon use something more human readable if possible. I know there’s a strong argument for unique numbers but I do think it can be quite helpful in looking at the data.

**Comment by rwarren2** [comment]
Converting to semi-human readable uri and convert only NovelTM data.
