### ISSUE TITLE
Define EventClimate and EventSignificance

### ISSUE THREAD

**Issue by alliyya** [cwrc/ontology#504]
for grouping 

- BritishWomenLiteraryClimate
- LiteraryClimate
- PoliticalClimate
- SocialClimate

and 

- HistoricSignificance
- IndividualSignificance
- PeriodSignificance

**Comment by SusanBrown** [comment]
EventClimate
label:eventClimate
definition: Indicates the broad category or categories in which an event has been grouped by an author or editor, 

ChronColumn is a mandatory attribute of chronStruct and has four values: "nationalInternational," "BritishWomenWriters," "writingClimate," and "socialClimate." These attribute values carry the following connotations: "National/International Events"

British-centric events with major implications in Europe, colonies, or world-wide;
major foreign events which affected Britain either politically or socially (eg., Russian Revolution);
establishment of major national and international organizations (eg., League of Nations, Oxfam, International Labour Organization);
change in status of countries' governing structure, especially colonies, former colonies, and close allies (eg. independence, coups);
British monarchs accession;
British national elections;
major British military engagements (eg., Boer War, major campaigns of WWI &#38; II, in India)
"Social Climate" The items in this column will frequently refer not to discrete events but to larger trends or practices affecting women; this means that dates may often be approximate. (note: please always regularise approximate or uncertain dates in the value attribute of date)The following are types of information appropriate to this column:
advances, developments, or regressions in the areas of technology, science, medicine, law
education
conditions surrounding or affecting domestic conditions: housing, clothes, food and food supply, family well being
women's political office or involvement in political organisations e.g. the dates of a non-writing but historically significant woman's election to office (Only major first events will be listed in the National and International Events column--e.g. Lady Astor as first woman to take her seat in the House of Commons)
Writing Climate
texts and events associated with male writers
texts and events associated with non-British women writers
information about copyright, print technology, etc.
British Women's Writing
texts and events associated with British women writers
material conditions affecting British women's writing

EventSignificance
label: event significance
definition: Indicates the degree of importance assigned to an event by an author or editor, ranging from events having some kind of historic significance through events significant to an understanding of that period, to events of individual biographical significance.
