### ISSUE TITLE
Define hasApproximateBirthDate & hasApproximateDeathDate

### ISSUE THREAD

**Issue by alliyya** [cwrc/ontology#505]
see #462

**Comment by SusanBrown** [comment]
hasApproximateBirthDate
label: has approximate birth date
skos:closeMatch hasBirthDate
definition: Provides an approximation of the date on which a person was born.

hasApproximateDeathDate 
label: has approximate death date
skos:closeMatch hasDeathDate
Definition: Provides an approximation of the date on which a person died.
