### ISSUE TITLE
Ensure that religions are in sync with Orlando.

### ISSUE THREAD

**Issue by rwarren2** [cwrc/ontology#51]
African Methodist Episcopal Church
Anglican Church
Anglican  Church
Baptist Church
Christianity
Christian Science
Church of England
Clapham Sect
Congregational Church
Covenanters
Dissenters
Dissenting Churches
Fifth Monarchists
Hermetic Order of the Golden Dawn
Hermetic Society
Independent Church
Independent Methodist Church
Islam
Jansenists
Jewish Students' Society
Judaism
Lollards
Methodist Church
Moravians
Mothers' Union
Nonconformist Churches
Oxford Movement
Plymouth Brethren
Presbyterian Church
Protestant Church
Puritans
Roman Catholic Church
Society of Friends
Theosophical Society
Unitarian Church
Universalist Church

(episcopal is to be synonymous with anglican)

**Comment by rwarren2** [comment]
Checkup on "Sufism, african religion and tarot card believer"

**Comment by lemaka** [comment]
what's the status of this/ what's left to be done @rwarren2 ?

**Comment by SusanBrown** [comment]
Confirmed that we not incorporate religious organizations into the ontology but instead stick to "ism"s. 
Religious organizations will be part of the dataset.
To be discussed: 
1) classing of different types of orgs (e.g. religious, publishing, educational etc)
2) predicates for linking e.g. reglious orgs to the associated religions.

**Comment by alliyya** [comment]
Religions are not completely in sync with orlando see Universalist Church.

**Comment by joelacummings** [comment]
Not sure the status of this, but assigned those who appear to be in the know :-)

**Comment by alliyya** [comment]
See #448 For missed instances in biographic data
