### ISSUE TITLE
Proposal: hasCertainty not to be a subproperty of oa:hasBody

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#510]
**1. cwrc:certainty**

Other provenance information such as dc:creator are functionalProperties/objectProperties are not subproperties of oa:hasBody within the data model, and cwrc:hasCertainty seems parallel and could be typed as both of these things, reasonably.

We don't current have this in the ontology, but one of the graffles represented it thus, so wanting to confirm that we are all on the same page with this. 

**2. hasEvent**

An event, on the other hand, is an identifiable entity that is an important component of the content of an annotation so cwrc:hasEvent ought, in my view, to be a subproperty of oa:hasBody.

If no discussion is needed, pls indicate agreement here. If there is disagreement, we will discuss.

**Comment by joelacummings** [comment]
Agreed, likely a mistake on the Graffle.
