### ISSUE TITLE
Proposal: allow multiple context foci for the same annotation

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#512]
While there are some cases such as father/daughter relationship that require 2 separate annotations because the relationships are not the same (i.e. hasFather & hasDaughter) there are cases in Writing docs where there are multiple Textscopes on the same Div, indicating that all the tagging within that Div pertains to all of the texts indicated by the textScope, which means that identical relationships would be generated for all texts. So in such cases, I think we can have multiple context foci, unless there are reasons not to that Alliyya and I cannot think of right now.

**Comment by joelacummings** [comment]
This sounds reasonable and I'd expect this to occur in other cases. It's fine as long as the subject does not change, that doesn't seem to be the case here.

**Comment by alliyya** [comment]
Decision documented in the extraction process.
