### ISSUE TITLE
genre revisions

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#513]
folkSong -- not a thematic genre
immigration - change to migration (can we figure out where this term came from? not in Orlando)

**Comment by alliyya** [comment]
folkSong just a NarrativeGenre & SongGenre ?
Immigration originates from [Immigration writing](https://docs.google.com/spreadsheets/d/1zOFxBmnFHyadaCR1CmvekeADxemBqVFEsIH3XWjvCoM/edit#gid=2121187828&range=E459) from the [CWRC subgenre picklist](https://cwrc.ca/terms/subgenre.pdf)
Still revise to migration @SusanBrown with altlabel Immigration writing ?

**Comment by SusanBrown** [comment]
Just SongGenre

**Comment by SusanBrown** [comment]
Yes on migration
