### ISSUE TITLE
Genre Revisions

### ISSUE THREAD

**Issue by alliyya** [cwrc/ontology#521]
- [x] Incorrect definitions for [HistoricalWriting](http://sparql.cwrc.ca/ontologies/genre.html#historicalWriting) use http://dbpedia.org/page/Historical_fiction definition

**Comment by SusanBrown** [comment]
Definitions required for:

- [ ] chapter, also added to EmbeddedWork 
- [ ] document
- [ ]

**Comment by alliyya** [comment]
@HannahJS99 Can you look through this issue and see that it's been followed up on.

**Comment by HannahJS99** [comment]
Note for future reference: sound recording, radio, and television terms seem to be adequately covered for now but we may want to revisit this later.

**Comment by alliyya** [comment]
Can this be closed @HannahJS99 ?

**Comment by HannahJS99** [comment]
I've completed almost all of the tasks associated with this issue. The only thing that remains is to finish sorting instances into types. I've started making notes using hypothesis about what instances should be sorted into types, but this will likely be a more long term, ongoing task.

**Comment by alliyya** [comment]
I think I'll make that a separate issue so we can track that work better in that case.

**Comment by HannahJS99** [comment]
Perfect; I think that's a good plan.
