### ISSUE TITLE
REED London genre term requests

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#528]
I've reviewed [this spreadsheet](https://docs.google.com/spreadsheets/d/1iI61vDZfQLqRN46vMhrECP07Lfd8VWkZ83C2fpwuaFI/edit#gid=0) and sent a few queries to Diane about it (re: removing x-references, and the fact that I seem not to be able to access all the definitions. For instance I cannot see 22C at the url in D; and the “(e.g., parish…..” portion of 24 C).

Once my queries are answered and final edits made, I think the terms can go into the genre ontology. I see no conflicts with the hierarchy and existing terms but would like @HannahJS99 to review for any possible problems as well.

**Comment by SusanBrown** [comment]
@HannahJS99 , this is good to go now.  I just gave you and Alliyya permission to the sheet, so please take a look and if all looks well to you both, then go ahead and start adding them. I copied what seemed like the necessary columns from our genre revisions spreadsheet, minus the fancy formatting ;)

**Comment by HannahJS99** [comment]
I've added all the new terms. Alliyya is going to review them and then merge the branch I used for these edits.
