### ISSUE TITLE
Ensure that sexual identity tags from Orlando are handled by Ontology

### ISSUE THREAD

**Issue by rwarren2** [cwrc/ontology#53]
As extracted from Orlando ontology:

BISEXUAL
BISEXUALITY
CELIBATE
FRIGID
HETEROSEXUAL
HETEROSEXUALITY
HOMOPHOBE
HOMOPHOBIC
HOMOSEXUAL
HOMOSEXUALITY
LESBIAN
LESBIANISM
LIBERTINISM
MALE HOMOSEXUAL
PROMISCUOUS

**Comment by rwarren2** [comment]
All Sexuality Tags will point to a main 'reference' class but the actual value of the tag will be kept as part of a separate skos-xl label infrastructure,

**Comment by rwarren2** [comment]
All long hand narratives:

owing to her family's status, 
passionate and life-long intimate relationship
passionately in love with a younger man
pillar of the orthodox institution of marriage
possibility that she had an 
profound distrust of men
prolific married life
promiscuity
promiscuous
recent biographers agree that 
 refers to a 
relationships with both men and women
relationships with women
religious life
richer for us
romantic
s[apphic]
sapphism
 seems unlikely to have included a strong erotic component on her side, although from her lifetime 
onwards some have supposed that it did
selective promiscuity
self-identification with the male
series of short-lived affairs, mostly with men but occasionally also with women
several affairs
sex and sexuality
sexual
sexual affair
sexual experience, with a mixed-race girl
sexual infringements of various kinds
sexuality
sexually enthralled by a woman
sexual pleasure at least briefly in her first marriage
sexual preference
sexual preferences
sexual relationship
sharing her husband with her best friend
she and 
she called lloyd her wife
she grew up with the standard sexist expectations (from her parents and her education) that she would fulfil herself as a woman in marriage, by bearing and caring for children, but that she would also have 
she had affairs with men as well as women, both before and after her marriage,
she never married and remained devoted to the birth relations who treated her like a servant.
single life
some of their friends believed the relationship was non-sexual; 
spinster
staunchly proclaimed her heterosexuality
strong erotic attachments to women
such as very close bonds between women
tended to turn a corner away from physical expression
 that she had no physical experience of sex. when questioned about herself and jourdain, she used a phrase that came from jourdain: 
the relationship may have been sexua
 to 
 told 
twice married
uninterested in sexual relationships for herself
unmarried
unmarried by choice and preference
unmarried, it now appears (contrary to what has been written about her in the past) at least largely by choice
unmarried status
, upset over an earlier dispute, entered her friend's bedroom at night and acted in such a way that it was a 
very possibly a lesbian
 was her family's code word for lesbianism.) 
was not, as people used to say, 
 was probably attracted to women, though it is unlikely that she had a sexual relationship with a woman.
 was sought out as a potential marriage partner by the age of twelve, and her parents insisted that her future husband should be, like them, 
whatever its nature—and 
when she fell in love with women, she hoped she had no 
, who had put some of her poetry to music, had been lovers
with individuals of both sexes
: women whose admiration for her intellectual and social successes was often accompanied by erotic feeling, which lee returned.
would never marry

**Comment by rwarren2** [comment]
We are missing cwrc:bisexual which is breaking some of the demos.

**Comment by SusanBrown** [comment]
We need a bit of clarification on this scrape, I think.

Could you confirm that the list in caps is all the REG attributes for the SEXUAL IDENTITY (not SEXUALITY, which will become the CF Sexuality Context snippets)?  It looks like it.

And did you **exclude**  the long-hand narratives for which there is a REG attribute on the tag? 
Please confirm.

If so, we just need the first half of the list of long-hand narratives, we think (assuming that it is unlikely to start with the letter "o").

**Comment by SusanBrown** [comment]
We think from looking at this further today that not all long-hand narratives with REG tags are excluded here. We would like a list of all long-hand narratives that **do not** have a REG tag (after tomorrow's deadline has passed that is ;) ).

**Comment by alliyya** [comment]
HOMOPHOBE
HOMOPHOBIC

Currently not in the ontology, rest is in

**Comment by susanirenebrown** [comment]
No worries: nto needed at present because not in sample data

**Comment by alliyya** [comment]
HOMOPHOBE
HOMOPHOBIC
Will not be in the ontology
