### ISSUE TITLE
Update SPARQL Documentation

### ISSUE THREAD

**Issue by JasmineDW** [cwrc/ontology#532]
SPARQL query URLs need to be updated. This issue will track individual tasks contributing to this update

- [x] Update query to include Yasgui url, and Fuseki endpoint
- [ ] Alliyya to push modifications to live site
- [x] Clean up graphs
- [ ] Modify queries/documentation to reflect graph updates
- [ ] Update references to Orlando

**Comment by alliyya** [comment]
Will be retiring the following graphs that will affect current query pages:

- [ ] http://sparql.cwrc.ca/data/orlando_volumes
- [ ] http://sparql.cwrc.ca/data/orlando_volumes/1
- [ ] http://sparql.cwrc.ca/data/orlando_volumes/2
- [ ] http://sparql.cwrc.ca/db/BiographyV6

These should be replaced with `http://sparql.cwrc.ca/data/orlando` or `http://sparql.cwrc.ca/data/orlando/simple`

Other graphs that will be removed shouldn't affect the documentation
- [ ] http://www.lincsproject.ca/cwrc/vocab
- [ ] http://www.lincsproject.ca/occupations
- [ ] http://sparql.cwrc.ca/ontology/cwrc

**Comment by alliyya** [comment]
Need to update all queries to reflect changes from #543
