### ISSUE TITLE
General Revisions

### ISSUE THREAD

**Issue by JasmineDW** [cwrc/ontology#539]
- [x] feministInternationalism not sameAs/exactMatch <http://dbpedia.org/resource/Internationalism_%28politics%29>
- [x] feministPacifism not sameAs/exactMatch <http://dbpedia.org/resource/Internationalism_(politics>, dbpedia:Pacifism ;

**Comment by alliyya** [comment]
@JasmineDW Can you check if these are still present in the RDF and remove them or correct them.
