### ISSUE TITLE
Nationality 

### ISSUE THREAD

**Issue by rwarren2** [cwrc/ontology#54]
Regularized Values:

african
american
anglo-irish
austrian
bulgarian
canadian
corsican
dutch
english
european
french
german
germany
irish
iroquois
italian
italy
jamaican
latvian
lithuania
lithuanian
new zealand
new zealander
nigerian
northern ireland
northern irish
polish
pollish
portuguese
scotland
scottish
spanish
swedish
swiss
the netherlands
ukrainian
usa
walsh
welsh

**Comment by rwarren2** [comment]
Non Regularized Value:

african
america
american
american-austrian
 ancestry included ties to 
 and 
anglicised irish
anglo
anglo-
anglo-french
anglo-irish
anglo-scottish
background
bengali
-born
born in 
born in england
british
bulgarian
, but who moved to 
canada
canadian
clan mackay
colonial american
cornish
corsican
cuban
danish
denmark
 descent though little money on both sides of her family).
 during violet's early childhood.
dutch
dutch-descended
edinburgh
england
english
english father
englishness
englishwoman
european
family
flemish
florentine
foreigners
french
french-canadian
french-descended
french extraction
french mother
french swiss
german
germany
ghanaian
half-english
half-french
half-irish
half-scots
hanoverian
 heritage and lived most of her life in britain.
holland
huguenot
hungarian
immigrant experience
ireland
irish
irish-
irish ancestry
irish ascendency
irish descent
irishness
irishwoman
italian
jamaican
jewish
latvia
 lineage (
lithuania
lithuanian
mohawk
multicultural
netherlands
new hampshire
new zealand
new zealander
nigerian
norman
northern english
northern ireland
northern irish
 notes that 
people of the reserve were noted for being vigorously intellectual and respectful of matrilineal traditions.
peruvian
poland
polish
portugal
portuguese
russian
scotch
scotland
scots
scotswoman
scottish
scottish 
scottish-irish
's family were 
shetland
southern american
southern states of america
spain
spanish
swedish
swiss
tatar
 that is, the family of protestant activist and martyr 
the 
turkish
ukraine
ulster
ulster irish protestants
united states
usa
viennese
 was born to parents whose 
 was of 
welsh
welsh 
welsh extraction
west indian
writer and activist

**Comment by colinraybrian** [comment]
Moved to https://docs.google.com/spreadsheets/d/1Z5wUJZGLu-6yXdiS9dMd1iPgY6PnoVHZFLsfYAGQiIs/edit#gid=0

I think the consensus is that we are holding off on processing this until after DH2017.

**Comment by SusanBrown** [comment]
Yes: hold off.

**Comment by alliyya** [comment]
@rwarren2 Needs to create a mapping function

**Comment by alliyya** [comment]
Missing instances here
https://docs.google.com/spreadsheets/d/1UROdUIXOqzG4bGVP8DU4EXL5jl3ejxwuZYtNAm7xlk0/edit?usp=drive_web&ouid=118423644733772776445

**Comment by alliyya** [comment]
Mapping is complete, no missing instances atm with available data samples.
