### ISSUE TITLE
Form and Genre classes

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#541]
Should we create Form and Genre parent classes in order to group these separately or should we just stick with owl:Class?

**Comment by alliyya** [comment]
Not too sure what you mean as we do use Form and Genre as parent classes to group terms. 
Ex. https://sparql.cwrc.ca/ontologies/genre.html#AlphabetForm
genre:AlphabetForm is a subclass of Form
and has instances listed underneath it. 

See also: https://sparql.cwrc.ca/testing/genre.html#Form

I think this might be a point of confusion with the layout of the documentation page perhaps maybe?

**Comment by SusanBrown** [comment]
Nope it's a result of my not looking at testing instead of the public version. This issue is already dealt with.
