### ISSUE TITLE
Missing labels in Illnesses and Injuries Ontology

### ISSUE THREAD

**Issue by alliyya** [cwrc/ontology#550]
Was just looking at some queries for the SPARQL Learning Group today and came across some entities with no label.

These are the entities missing labels
- [x] http://sparql.cwrc.ca/ontologies/ii#Congenital_malformation_deformation_or_chromosomal_abnormality
- [x] http://sparql.cwrc.ca/ontologies/ii#Disease_of_the_blood
- [x] http://sparql.cwrc.ca/ontologies/ii#Disease_of_the_circulatory_system
- [x] http://sparql.cwrc.ca/ontologies/ii#Disease_of_the_digestive_system
- [x] http://sparql.cwrc.ca/ontologies/ii#Disease_of_the_ear
- [x] http://sparql.cwrc.ca/ontologies/ii#Disease_of_the_eye
- [x] http://sparql.cwrc.ca/ontologies/ii#Disease_of_the_genitourinary_system
- [x] http://sparql.cwrc.ca/ontologies/ii#Disease_of_the_musculoskeletal_system
- [x] http://sparql.cwrc.ca/ontologies/ii#Disease_of_the_nervous_system
- [x] http://sparql.cwrc.ca/ontologies/ii#Disease_of_the_respiratory_system
- [x] http://sparql.cwrc.ca/ontologies/ii#Disease_of_the_skin
- [x] http://sparql.cwrc.ca/ontologies/ii#Endocrine_nutritional_or_metabolic_disease
- [x] http://sparql.cwrc.ca/ontologies/ii#External_cause
- [x] http://sparql.cwrc.ca/ontologies/ii#InfantDeath
- [x] http://sparql.cwrc.ca/ontologies/ii#Infectious_disease
- [x] http://sparql.cwrc.ca/ontologies/ii#Injury
- [x] http://sparql.cwrc.ca/ontologies/ii#Mental_and_behavioural_disorder
- [x] http://sparql.cwrc.ca/ontologies/ii#Pregnancy_or_childbirth
- [x] http://sparql.cwrc.ca/ontologies/ii#Unspecified_unknown

Need to double-check [II vocabulary](https://gitlab.com/calincs/infrastructure/vocabularies) as well to make sure labels are there too. 
- [x] Vocab checked? Duplicate above list if they are missing and check them off as needed

**Comment by JasmineDW** [comment]
Added to vocab in GitLab
