### ISSUE TITLE
Writing Predicate Modifications

### ISSUE THREAD

**Issue by JasmineDW** [cwrc/ontology#556]
The following relationships between Writing predicates need to be updated based on model pdfs generated by Alliyya:

<img width="1016" alt="Screen Shot 2022-06-06 at 10 43 09 AM" src="https://user-images.githubusercontent.com/29200198/172184486-2bfa85c2-456b-451d-b55b-1112426e2ee2.png">

<img width="1017" alt="Screen Shot 2022-06-06 at 10 43 39 AM" src="https://user-images.githubusercontent.com/29200198/172184666-4fba7e7b-ae9b-48c9-9171-e93d7c8ed781.png">

- What query did Alliyya use to create the model images? 
- How can having inverse properties (with parent properties that are symmetric) impact the queries used?

- [x] has influence on doesn’t have the corresponding is influenced by inverse
- [x] all the connections to [has influence on] should be to [is influenced by] instead

<img width="450" alt="Screen Shot 2022-06-06 at 10 46 35 AM" src="https://user-images.githubusercontent.com/29200198/172184819-ef9d327b-7c71-4f17-a920-9c5774d0071a.png">

- [x] I think you may have mapped the inverse predicates because the simple predicate versions of those are hasXYZinfluence
- [x] bestKnownWork should be a subproperty of receptionRelationship NOT writingRelationship

**Comment by alliyya** [comment]
@alliyya To provide examples+queries of extracted data of `RSHEINFLUENCE` & `PINFLUENCESHER`

**Comment by JasmineDW** [comment]
Decision:
1. Remove the following properties:
- isInfluencedBy
- influencedBy

2. Modify existing influence attribute properties to fit the language/structure of hasInfluenceOn
- hasLiteraryInfluenceOn
- hasIntellectualInfluenceOn
- hasfamilialInfluenceOn

The work of imposing directionality will be the responsibility of the extraction process; i.e. if within RSHEINFLUENCED tag, make the subject of the entry the subject in the triple; if within the PINFLUENCESHER tag, make the subject of the entry the object of the triple.
