### ISSUE TITLE
hasPoliticalAffiliation

### ISSUE THREAD

**Issue by rwarren2** [cwrc/ontology#56]
all Political Affiliations are missing.

**Comment by rwarren2** [comment]
REG values (Non REG values are the wild west):
abolition
abolitionish
abolitionism
abolitionist
activist for racial equality
activist for women and children
activist for women's education
advocate for the arts
advocate for the poor
against violence to women
aids activist
american nationalist
anarchist
animal activist
animal rights
animal rights advocate
animal welfare
animal welfare activist
anti-american
anti-anglican
anti-antisemitic
anti-antisemitism
anti-anti-semitism
anti-antisemitist
anti-apartheid
anti-appeasement
anti-blood-sports
anti-boer
anti-bolshevik
anti-bonapartist
anti-british
anti-capitalist
anti-capital punishment
anti-capital-punishment
anti-catholic
anti-catholic-emancipation
anti-catholicism
anti-censorship
anti-colonial
anti-colonialist
anti-communist
anti-conscriptionist
anti-conservative
anti-contagious diseases act
anti-contagious diseases act activist
anti-contagious diseases acts
anti-corn law
anti-corn laws
anti-corporal punishment
anti-cruelty
anti-cruelty to animals
anti-democracy
anti-democratic
anti-desegregationist
antidisestablishmentarian
anti-episcopal
anti-episcopalian
anti-european
anti-fascism
anti-fascist
anti-federalist
anti-female-genital-mutilation
anti-feminism
antifeminist
anti-feminist
anti-gladstonian
anti-globalist
anti-home rule
anti-home ruler
anti-home ruler 
anti-hunting
anti-imperial
anti-imperialist
anti-industrialist
anti-irish
anti-irish nationalist
anti-isolationist
anti-israeli
anti-jacobin
anti-jacobite
anti-land league
anti-militarism
anti-militaristic
anti-monarchist
anti-nazi
anti-nazi, anti-fascist
anti-nuclear
anti-nuclear activist
anti-nuclear war
anti-nuclear weapons
anti-pacifist
anti-parliamentarian
anti-poverty activist
anti-property
anti-racist
anti-radical
anti-reform
anti-reformist
anti-revolutionary
anti-segregationist
antisemitic
antisemitism
anti-semitism
anti-sexist
anti-slavery
anti-socialist
anti-sufffragist
anti-suffrage
anti-suffragist
anti-sweated labour
anti-tithes
anti-trade-unionist
anti-union
anti-unionist
anti vietnam war
anti-vivisection
anti-vivisectionist
anti-vivsection
anti-war
anti-war activist
anti-women's liberation
anti-zionist
artists' advocate
birth control activist
birth-control activist
birth control campaigner
black activist
black liberation
black liberationist
black power
black pride
bolshevist
boulangist
british nationalism
british nationalist
campaigner against child prostitution
campaigner for women's education
catholic
children's rights
children's rights activist
children's rights advocate
children's welfare
chinese communist
christian communist
christian pacifist
christian socialism
christian suffragist
civil libertarian
civil rights activist
colonialist
commonwealth supporter
communalist
communism
communist
conscientious objector
conscriptionist
conservatism
conservative
conservative feminist
conservative party
constitutional feminist
constitutionalist
contraceptionist
co-operative movement
covenanters
cultural nationalist
custody rights
democrat
democratic
dissident whig
divorce reform activist
divorce reformer
dress reform
dress reformer
dreyfusard
ecologist
educationalist
educational reform
educational reformer
education reform
education reformer
egalitarian
egyptian nationalism
elder care activist
emigration, imperialism
employment activist
environmentalist
equal rights
equal rights in the work place
eugenicist
existentialist
fabian
fabian socialism
factory reformer
fascism
fascist
fascist party
female education
female education advocate
female employment
female suffrage
feminism
feminist
feminist internationalist
feminist pacifist
foxite whig
free speech advocate
free trader
french nationalism
friends, society of
gay rights advocate
gender conservative
gender egalitarian
german nationalism
girondin
greek nationalist
guelph
hanoverian
health activist
high-church party
home ruler
home ruler (ireland)
housing activist
humanist
humanitarian
human rights
human rights activist
illegitimacy reformer
imperialism
imperialist
imperialit
independent
independent labour party
indian independence
indian nationalist
indigenous rights
individualism
individualist
industrial reformer
integrationism
intellectual property activist
internationalist
international labour party
irish home ruler
irish independence
irish moderate
irish nationalism
irish nationalist
irish patriotism
irish question
irish republican
irish republicanism
irish resistance
italian nationalism
italian nationalist
italian risorgimento
jacobin
jacobite
jacobitism
jewish emancipation
judicial reform activist
labour
labour activism
labour activist
labour advocate
labour feminist
labour movement
labour organizer
labour party
labour party activist
laissez-faire
land reform
land reformer
leftist
left-wing
legal reformer
liberal
liberal party
liberal unionist
libertarian
maoist
marriage law reformer
marriage reformer
married women's property supporter
marxist
maternal wage activist
mazzinian
meliorist (about slavery)
militant socialist
misogynist
moderate
moderate feminist
moderate suffragist
monarchist
monarchist (tudor)
movement against compulsory vaccination
multiculturalist
multi-racialist
nationalism
nationalist
nature conservationist
nazi
nazism
neo-conservative
new dealer
nihilist
non-aligned
non-chartist
non-compounder
non-feminist
nonjurors
non-militant suffragist
non-pacifist
non-separatist feminist
non-suffragist
nuclear disarmament
nuclear disarmament campaigner
opponent of capital punishment
opposition whig
owenite socialism
pacificism
pacifism
pacifist
pacifist supporter
parliamentarian
parliamentary reformer
parnellite
patriot
patriotic
patriotism
peace movement
personal rights advocate
pittite whig
polish nationalist
poor law reform
poverty activist
prison reformer
pro-alliance with britain
pro-american
pro birth control
pro-birth control
pro-boer
pro-bolshevik
pro-bonapartist
pro-choice
pro civil rights
pro-contraception
pro-countryside
pro-emigration
pro-european
pro-family
pro-fascist
pro free speech
progressivist
pro-independence (indian)
pro-nazi
pro nuclear disarmament
pro-parliamentarian
property reform
pro-reform
pro-revolutionary
pro-sexual preference
pro-slavery
protestant
protestantism
proto-feminist
pro-toleration
purity movement
race equality
racial equality activist
racial integration
racial integrationist
racism
racist
radical
radicalism
rationalist
reform
reformer
reformers
reformist
religious campaigner
religious libertarian
religious reformer
religious toleration
republican
revolutionary
roman catholic
royalist
sabbatarianism
salary reform
sanitary movement
school board
scoialist
scotialist
scots nationalist
scottish nationalist
secularist
sex-trade activist
sex-trade reformer
sexual liberationist
sexual libertarian
sexual reformer
single parents' advocate
social democrat
social democratic
social democratic foundation
social democratic party
socialism
socialist
socialist and feminist
socialist feminist
social purity
social reformer
social welfare
society of friends
spanish republican
spanish republican supporter
spiritualist
stalinist
state education movement
suffrage
suffragism
suffragist
sugar boycotter
supporter of independence
tariff reform
tariff reformer
tarif reform
tax resister
tax withholder
temperance
temperance activist
temperance movement
temperance supporter
tory
tory party
totalitarian
trade unionist
unionism
unionist
union movement
urban reformer
(us) nationalist
us nationalist
us patriotism
vegetarian
vietnam war protester
war supporter
welsh nationalist
whig
whiggism
whigs
wilkite
williamite
womanist
women's education reformer
women's employment reformer
women's higher education
women's labour activist
women's liberation
women's medical education
women's movement
women's rights
women's rights activist
women's suffrage
worked against the caste system
zionish
zionist

**Comment by SusanBrown** [comment]
Recording decision: we will use the noun form of political affiliation values for the term labels, i.e. feminism rather than feminist.

**Comment by colinraybrian** [comment]
I think this is ok to close
