### ISSUE TITLE
Missing Terms related to Marital Status

### ISSUE THREAD

**Issue by alliyya** [cwrc/ontology#568]
I don't know how these terms got missed!

They've been extracted before oddly enough just never made it into the Ontology therefore never in the Vocabulary.

Task:
- [ ] Add below terms to CWRC Ontology
- [ ] Add Instances to LINCS Vocabulary, I think these would be under the Personal Relations Vocabulary or maybe the Event Vocab?

# Terms

I don't think these fit in any subproperty hierarchy but if you find a suitable parent property/class add that relationship.

Predicate: `cwrc:hasMaritalStatusChange`
Context Predicate: `cwrc:maritalStatusChange`

Class: `cwrc:MaritalStatusChange`

Instances: 
- `cwrc:marriage` : Indicates a person's transition into a married relationship, whether legal or common-law, heterosexual or same-sex.
- `cwrc:divorce` : Indicates a person's transition, or in rare cases desired transition, from being married to being divorced.
- `cwrc:separation` : Indicates a person's transition out of a marriage or relationship through separation, whether temporary or permanent.

The definitions were pulled from the [biography spreadsheet](https://docs.google.com/spreadsheets/d/1L9V__vfiZ2hEZOsbVkMZ7-JlsToHHOuOKzbPIi-HTPs/edit#gid=1512757216), the property URIs are slightly different as these are what was extracted, so I assume that's more up to date than the sheet.
 
---

@SusanBrown Could you re-review these terms and definitions and then we can have @jingyilong update the Ontology/Vocabulary, Thanks!

**Comment by alliyya** [comment]
Any update on the above? Thanks!

**Comment by alliyya** [comment]
Realized we have marriage defined in the Vocabularies
https://vocab.lincsproject.ca/Skosmos/persrel/en/page/marriage

But we do not have separation or divorce defined. 

I will be using placeholder terms in the meantime. Uncertain if I'll make it up or use an external identifier.

**Comment by SusanBrown** [comment]
How about these?

> Divorce: A relationship resulting from the legal dissolution of a marriage through civil or religious processes.
> 
> Separati

on: A informal or legal relationship in which a married couple who are not divorced cease to function as married.

In the vocabulary, both should remain categorized as interpersonal relationships, I think, but not as intimate ones although in some cases a relationship will be both.
