### ISSUE TITLE
Create all ontology instances for Race.

### ISSUE THREAD

**Issue by rwarren2** [cwrc/ontology#59]
Regular values:

asian
black
father
grandmother
jew
mixed race
mixed-race
other
white

Free form values:

african
african-american
afro-caribbean
anglo-irish
arawak or american indian
black
blackwoman
coloured (mixed-race)
creole
englishness
 englishwoman from the
eurasian
foreigner
full-blooded african
indian
jew
mixed
mixed-blood
mixed-race
mohawk
native american
racially mixed
red mulatto
scotch
scottish,  
west indian
white
yellow

**Comment by rwarren2** [comment]
https://phinvads.cdc.gov/vads/SearchVocab.action
https://bioportal.bioontology.org/ontologies/SNOMED-Ethnic-Group?p=classes

**Comment by rwarren2** [comment]
As per https://docs.google.com/document/d/1gOqgqf2-b4NuKju2lgd5d852CululRvro3EIJQegfVc/edit?disco=AAAABTaBpeg&usp=comment_email_discussion&ts=597f5f9b

URI and some descriptions to be created programmatically.

**Comment by lemaka** [comment]
this is done -- see RaceColour in ontology
