### ISSUE TITLE
Should rdfs:labels and/or foaf:name have differentiators in the rdf documentation for class, properties and instances?

### ISSUE THREAD

**Issue by rwarren2** [cwrc/ontology#6]
Right now more of the instances in the ontology have an rdf:label in a few languages to label the thing in the ontology. 

In some cases, the label can have multiple contexts, such as the Language class which has the "Linguistic Ability (Spoken and/or Written)" label. Should we:

Keep rdfs:label  as being undifferentiated such as "Linguistic Ability"?
Make rdfs:label differentiated "Linguistic Ability (Spoken and/or Written)"
Make foaf:name as being undiffierentiated such as "Linguistic Ability"?
Use some of the skos labels?

**Comment by susanirenebrown** [comment]
I don’t follow this. Either we need to discuss it or you need to provide a fuller explanation.

**Comment by rwarren2** [comment]
After talking today, we'll remove the qualifiers since the data is from orlando and add the qualifying data to the description.

**Comment by alliyya** [comment]
Foaf:person for now

**Comment by rwarren2** [comment]
This is to be tried with #jewish with the rdfs:label so that Huviz testing may occur.

**Comment by antimony27** [comment]
Meeting with REED is next step to figure out the way they use "Role" and see if we can come to an agreement before including this in the onto.

**Comment by SusanBrown** [comment]
Deprecate LinguisticAbility class

**Comment by alliyya** [comment]
Deprecated LinguisticAbility class in 47d4adf481e5dbea119f514035340e43dc6c386e
