### ISSUE TITLE
revise entrepreneurial-industrialist to entrepreneurial

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#61]

**Comment by rwarren2** [comment]
You want me to deprecate the uri for #entrepreneurial-industrialist and create a new one for #entrepreneurial ?

**Comment by rwarren2** [comment]
From chat:

@rwarren2 7:51 PM - Interestingly, the ontology has "#entrepreneurial-industrialism" and "#entrepreneurial-industrialist". I'm thinking that entrepreneurial-industrialism is superfluous here. I will change the label of "#entrepreneurial-industrialist" to read "entrepreneurial'.
@antimony27  7:53 PM Yes, and industrialism is a typo. Thanks!

**Comment by rwarren2** [comment]
* Deprecated #entrepreneurial-industrialism
* Changed labels of #entrepreneurial-industrialist to entrepreneurial.
