### ISSUE TITLE
Create terms for mother, father, grand-mother, grand-father, etc...

### ISSUE THREAD

**Issue by rwarren2** [cwrc/ontology#67]
Try to link to http://purl.org/vocab/relationship/ and http://purl.org/vocab/bio/0.1/ as possible.

**Comment by lemaka** [comment]
I think we should hold off on this until after DH2017 (looks like a can of worms). 
What do you think, @SusanBrown @rwarren2 @antimony27 ?

**Comment by rwarren2** [comment]
it's partially in the ontology at this point but not in the dataset.

**Comment by SusanBrown** [comment]
seems pretty straightforward to me (ha!) but I think we should focus our efforts on getting CF finished, the documentation etc. rendering properly, and all that before tackling another thing (and why the hell isn’t there one already, she says yet again????)


On Jul 23, 2017, at 11:33 AM, rwarren2 <notifications@github.com<mailto:notifications@github.com>> wrote:


it's partially in the ontology at this point but not in the dataset.

**Comment by SusanBrown** [comment]
Rob will do the architecture and then we'll discuss it again.

**Comment by lemaka** [comment]
@colinraybrian, could you please draft definitions that capture the difference between blood relation and more fluid concepts of kinship (the concepts are already in the ontology) -- Orlando is not a place where we asserted blood relatives authoritatively because it's something we can never know for certain. Please note, we don't need to worry about free-form values.

**Comment by colinraybrian** [comment]
@rwarren2 after checking out purl RELATIONSHIP and BIO, there are many missing still. http://vocab.getty.edu/ontology has an extensive list, for example: step-child is http://vocab.getty.edu/ontology#anchor1129617585

let me know if this works

**Comment by rwarren2** [comment]
Thanks. I'm on top of this.

**Comment by rwarren2** [comment]
Ensure Sister/Brother are inserted to match @antimony27 's use.

**Comment by rwarren2** [comment]
Still needs linkages and add biological mother tags as discussed in meeting on August 17th.

**Comment by rwarren2** [comment]
Also cross link to other vocabs as available.

**Comment by rwarren2** [comment]
Add properties that are the inverse. Decision make on November 8th.

**Comment by joelacummings** [comment]
@SusanBrown This seems related to #211 How specific are Orlando's definitions for these terms? Perhaps these specify what is close enough for blood relations.

**Comment by SusanBrown** [comment]
Currently in Family and Friends tab in spreadsheet.

**Comment by SusanBrown** [comment]
Am closing because I don't think we have time to address what needs to be considered before the update, and what we need to decide is covered in the card about a definition for family.
