### ISSUE TITLE
gender instances

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#68]
consider revising cwrc:genderWomanFemale  to cwrc:WomanFemale

**Comment by lemaka** [comment]
I thought we were going with cwrc:genderWoman

can you confirm?

**Comment by SusanBrown** [comment]
confirmed

On Jul 23, 2017, at 11:30 AM, lemaka <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #68<https://github.com/cwrc/ontology/issues/68> to @SusanBrown<https://github.com/susanbrown>.
