### ISSUE TITLE
Ensure ontology and dataset are consistent.

### ISSUE THREAD

**Issue by rwarren2** [cwrc/ontology#70]
As per cwrc/HuViz#98, Need to think through a system to ensure ontology and data match each other at operation level.

**Comment by lemaka** [comment]
@rwarren2 , do you mean like a parser? and would this happen at the level of Huviz or do you mean prior

**Comment by lemaka** [comment]
in any case, I think this may be worth noting in our paper

**Comment by rwarren2** [comment]
We keep changing the ontology but not updating the example dataset. I want to write a script that checks the data examples against the current ontology. Among all other things to do.

**Comment by alliyya** [comment]
Something that checks if the triples exist in the ontology or vice versa? Comparing up-to-date.ttl to cwrc.owl?
