### ISSUE TITLE
jewishEthnicity vs JewishEthnicity

### ISSUE THREAD

**Issue by smurp** [cwrc/ontology#75]
I'm seeing both jewishEthnicity and JewishEthnicity in HuVizSHARP2017.  For example Charlotte is one and Grace has the other.

This might participate in https://github.com/cwrc/HuViz/issues/103

**Comment by SusanBrown** [comment]
This is an error in the data. Will be trying to tidy it up tonight if possible.

**Comment by rwarren2** [comment]
It should be jewishEthnicity everywhere.

**Comment by SusanBrown** [comment]
Fix in https://github.com/cwrc/ontology/blob/master/demoData/upToDate.ttl
