### ISSUE TITLE
genderManMale has "woman/female"@fr

### ISSUE THREAD

**Issue by smurp** [cwrc/ontology#76]
Little boo boo

    cwrc:genderManMale
        rdfs:label "man/male"@en, "woman/female"@fr ;

**Comment by susanirenebrown** [comment]
ha!

**Comment by rwarren2** [comment]
After speaking with @SusanBrown, change labels to man and women. And make sure they match in french and english.

**Comment by SusanBrown** [comment]
@antimony27 or @susanirenebrown to change in the data file https://github.com/cwrc/ontology/blob/master/demoData/upToDate.ttl
