### ISSUE TITLE
non-unique labels for GeographicHeritageContext instances

### ISSUE THREAD

**Issue by smurp** [cwrc/ontology#77]
In `HuVizSHARP2017` all five instances of:

    a cwrc:GeographicHeritageContext;

which relate to "Charlotte Dacre" all have the same label:

    rdfs:label "Geographic Heritage Context for Charlotte Dacre"@en ; 

Examples include:

    DACREGeogHeritageMiddlesex
    DACREGeogHeritageEngland
    ...

**Comment by lemaka** [comment]
Hi @smurp , could you please clarify what needs to be done here? Would you like for us to disambiguate the labels by adding the specific location at the end? If so, I'm not exactly understanding why...

**Comment by antimony27** [comment]
Hi @smurp I can see why this is a problem, but not sure how to solve it. Can you explain how you think the instances should be labelled?

**Comment by SusanBrown** [comment]
So yes, I think we need some explanation here of what the problem is, and also for @rwarren2 to wade in perhaps.

**Comment by SusanBrown** [comment]
These are annotations, and they have unique identifiers. They describe the fact that we have annotated the author Charlotte Dacre as having several kinds of geographic heritage, and they point to the provenance excerpt or snipped associated with the assertion.

I guess one of my questions would be why it is a problem for these annotation objects to have identical labels if they have distinct URIs. We have at present many duplicates of the same label appearing in visualizations and they don't seem to be a problem.

Below is the data in question for ease of consultation by Rob:

`<http://www.cwrc.ca/cwrcdata/DACREGeogHeritageJewish>
    a cwrc:GeographicHeritageContext ;
    rdfs:label "Geographic Heritage Context for Charlotte Dacre"@en ;
    oa:hasBody cwrc:jewish ;
    oa:hasTarget <http://www.cwrc.ca/cwrcdata/CharlotteDacre> ;
    prov:derivedFrom <http://www.cwrc.ca/cwrcdata/charlotteDacre1> .

<http://www.cwrc.ca/cwrcdata/DACREGeogHeritagePortugal>
    a cwrc:GeographicHeritageContext ;
    rdfs:label "Geographic Heritage Context for Charlotte Dacre"@en ;
    oa:hasBody cwrc:portugal ;
    oa:hasTarget <http://www.cwrc.ca/cwrcdata/CharlotteDacre> ;
    prov:derivedFrom <http://www.cwrc.ca/cwrcdata/charlotteDacre1> .

<http://www.cwrc.ca/cwrcdata/DACREGeogHeritageEngland>
    a cwrc:GeographicHeritageContext ;
    rdfs:label "Geographic Heritage Context for Charlotte Dacre"@en ;
    oa:hasBody cwrc:england ;
    oa:hasTarget <http://www.cwrc.ca/cwrcdata/CharlotteDacre> ;
    prov:derivedFrom <http://www.cwrc.ca/cwrcdata/charlotteDacre1> .

<http://www.cwrc.ca/cwrcdata/DACREGeogHeritageMiddlesex>
    a cwrc:GeographicHeritageContext ;
    rdfs:label "Geographic Heritage Context for Charlotte Dacre"@en ;
    oa:hasBody cwrc:middlesex ;
    oa:hasTarget <http://www.cwrc.ca/cwrcdata/CharlotteDacre> ;
    prov:derivedFrom <http://www.cwrc.ca/cwrcdata/charlotteDacre1> .

<http://www.cwrc.ca/cwrcdata/DACREGeogHeritageLondon>
    a cwrc:GeographicHeritageContext ;
    rdfs:label "Geographic Heritage Context for Charlotte Dacre"@en ;
    oa:hasBody cwrc:london ;
    oa:hasTarget <http://www.cwrc.ca/cwrcdata/CharlotteDacre> ;
    prov:derivedFrom <http://www.cwrc.ca/cwrcdata/charlotteDacre1> .`

**Comment by rwarren2** [comment]
Why don't we just adapt the labels to the location they are referencing?

http://www.cwrc.ca/cwrcdata/DACREGeogHeritageLondon
a cwrc:GeographicHeritageContext ;
rdfs:label "London Geographic Heritage Context for Charlotte Dacre"@en ;
oa:hasBody cwrc:london ;
oa:hasTarget http://www.cwrc.ca/cwrcdata/CharlotteDacre ;
prov:derivedFrom http://www.cwrc.ca/cwrcdata/charlotteDacre1 .`

**Comment by SusanBrown** [comment]
I would like to **understand** why labels can't be identical. Are we working around a temporary limitation with HuViz or is there something that I'm not getting? Need to understand because this would have huge implications.

Also, I would like to understand what is being labelled here. If it is, as I believe, the annotation itself (i.e. not the snippet/extraction) then it makes sense to me that it would be specific to the particular annotation though that is quite a mouthful. And there may well be some multiples for specific authors. 

Lastly, I would like confirm that cwrc:london has to be replaced by the geonames URI.

[@rwarren2 Some more questions have arisen but I am going to put them in other issues to try to keep the threads distinct. Brace yourself.]

**Comment by rwarren2** [comment]
There is no technical reason that prevent labels to be unique. 

My understanding is that @smurp is concerned that the identical labels don't communicate effectively when displaying on Huviz.

**Comment by SusanBrown** [comment]
Thanks. Can you respond to the other two points, pls?

**Comment by rwarren2** [comment]
These are the specific instances of the different contextes for Charlotte Dacre. There are multiple contextes for Charlotte Dacre, but they are _not_ the annotations themselves which are the nodes pointed to by prov:derivedFrom

**Comment by susanirenebrown** [comment]
Ok thanks for that clarification. Question about Contexts to follow in separate issue.

And if I don’t hear from you on point 3 then I am going to assume that what I said about geonames is correct.

**Comment by rwarren2** [comment]
In the final form of the cwrc data, cwrc:london has to be replaced by the geonames URI.

I've asked @antimony27 to keep to the geonames nodes so that the examples reflect what we are supposed to be doing.

If this doesn't work for demo purposes, we can keep it to cwrc:london or as above bring in the triples into the file from geonames.

**Comment by alliyya** [comment]
I think this can be closed wdyt? @SusanBrown @antimony27
