### ISSUE TITLE
several situations where rdfs:label should likely be rdfs:comment

### ISSUE THREAD

**Issue by smurp** [cwrc/ontology#78]
I would suggest that @en version of `rdfs:label` should be an `rdfs:comment` value instead

    cwrc:lowerMiddleClass
        rdfs:label "This includes employees, clerical workers, teachers, and governesses. Note, however, that some teachers go into Professional (Mr. Chips) and women starting schools and then managing them also go into Professional."@en, "classe basse moyenne"@fr ;

Other examples of this non-optimal use of `rdfs:label` include:

    cwrc:shopkeepers
    cwrc:skilledCraftpersonArtisan 
    cwrc:urban-industrialUnskilled
    cwrc:yeoman-farmer

**Comment by SusanBrown** [comment]
Should not be comment should be definition.
