### ISSUE TITLE
create contraryTo property. 

### ISSUE THREAD

**Issue by rwarren2** [cwrc/ontology#84]
eg: Use this for non-conformist vs. conformist.

**Comment by SusanBrown** [comment]
So I was mulling this over in the weekend and I don't think that this is right for non-suffragist etc. It's not that a non-suffragist is opposed or contrary to suffragism, so I don't think this predicate would be right. 

What about something like skos:disjointWith or owl:disjointWith -- I know these are for classes so perhaps wouldn't work for instances. 

At any rate, would like to talk this through before moving on this item.

**Comment by SusanBrown** [comment]
NB we might still want ContraryTo so that we can oppose, for instance, anti-semitism and anti-anti-semitism or Anti-Corn Law League and Mercantilism

**Comment by rwarren2** [comment]
I'd like to set aside a good 20 mins to talk about this in the ontology meeting. 

We can talk about something being differentFrom and being opposite to; there is no skos:disjointWith. By cheating a little bit and make these political affiliations organizations / classes and then state that there is no overlap in their memberships. This would neatly avoid the problems of people actively being opposed to versus being indifferent to certain groups.

Along with Issue #84, I want to have a clear policy of where we are going with respect to relationships and memberships. The reason is that  *everything* is a potential relationship and we are going to drown into irrelevancy unless we articulate the goal. Case in point: Everyone in the Victorian era "rel:knowsByReputation" [1] Queen Victoria, but since it is true for everyone it actually means nothing while overwhelming people with useless triples.

Would a small taxonomy of relationships strengths be useful in terms of: wasAssociatedWith, participatingMemberOf, retiredFrom with the caveat that weak relationships are not recorded?

[1] http://vocab.org/relationship/

**Comment by SusanBrown** [comment]
deferred with related issued #93

**Comment by rwarren2** [comment]
Partially added to politicalAffiliation. Perhaps this property should be reflective? 
Anti-communism contraryTo communism means communism contraryTo Anti-communism?

**Comment by SusanBrown** [comment]
Yes I think so.



On Aug 2, 2017, at 3:39 PM, rwarren2 <notifications@github.com<mailto:notifications@github.com>> wrote:


Partially added to politicalAffiliation. Perhaps this property should be reflective?
Anti-communism contraryTo communism means communism contraryTo Anti-communism?

**Comment by alliyya** [comment]
Make property reflective

**Comment by rwarren2** [comment]
Make that "owl:SymmetricProperty"

**Comment by rwarren2** [comment]
Fixed in 75d41aa8f91760080eaedb403718322126c94e2f
