### ISSUE TITLE
2nd definition (by Wheeler) of propaganda not showing up in html view

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#86]
The sparql view of the ontology is rendering only the Getty definition for this entry, even though the second one is actually more useful for our purposes. Is there are reason that it is not showing up?

`

<cwrc:Genre rdf:about="#genrePropaganda">
--
  | <rdf:value>PROPAGANDA</rdf:value>
  | <rdfs:label xml:lang="en">propaganda</rdfs:label>
  | <rdfs:label xml:lang="fr"/>
  | <rdfs:isDefinedBy rdf:resource="http://sparql.cwrc.ca/ontologies/cwrc-ONTOLOGY_DATE"/>
  | <void:inDataset rdf:resource="#datasetdefinition"/>
  | <skos:inScheme rdf:resource="#Genre"/>
  | <rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#Concept"/>
  | <skos:definition xml:lang="en">Ideas, facts, or allegations spread deliberately to support one cause or individual or to damage another. <![CDATA[<a href="#_getty_2017">(Getty, 2017)</a>]]></skos:definition>
  | <skos:definition xml:lang="es">Ideas, hechos o alegatos difundidos deliberadamente para soportar una causa o individuo o para dañar a otro. <![CDATA[<a href="#_getty_2017">(Getty, 2017)</a>]]></skos:definition>
  | <skos:definition xml:lang="nl">Ideeën, feiten of beweringen die met opzet zijn verspreid om het ene doel of individu te ondersteunen en het andere te schaden. <![CDATA[<a href="#_getty_2017">(Getty, 2017)</a>]]></skos:definition>
  | <skos:definition xml:lang="zh-hant">蓄意傳播思想、事實、主張以支持或詆毀某個理想或個人。 <![CDATA[<a href="#_getty_2017">(Getty, 2017)</a>]]></skos:definition>
  | <prov:derivedFrom rdf:resource="http://vocab.getty.edu/aat/300055539"/>
  | <rdfs:comment xml:lang="en">The description for this term is indebted to the Getty Art &amp; Architecture Thesaurus.</rdfs:comment>
  | <skos:definition xml:lang="en">(Latin, &quot;things that must be sent forth&quot;): In its original use, the term referred to a committee of cardinals the Roman Catholic church founded in 1622 (the Congregatio de propaganda fide). This group established specific educational materials to be sent with priests-in-training for foreign missions . The term is today used to refer to information, rumors, ideas, and artwork spread deliberately to help or harm another specific group, movement, belief, institution, or government. The term's connotations are mostly negative. When literature or journalism is propaganda and when it is not is hotly debated. For instance, the Roman Emperor Augustus commissioned Virgil to write The Aeneid for specific goals. He wanted Virgil to glorify Rome's greatness, instill public pride in Rome's past, and cultivate traditional Roman virtues such as loyalty to the family, the Empire, and the gods. Is this propaganda? Or patriotism? Typically, readers claim a work is propaganda when it sets forth an argument with which they personally disagree. In other cases, readers will call a work propagandistic if they can perceive that the characters or the author advances particular doctrines or principles. Harry Shaw notes: &quot;Propaganda is attacked by most critics and general readers because it is an attempt to influence opinions and actions deliberately, but by this definition all education and most literature are propagandistic&quot; (220). <![CDATA[<a href="#_wheeler_2017">(L. K Wheeler, 2017)</a>]]></skos:definition>
  | <prov:derivedFrom rdf:resource="http://web.cn.edu/kwheeler/lit_terms_p.html"/>
  | <rdfs:comment xml:lang="en">The description for this term is indebted to Dr. L. Kip Wheeler of Carson-Newman University. </rdfs:comment>
  | </cwrc:Genre>

`

**Comment by rwarren2** [comment]
Documentation generator only picks up a definition at random currently, should be fixed in new writeup.

@alliyya Can we pick up all definition tags for the active language with the new generator?

**Comment by alliyya** [comment]
Should it grab all the definition tags are just the longest?

**Comment by rwarren2** [comment]
Grab all of the definitions that match the language and put them in a numbered list.

**Comment by rwarren2** [comment]
Done by @alliyya.
