### ISSUE TITLE
URL for html view of ontology

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#88]
Which is the best one to use, do we need both?

http://sparql.cwrc.ca/ontology/cwrc.html#taxonomiesontology

or 

http://sparql.cwrc.ca/testing/cwrc.html#genrePropaganda

diagrams visible in testing but not in the first one

**Comment by rwarren2** [comment]
Deploy script not updating since 23 June 2017. Working on it.

**Comment by rwarren2** [comment]
The following from is best:
http://sparql.cwrc.ca/testing/genre#genrePropaganda

Everything will resolve at final depoy.
