### ISSUE TITLE
revise definition of epitaph

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#89]
Needs to refer to literary genre not (only) inscriptions.

**Comment by rwarren2** [comment]
@rwarren2 Reference http://rdf.muninn-project.org/ontologies/graves.html#term_epitaph with appropriate term.

**Comment by rwarren2** [comment]
There no equivalent definition in Getty. Will remove this definition and link to the Getty as a narrower.

**Comment by rwarren2** [comment]
Definition to be added in next round of genre term edits.
