### ISSUE TITLE
Do we a cwrc Person over a foaf person?

### ISSUE THREAD

**Issue by rwarren2** [cwrc/ontology#9]
Need to determine what the status of cisgendered and transgendered are. Are they gendered

**Comment by SusanBrown** [comment]
Cisgender and transgendered are instances of hasGender to my mind. They are both also broader tens of the more specific instances.

Can we use road:person for now and plan to (likely)revise later or is that problematic?

Sent from my iPhone

On Jan 24, 2017, at 12:44 PM, rwarren2 <notifications@github.com<mailto:notifications@github.com>> wrote:


Need to determine what the status of cisgendered and transgendered are. Are they gendered

-

**Comment by alliyya** [comment]
Foaf:person for now
