### ISSUE TITLE
document use of adjectival forms in genre instances

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#90]
explain e.g. philosophical and love as "genres"

**Comment by SusanBrown** [comment]
@rwarren2 please review my changes in https://github.com/cwrc/ontology/commit/d0eaf969e95428093d2908f2829b054a711e1b9c and consider whether this still needs discussion.
See related issue #151 on question of whether we can figure out some way of linking them via a predicate for "hasCombinedGenre" or something.

**Comment by alliyya** [comment]
hasGenre is to be used
