### ISSUE TITLE
Split ontology into two: one for genre and one for 'the rest'

### ISSUE THREAD

**Issue by lemaka** [cwrc/ontology#97]
Decision made: we will have two ontologies. One will be just for genre and the other will capture the rest. This means that Huviz will have to be modified to accept multiple ontologies (sorry, Shawn!).

_Why would we create several ontologies?_ Susan: because CF is quite contentious/unorthodox, while genre definitions is more straightforward, and therefore more reusable. We want to encourage users to adopt genre wholesale without having to think through our rather complex and specific cwrc ontology filled with things like gender, raceEthnicityContext, etc.

**Comment by lemaka** [comment]
see also: Template header for Genres #96

**Comment by rwarren2** [comment]
Ontology split, closing ticket.
