### ISSUE TITLE
Race and Ethnicity Vocabularies

### ISSUE THREAD

**Issue by colinraybrian** [cwrc/ontology#99]
We need to begin collecting vocabularies to refer for race and ethnicities, based on the Orlando scrape. 
Getty has several examples, but unfortunately they are described in the context of style and culture (hispanic style/culture) instead of ethnicity (hispanic as an ethnicity).

**Comment by SusanBrown** [comment]
@rwarren2 found a CDC one, I think. Can we put the links for any that seem to be candidates here? Unless we get really lucky, this may be a case where we need quite sparse definitions we write ourselves and point do but don't adopt external ones. We should start this section of the ontology with careful reference to what we've been thinking through for the paper.

**Comment by rwarren2** [comment]
Duplicate to Issue #59 I've posted a few sources there.

**Comment by rwarren2** [comment]
Closing as this is a duplicate.
